# Translations template for nova.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the nova project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: nova 2015.1.dev552\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-01-27 06:15+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: nova/context.py:91
#, python-format
msgid "Arguments dropped when creating context: %s"
msgstr ""

#: nova/debugger.py:80
msgid ""
"WARNING: Using the remote debug option changes how Nova uses the eventlet"
" library to support async IO. This could result in failures that do not "
"occur under normal operation. Use at your own risk."
msgstr ""

#: nova/service.py:286
msgid "Service killed that has no database entry"
msgstr ""

#: nova/utils.py:147
#, python-format
msgid "Expected to receive %(exp)s bytes, but actually %(act)s"
msgstr ""

#: nova/api/auth.py:73
msgid "ratelimit_v3 is removed from v3 api."
msgstr ""

#: nova/api/ec2/__init__.py:174
#, python-format
msgid ""
"Access key %(access_key)s has had %(failures)d failed authentications and"
" will be locked out for %(lock_mins)d minutes."
msgstr ""

#: nova/api/ec2/cloud.py:1320
#: nova/api/openstack/compute/contrib/floating_ips.py:207
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:223
#, python-format
msgid "multiple fixed_ips exist, using the first: %s"
msgstr ""

#: nova/api/metadata/handler.py:114
msgid ""
"X-Instance-ID present in request headers. The 'service_metadata_proxy' "
"option must be enabled to process this header."
msgstr ""

#: nova/api/metadata/handler.py:189
#, python-format
msgid ""
"X-Instance-ID-Signature: %(signature)s does not match the expected value:"
" %(expected_signature)s for id: %(instance_id)s. Request From: "
"%(remote_address)s"
msgstr ""

#: nova/api/metadata/handler.py:217
#, python-format
msgid ""
"Tenant_id %(tenant_id)s does not match tenant_id of instance "
"%(instance_id)s."
msgstr ""

#: nova/api/metadata/vendordata_json.py:47
#, python-format
msgid "%(logprefix)sfile does not exist"
msgstr ""

#: nova/api/metadata/vendordata_json.py:50
#, python-format
msgid "%(logprefix)unexpected IOError when reading"
msgstr ""

#: nova/api/metadata/vendordata_json.py:54
#, python-format
msgid "%(logprefix)sfailed to load json"
msgstr ""

#: nova/api/openstack/__init__.py:236 nova/api/openstack/__init__.py:430
#, python-format
msgid ""
"Extension %(ext_name)s: Cannot extend resource %(collection)s: No such "
"resource"
msgstr ""

#: nova/api/openstack/__init__.py:304
#, python-format
msgid "Extensions in both blacklist and whitelist: %s"
msgstr ""

#: nova/api/openstack/common.py:424
msgid "Rejecting snapshot request, snapshots currently disabled"
msgstr ""

#: nova/api/openstack/extensions.py:231
#, python-format
msgid "Failed to load extension %(ext_factory)s: %(exc)s"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/servers.py:110
#, python-format
msgid "Not loading %s because it is in the blacklist"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/servers.py:115
#, python-format
msgid "Not loading %s because it is not in the whitelist"
msgstr ""

#: nova/api/openstack/compute/views/servers.py:198
msgid "Instance has had its instance_type removed from the DB"
msgstr ""

#: nova/cells/manager.py:80
msgid ""
"The cells feature of Nova is considered experimental by the OpenStack "
"project because it receives much less testing than the rest of Nova. This"
" may change in the future, but current deployers should be aware that the"
" use of it in production right now may be risky."
msgstr ""

#: nova/cells/messaging.py:1215
#, python-format
msgid "No match when trying to update BDM: %(bdm)s"
msgstr ""

#: nova/cells/messaging.py:1696
#, python-format
msgid "No cell_name for %(method)s() from API"
msgstr ""

#: nova/cells/messaging.py:1713
msgid "No cell_name for instance update from API"
msgstr ""

#: nova/cells/weights/mute_child.py:66
#, python-format
msgid ""
"%(cell)s has not been seen since %(last_seen)s and is being treated as "
"mute."
msgstr ""

#: nova/compute/api.py:1550
#, python-format
msgid "Failed to delete snapshot from shelved instance (%s)."
msgstr ""

#: nova/compute/api.py:1723
#, python-format
msgid "Flavor %d not found"
msgstr ""

#: nova/compute/api.py:1748
#, python-format
msgid "instance's host %s is down, deleting from database"
msgstr ""

#: nova/compute/api.py:2602
#, python-format
msgid "%(overs)s quota exceeded for %(pid)s, tried to resize instance."
msgstr ""

#: nova/compute/api.py:3559
#, python-format
msgid "More than 1 AZ for host %s"
msgstr ""

#: nova/compute/manager.py:782
msgid ""
"Hypervisor driver does not support instance shared storage check, "
"assuming it's not on shared storage"
msgstr ""

#: nova/compute/manager.py:949
#, python-format
msgid ""
"Instance in transitional state (%(task_state)s) at start-up and power "
"state is (%(power_state)s), clearing task state"
msgstr ""

#: nova/compute/manager.py:960
#, python-format
msgid ""
"Instance in transitional state (%(task_state)s) at start-up and power "
"state is (%(power_state)s), clearing task state and unpausing the "
"instance"
msgstr ""

#: nova/compute/manager.py:1063
msgid "Hypervisor driver does not support resume guests"
msgstr ""

#: nova/compute/manager.py:1068
msgid "Failed to resume instance"
msgstr ""

#: nova/compute/manager.py:1078
msgid "Hypervisor driver does not support firewall rules"
msgstr ""

#: nova/compute/manager.py:1120
#, python-format
msgid "Unexpected power state %d"
msgstr ""

#: nova/compute/manager.py:1236
msgid "Hypervisor driver does not support security groups."
msgstr ""

#: nova/compute/manager.py:1272
#, python-format
msgid ""
"Treating negative config value (%(retries)s) for 'block_device_retries' "
"as 0."
msgstr ""

#: nova/compute/manager.py:1287
#, python-format
msgid "Volume id: %s finished being created but was not set as 'available'"
msgstr ""

#: nova/compute/manager.py:1636
msgid "Instance build timed out. Set to error state."
msgstr ""

#: nova/compute/manager.py:1664
#, python-format
msgid ""
"Treating negative config value (%(retries)s) for "
"'network_allocate_retries' as 0."
msgstr ""

#: nova/compute/manager.py:1694
#, python-format
msgid "Instance failed network setup (attempt %(attempt)d of %(attempts)d)"
msgstr ""

#: nova/compute/manager.py:1875
msgid ""
"Failed to create block device for instance due to being over volume "
"resource quota"
msgstr ""

#: nova/compute/manager.py:2192
msgid "No more network or fixed IP to be allocated"
msgstr ""

#: nova/compute/manager.py:2468
#, python-format
msgid "Ignoring EndpointNotFound: %s"
msgstr ""

#: nova/compute/manager.py:2486
#, python-format
msgid "Failed to delete volume: %(volume_id)s due to %(exc)s"
msgstr ""

#: nova/compute/manager.py:2966
#, python-format
msgid ""
"trying to reboot a non-running instance: (state: %(state)s expected: "
"%(running)s)"
msgstr ""

#: nova/compute/manager.py:3002
msgid "Reboot failed but instance is running"
msgstr ""

#: nova/compute/manager.py:3022
msgid "Instance disappeared during reboot"
msgstr ""

#: nova/compute/manager.py:3096
#, python-format
msgid ""
"trying to snapshot a non-running instance: (state: %(state)s expected: "
"%(running)s)"
msgstr ""

#: nova/compute/manager.py:3129
#, python-format
msgid "Error while trying to clean up image %s"
msgstr ""

#: nova/compute/manager.py:3231
msgid "set_admin_password is not implemented by this driver or guest instance."
msgstr ""

#: nova/compute/manager.py:3268
#, python-format
msgid ""
"trying to inject a file into a non-running (state: %(current_state)s "
"expected: %(expected_state)s)"
msgstr ""

#: nova/compute/manager.py:3292
msgid ""
"Unable to find a different image to use for rescue VM, using instance's "
"current image"
msgstr ""

#: nova/compute/manager.py:3447
#, python-format
msgid ""
"Unexpected confirmation status '%(status)s' of migration %(id)s, exit "
"confirmation process"
msgstr ""

#: nova/compute/manager.py:4664
msgid "Detaching volume from unknown instance"
msgstr ""

#: nova/compute/manager.py:4675
#, python-format
msgid ""
"Ignoring DiskNotFound exception while detaching volume %(volume_id)s from"
" %(mp)s: %(err)s"
msgstr ""

#: nova/compute/manager.py:5488
#, python-format
msgid "Setting migration %(migration_id)s to error: %(reason)s"
msgstr ""

#: nova/compute/manager.py:5670
msgid "Bandwidth usage not supported by hypervisor."
msgstr ""

#: nova/compute/manager.py:5792
#, python-format
msgid ""
"While synchronizing instance power states, found %(num_db_instances)s "
"instances in the database and %(num_vm_instances)s instances on the "
"hypervisor."
msgstr ""

#: nova/compute/manager.py:5911
#, python-format
msgid ""
"Instance shutdown by itself. Calling the stop API. Current vm_state: "
"%(vm_state)s, current task_state: %(task_state)s, current DB power_state:"
" %(db_power_state)s, current VM power_state: %(vm_power_state)s"
msgstr ""

#: nova/compute/manager.py:5938
msgid "Instance is suspended unexpectedly. Calling the stop API."
msgstr ""

#: nova/compute/manager.py:5954
msgid "Instance is paused unexpectedly. Ignore."
msgstr ""

#: nova/compute/manager.py:5960
msgid "Instance is unexpectedly not found. Ignore."
msgstr ""

#: nova/compute/manager.py:5966
#, python-format
msgid ""
"Instance is not stopped. Calling the stop API. Current vm_state: "
"%(vm_state)s, current task_state: %(task_state)s, current DB power_state:"
" %(db_power_state)s, current VM power_state: %(vm_power_state)s"
msgstr ""

#: nova/compute/manager.py:5988
msgid "Paused instance shutdown by itself. Calling the stop API."
msgstr ""

#: nova/compute/manager.py:6002
msgid "Instance is not (soft-)deleted."
msgstr ""

#: nova/compute/manager.py:6036
#, python-format
msgid "Periodic reclaim failed to delete instance: %s"
msgstr ""

#: nova/compute/manager.py:6108
#, python-format
msgid ""
"Detected instance with name label '%s' which is marked as DELETED but "
"still present on host."
msgstr ""

#: nova/compute/manager.py:6123
msgid "set_bootable is not implemented for the current driver"
msgstr ""

#: nova/compute/manager.py:6144
#, python-format
msgid "Periodic cleanup failed to delete instance: %s"
msgstr ""

#: nova/compute/resource_tracker.py:116
msgid ""
"Host field should not be set on the instance until resources have been "
"claimed."
msgstr ""

#: nova/compute/resource_tracker.py:121
msgid ""
"Node field should not be set on the instance until resources have been "
"claimed."
msgstr ""

#: nova/compute/resource_tracker.py:296
#, python-format
msgid "Cannot get the metrics from %s."
msgstr ""

#: nova/compute/resource_tracker.py:447
#, python-format
msgid "No compute node record for %(host)s:%(node)s"
msgstr ""

#: nova/compute/resource_tracker.py:474
#, python-format
msgid "No service record for host %s"
msgstr ""

#: nova/compute/resource_tracker.py:677
msgid "Instance not resizing, skipping migration."
msgstr ""

#: nova/compute/resource_tracker.py:692
msgid "Flavor could not be found, skipping migration."
msgstr ""

#: nova/compute/resource_tracker.py:782
#, python-format
msgid ""
"Detected running orphan instance: %(uuid)s (consuming %(memory_mb)s MB "
"memory)"
msgstr ""

#: nova/compute/rpcapi.py:374
msgid ""
"Live migration with clients before RPC version 3.32 is known to be buggy "
"with shared block storage. See "
"https://bugs.launchpad.net/nova/+bug/1250751 for more information!"
msgstr ""

#: nova/compute/utils.py:222
#, python-format
msgid "Can't access image %(image_id)s: %(error)s"
msgstr ""

#: nova/compute/utils.py:252
#, python-format
msgid ""
"Metadata value %(value)s for %(key)s is not of type %(type)s. Using "
"default value %(default)s."
msgstr ""

#: nova/compute/utils.py:376
#, python-format
msgid ""
"No host name specified for the notification of HostAPI.%s and it will be "
"ignored"
msgstr ""

#: nova/compute/monitors/__init__.py:189
#, python-format
msgid "The following monitors have been disabled: %s"
msgstr ""

#: nova/compute/resources/__init__.py:31
#, python-format
msgid "Compute resource plugin %s was not loaded"
msgstr ""

#: nova/conductor/api.py:322
msgid ""
"Timed out waiting for nova-conductor.  Is it running? Or did this service"
" start before nova-conductor?  Reattempting establishment of nova-"
"conductor connection..."
msgstr ""

#: nova/conductor/manager.py:754
msgid "No valid host found for unshelve instance"
msgstr ""

#: nova/conductor/manager.py:797
msgid "No valid host found for rebuild"
msgstr ""

#: nova/console/serial.py:98
#, python-format
msgid ""
"serial_console.port_range should be <num>:<num>. Given value "
"%(port_range)s could not be parsed. Taking the default port range "
"%(default)s."
msgstr ""

#: nova/consoleauth/manager.py:84
#, python-format
msgid "Token: %(token)s failed to save into memcached."
msgstr ""

#: nova/consoleauth/manager.py:95
#, python-format
msgid "Instance: %(instance_uuid)s failed to save into memcached"
msgstr ""

#: nova/db/sqlalchemy/api.py:185
#, python-format
msgid "Deadlock detected when running '%(func_name)s': Retrying..."
msgstr ""

#: nova/db/sqlalchemy/api.py:3480
#, python-format
msgid "Change will make usage less than 0 for the following resources: %s"
msgstr ""

#: nova/keymgr/mock_key_mgr.py:54
msgid "This key manager is not suitable for use in production deployments"
msgstr ""

#: nova/keymgr/single_key_mgr.py:40
msgid ""
"This key manager is insecure and is not recommended for production "
"deployments"
msgstr ""

#: nova/keymgr/single_key_mgr.py:72
#, python-format
msgid "Not deleting key %s"
msgstr ""

#: nova/network/floating_ips.py:195
#, python-format
msgid "Address |%(address)s| is not allocated"
msgstr ""

#: nova/network/floating_ips.py:199
#, python-format
msgid "Address |%(address)s| is not allocated to your project |%(project)s|"
msgstr ""

#: nova/network/floating_ips.py:233
#, python-format
msgid "Quota exceeded for %s, tried to allocate floating IP"
msgstr ""

#: nova/network/floating_ips.py:390
#, python-format
msgid "Failed to disassociated floating address: %s"
msgstr ""

#: nova/network/floating_ips.py:555
#, python-format
msgid ""
"Floating ip address |%(address)s| no longer belongs to instance "
"%(instance_uuid)s. Will not migrate it "
msgstr ""

#: nova/network/floating_ips.py:592
#, python-format
msgid ""
"Floating ip address |%(address)s| no longer belongs to instance "
"%(instance_uuid)s. Will not setup it."
msgstr ""

#: nova/network/floating_ips.py:636
#, python-format
msgid ""
"Database inconsistency: DNS domain |%s| is registered in the Nova db but "
"not visible to either the floating or instance DNS driver. It will be "
"ignored."
msgstr ""

#: nova/network/floating_ips.py:676
#, python-format
msgid "Domain |%(domain)s| already exists, changing zone to |%(av_zone)s|."
msgstr ""

#: nova/network/floating_ips.py:685
#, python-format
msgid "Domain |%(domain)s| already exists, changing project to |%(project)s|."
msgstr ""

#: nova/network/ldapdns.py:108
#, python-format
msgid ""
"Found multiple matches for domain %(domain)s.\n"
"%(entry)s"
msgstr ""

#: nova/network/ldapdns.py:135
#, python-format
msgid "Unable to dequalify.  %(name)s is not in %(domain)s.\n"
msgstr ""

#: nova/network/ldapdns.py:376
msgid "This shouldn't be getting called except during testing."
msgstr ""

#: nova/network/linux_net.py:240
#, python-format
msgid "Attempted to remove chain %s which does not exist"
msgstr ""

#: nova/network/linux_net.py:309
#, python-format
msgid ""
"Tried to remove rule that was not there: %(chain)r %(rule)r %(wrap)r "
"%(top)r"
msgstr ""

#: nova/network/linux_net.py:785
#, python-format
msgid "Removed %(num)d duplicate rules for floating ip %(float)s"
msgstr ""

#: nova/network/linux_net.py:1203
#, python-format
msgid "hostname %s too long, truncating."
msgstr ""

#: nova/network/linux_net.py:1685
#, python-format
msgid "%s failed. Not Retrying."
msgstr ""

#: nova/network/linux_net.py:1689
#, python-format
msgid "%(cmd)s failed. Sleeping %(time)s seconds before retry."
msgstr ""

#: nova/network/manager.py:814
#, python-format
msgid "instance-dns-zone not found |%s|."
msgstr ""

#: nova/network/manager.py:821
#, python-format
msgid ""
"instance-dns-zone is |%(domain)s|, which is in availability zone "
"|%(zone)s|. Instance is in zone |%(zone2)s|. No DNS record will be "
"created."
msgstr ""

#: nova/network/manager.py:863
#, python-format
msgid ""
"Quota exceeded for project %(pid)s, tried to allocate fixed IP. %(used)s "
"of %(allowed)s are in use or are already reserved."
msgstr ""

#: nova/network/manager.py:958
msgid "Error cleaning up fixed ip allocation. Manual cleanup may be required."
msgstr ""

#: nova/network/manager.py:1060
#, python-format
msgid "Failed to rollback quota for deallocate fixed ip: %s"
msgstr ""

#: nova/network/manager.py:1073
#, python-format
msgid "IP %s leased that is not associated"
msgstr ""

#: nova/network/manager.py:1079
#, python-format
msgid "IP |%s| leased that isn't allocated"
msgstr ""

#: nova/network/manager.py:1088
#, python-format
msgid "IP %s released that is not associated"
msgstr ""

#: nova/network/manager.py:1092
#, python-format
msgid "IP %s released that was not leased"
msgstr ""

#: nova/network/manager.py:1175
#, python-format
msgid ""
"Subnet(s) too large, defaulting to /%s.  To override, specify "
"network_size flag."
msgstr ""

#: nova/network/minidns.py:122
#, python-format
msgid "Cannot delete entry |%s|"
msgstr ""

#: nova/network/minidns.py:207
#, python-format
msgid "Cannot delete domain |%s|"
msgstr ""

#: nova/network/neutronv2/api.py:279
#, python-format
msgid "Neutron error: Fixed IP %s is already in use."
msgstr ""

#: nova/network/neutronv2/api.py:284
#, python-format
msgid "Neutron error: Port quota exceeded in tenant: %s"
msgstr ""

#: nova/network/neutronv2/api.py:289
#, python-format
msgid "Neutron error: No more fixed IPs in network: %s"
msgstr ""

#: nova/network/neutronv2/api.py:293
#, python-format
msgid ""
"Neutron error: MAC address %(mac)s is already in use on network "
"%(network)s."
msgstr ""

#: nova/network/neutronv2/api.py:592
#, python-format
msgid "Port %s does not exist"
msgstr ""

#: nova/network/neutronv2/api.py:596
#, python-format
msgid "Failed to delete port %s for instance."
msgstr ""

#: nova/network/neutronv2/api.py:1348
#, python-format
msgid ""
"Network %(id)s not matched with the tenants network! The ports tenant "
"%(tenant_id)s will be used."
msgstr ""

#: nova/network/security_group/neutron_driver.py:434
#, python-format
msgid ""
"Cannot add security group %(name)s to %(instance)s since the port "
"%(port_id)s does not meet security requirements"
msgstr ""

#: nova/openstack/common/loopingcall.py:87
#, python-format
msgid "task %(func_name)r run outlasted interval by %(delay).2f sec"
msgstr ""

#: nova/openstack/common/service.py:356
#, python-format
msgid "pid %d not in child list"
msgstr ""

#: nova/pci/manager.py:112
#, python-format
msgid ""
"Trying to remove device with %(status)s ownership %(instance_uuid)s "
"because of %(pci_exception)s"
msgstr ""

#: nova/scheduler/host_manager.py:170
#, python-format
msgid "Metric name unknown of %r"
msgstr ""

#: nova/scheduler/host_manager.py:185
#, python-format
msgid ""
"Host %(hostname)s has more disk space than database expected "
"(%(physical)sgb > %(database)sgb)"
msgstr ""

#: nova/scheduler/host_manager.py:410
#, python-format
msgid "No service for compute ID %s"
msgstr ""

#: nova/scheduler/utils.py:84
#, python-format
msgid "Failed to %(service)s_%(method)s: %(ex)s"
msgstr ""

#: nova/scheduler/utils.py:93
#, python-format
msgid "Setting instance to %s state."
msgstr ""

#: nova/scheduler/utils.py:239
#, python-format
msgid "Ignoring the invalid elements of the option %(name)s: %(options)s"
msgstr ""

#: nova/scheduler/utils.py:338
#, python-format
msgid ""
"Retrying %(name)s after a MessagingTimeout, attempt %(attempt)s of "
"%(retries)s."
msgstr ""

#: nova/scheduler/filters/compute_filter.py:47
#, python-format
msgid "%(host_state)s has not been heard from in a while"
msgstr ""

#: nova/scheduler/filters/core_filter.py:51
#: nova/scheduler/filters/exact_core_filter.py:36
msgid "VCPUs not set; assuming CPU collection broken"
msgstr ""

#: nova/scheduler/filters/core_filter.py:102
#, python-format
msgid "Could not decode cpu_allocation_ratio: '%s'"
msgstr ""

#: nova/scheduler/filters/disk_filter.py:87
#, python-format
msgid "Could not decode disk_allocation_ratio: '%s'"
msgstr ""

#: nova/scheduler/filters/io_ops_filter.py:76
#, python-format
msgid "Could not decode max_io_ops_per_host: '%s'"
msgstr ""

#: nova/scheduler/filters/num_instances_filter.py:71
#, python-format
msgid "Could not decode max_instances_per_host: '%s'"
msgstr ""

#: nova/scheduler/filters/ram_filter.py:95
#, python-format
msgid "Could not decode ram_allocation_ratio: '%s'"
msgstr ""

#: nova/servicegroup/api.py:88
#, python-format
msgid ""
"Report interval must be less than service down time. Current config: "
"<service_down_time: %(service_down_time)s, report_interval: "
"%(report_interval)s>. Setting service_down_time to: "
"%(new_service_down_time)s"
msgstr ""

#: nova/storage/linuxscsi.py:101
#, python-format
msgid "Multipath call failed exit (%(code)s)"
msgstr ""

#: nova/storage/linuxscsi.py:122
#, python-format
msgid "Couldn't find multipath device %s"
msgstr ""

#: nova/storage/linuxscsi.py:131
#, python-format
msgid "Skip faulty line \"%(dev_line)s\" of multipath device %(mdev)s"
msgstr ""

#: nova/virt/configdrive.py:178
#, python-format
msgid "Image config drive option %(image_prop)s is invalid and will be ignored"
msgstr ""

#: nova/virt/fake.py:232
#, python-format
msgid "Key '%(key)s' not in instances '%(inst)s'"
msgstr ""

#: nova/virt/storage_users.py:65 nova/virt/storage_users.py:93
#, python-format
msgid "Cannot decode JSON from %(id_path)s"
msgstr ""

#: nova/virt/disk/api.py:366
#, python-format
msgid "Ignoring error injecting data into image %(image)s (%(e)s)"
msgstr ""

#: nova/virt/disk/api.py:456
#, python-format
msgid "Ignoring error injecting %(inject)s into image (%(e)s)"
msgstr ""

#: nova/virt/disk/mount/api.py:124
msgid "Device allocation failed after repeated retries."
msgstr ""

#: nova/virt/disk/mount/nbd.py:59
msgid "No free nbd devices"
msgstr ""

#: nova/virt/disk/mount/nbd.py:110
#, python-format
msgid "Detaching from erroneous nbd device returned error: %s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:89
msgid ""
"Please consider to execute setup before trying to configure debug log "
"message."
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:193
#, python-format
msgid "Unable to force TCG mode, libguestfs too old? %s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:228
#, python-format
msgid "Failed to close augeas %s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:236
#, python-format
msgid "Failed to shutdown appliance %s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:244
#, python-format
msgid "Failed to close guest handle %s"
msgstr ""

#: nova/virt/hyperv/snapshotops.py:119
#, python-format
msgid "Failed to remove snapshot for VM %s"
msgstr ""

#: nova/virt/hyperv/vmops.py:501
msgid "Timed out while waiting for soft shutdown."
msgstr ""

#: nova/virt/hyperv/vmutils.py:462
#, python-format
msgid ""
"Disk not found on controller \"%(controller_path)s\" with address "
"\"%(address)s\""
msgstr ""

#: nova/virt/hyperv/volumeops.py:134
msgid "Could not determine iscsi initiator name"
msgstr ""

#: nova/virt/ironic/driver.py:104
#, python-format
msgid "Power state %s not found."
msgstr ""

#: nova/virt/ironic/driver.py:207
#, python-format
msgid "cpu_arch not defined for node '%s'"
msgstr ""

#: nova/virt/ironic/driver.py:235
#, python-format
msgid "Ignoring malformed capability '%s'. Format should be 'key:val'."
msgstr ""

#: nova/virt/ironic/driver.py:525
#, python-format
msgid "Warning, memory usage is 0 for %(instance)s on baremetal node %(node)s."
msgstr ""

#: nova/virt/ironic/driver.py:532
#, python-format
msgid "Warning, number of cpus is 0 for %(instance)s on baremetal node %(node)s."
msgstr ""

#: nova/virt/ironic/driver.py:718
#, python-format
msgid "Destroy called on non-existing instance %s."
msgstr ""

#: nova/virt/libvirt/driver.py:430
#, python-format
msgid "Invalid cachemode %(cache_mode)s specified for disk type %(disk_type)s."
msgstr ""

#: nova/virt/libvirt/driver.py:504
#, python-format
msgid ""
"The libvirt driver is not tested on %(type)s/%(arch)s by the OpenStack "
"project and thus its quality can not be ensured. For more information, "
"see: https://wiki.openstack.org/wiki/HypervisorSupportMatrix"
msgstr ""

#: nova/virt/libvirt/driver.py:523
msgid ""
"Running libvirt-lxc without user namespaces is dangerous. Containers "
"spawned by Nova will be run as the host's root user. It is highly "
"suggested that user namespaces be used in a public or multi-tenant "
"environment."
msgstr ""

#: nova/virt/libvirt/driver.py:634
msgid "Cannot destroy instance, operation time out"
msgstr ""

#: nova/virt/libvirt/driver.py:658
msgid "During wait destroy, instance disappeared."
msgstr ""

#: nova/virt/libvirt/driver.py:745
msgid "Instance may be still running, destroy it again."
msgstr ""

#: nova/virt/libvirt/driver.py:800
#, python-format
msgid "Ignoring Volume Error on vol %(vol_id)s during delete %(exc)s"
msgstr ""

#: nova/virt/libvirt/driver.py:1154 nova/virt/libvirt/driver.py:1162
msgid "During detach_volume, instance disappeared."
msgstr ""

#: nova/virt/libvirt/driver.py:1207
msgid "During detach_interface, instance disappeared."
msgstr ""

#: nova/virt/libvirt/driver.py:1945
msgid "Failed to soft reboot instance. Trying hard reboot."
msgstr ""

#: nova/virt/libvirt/driver.py:2611
#, python-format
msgid "Image %s not found on disk storage. Continue without injecting data"
msgstr ""

#: nova/virt/libvirt/driver.py:2797
msgid "File injection into a boot from volume instance is not supported"
msgstr ""

#: nova/virt/libvirt/driver.py:2872
msgid "Instance disappeared while detaching a PCI device from it."
msgstr ""

#: nova/virt/libvirt/driver.py:2992
#, python-format
msgid "Cannot update service status on host: %s,since it is not registered."
msgstr ""

#: nova/virt/libvirt/driver.py:2995
#, python-format
msgid "Cannot update service status on host: %s,due to an unexpected exception."
msgstr ""

#: nova/virt/libvirt/driver.py:3305
msgid "Too many id maps, only included first five."
msgstr ""

#: nova/virt/libvirt/driver.py:3315
#, python-format
msgid "Invalid value for id mapping %s"
msgstr ""

#: nova/virt/libvirt/driver.py:3950
msgid ""
"Old property name \"hw_watchdog_action\" is now deprecated and will be "
"removed in the next release. Use updated property name "
"\"hw:watchdog_action\" instead"
msgstr ""

#: nova/virt/libvirt/driver.py:4239
#, python-format
msgid "Timeout waiting for vif plugging callback for instance %(uuid)s"
msgstr ""

#: nova/virt/libvirt/driver.py:4260
#, python-format
msgid "couldn't obtain the XML from domain: %(uuid)s, exception: %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:4317
msgid ""
"Cannot get the number of cpu, because this function is not implemented "
"for this platform. "
msgstr ""

#: nova/virt/libvirt/driver.py:4379
#, python-format
msgid "couldn't obtain the vpu count from domain id: %(uuid)s, exception: %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:4410
#, python-format
msgid "couldn't obtain the memory from domain: %(uuid)s, exception: %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:4571
#, python-format
msgid "URI %(uri)s does not support listDevices: %(error)s"
msgstr ""

#: nova/virt/libvirt/driver.py:5220
#, python-format
msgid ""
"An error occurred trying to live migrate. Falling back to legacy live "
"migrate flow. Error: %s"
msgstr ""

#: nova/virt/libvirt/driver.py:5363
#, python-format
msgid "plug_vifs() failed %(cnt)d. Retry up to %(max_retry)d."
msgstr ""

#: nova/virt/libvirt/driver.py:5576
#, python-format
msgid ""
"Error from libvirt while getting description of %(instance_name)s: [Error"
" Code %(error_code)s] %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:5584
#, python-format
msgid ""
"Periodic task is updating the host stat, it is trying to get disk "
"%(i_name)s, but disk file was removed by concurrent operations such as "
"resize."
msgstr ""

#: nova/virt/libvirt/driver.py:5590
#, python-format
msgid ""
"Periodic task is updating the host stat, it is trying to get disk "
"%(i_name)s, but access is denied. It is most likely due to a VM that "
"exists on the compute node but is not managed by Nova."
msgstr ""

#: nova/virt/libvirt/driver.py:5599
#, python-format
msgid ""
"Periodic task is updating the host stats, it is trying to get disk info "
"for %(i_name)s, but the backing volume block device was removed by "
"concurrent operations such as resize. Error: %(error)s"
msgstr ""

#: nova/virt/libvirt/firewall.py:60
msgid ""
"Libvirt module could not be loaded. NWFilterFirewall will not work "
"correctly."
msgstr ""

#: nova/virt/libvirt/host.py:366
#, python-format
msgid "URI %(uri)s does not support events: %(error)s"
msgstr ""

#: nova/virt/libvirt/host.py:382
#, python-format
msgid "URI %(uri)s does not support connection events: %(error)s"
msgstr ""

#: nova/virt/libvirt/host.py:617
#, python-format
msgid "URI %(uri)s does not support full set of host capabilities: %(error)s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:331
#, python-format
msgid ""
"Instance %(instance)s is using a backing file %(backing)s which does not "
"appear in the image service"
msgstr ""

#: nova/virt/libvirt/imagecache.py:541
#, python-format
msgid ""
"image %(id)s at (%(base_file)s): warning -- an absent base file is in "
"use! instances: %(instance_list)s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:581
#, python-format
msgid "%s swap image was used by instance but no back files existing!"
msgstr ""

#: nova/virt/libvirt/imagecache.py:607
#, python-format
msgid "Unknown base file: %s"
msgstr ""

#: nova/virt/libvirt/lvm.py:104
#, python-format
msgid ""
"Volume group %(vg)s will not be able to hold sparse volume %(lv)s. "
"Virtual volume size is %(size)db, but free space on volume group is only "
"%(free_space)db."
msgstr ""

#: nova/virt/libvirt/rbd_utils.py:267
#, python-format
msgid "rbd remove %(volume)s in pool %(pool)s failed"
msgstr ""

#: nova/virt/libvirt/remotefs.py:45 nova/virt/libvirt/volume.py:775
#: nova/virt/libvirt/volume.py:1013
#, python-format
msgid "%s is already mounted"
msgstr ""

#: nova/virt/libvirt/utils.py:71 nova/virt/libvirt/utils.py:77
msgid "systool is not installed"
msgstr ""

#: nova/virt/libvirt/volume.py:144
#, python-format
msgid "Unknown content in connection_info/qos_specs: %s"
msgstr ""

#: nova/virt/libvirt/volume.py:343
#, python-format
msgid ""
"ISCSI volume not yet found at: %(disk_dev)s. Will rescan & retry.  Try "
"number: %(tries)s"
msgstr ""

#: nova/virt/libvirt/volume.py:414
#, python-format
msgid "Unable to delete volume device %s"
msgstr ""

#: nova/virt/libvirt/volume.py:425
#, python-format
msgid ""
"Failed to remove multipath device descriptor %(dev_mapper)s. Exception "
"message: %(msg)s"
msgstr ""

#: nova/virt/libvirt/volume.py:900
#, python-format
msgid "AoE volume not yet found at: %(aoedevpath)s. Try number: %(tries)s"
msgstr ""

#: nova/virt/libvirt/volume.py:1110
#, python-format
msgid ""
"Fibre volume not yet found at: %(mount_device)s. Will rescan & retry.  "
"Try number: %(tries)s"
msgstr ""

#: nova/virt/libvirt/volume.py:1166
#, python-format
msgid "multipath-tools probably work improperly. devices to remove = %s."
msgstr ""

#: nova/virt/libvirt/volume.py:1220
msgid "Value required for 'scality_sofs_config'"
msgstr ""

#: nova/virt/libvirt/volume.py:1231
#, python-format
msgid "Cannot access 'scality_sofs_config': %s"
msgstr ""

#: nova/virt/libvirt/volume.py:1237
msgid "Cannot execute /sbin/mount.sofs"
msgstr ""

#: nova/virt/libvirt/volume.py:1252
msgid "Cannot mount Scality SOFS, check syslog for errors"
msgstr ""

#: nova/virt/vmwareapi/driver.py:162
#, python-format
msgid "The following clusters could not be found in the vCenter %s"
msgstr ""

#: nova/virt/vmwareapi/driver.py:206
msgid "datastore_regex is ignored when PBM is enabled"
msgstr ""

#: nova/virt/vmwareapi/driver.py:243
msgid "Instance cannot be found in host, or in an unknown state."
msgstr ""

#: nova/virt/vmwareapi/imagecache.py:74
#, python-format
msgid "Unable to delete %(file)s. Exception: %(ex)s"
msgstr ""

#: nova/virt/vmwareapi/vif.py:118
#, python-format
msgid ""
"No valid network found in %(opaque)s, from %(bridge)s or "
"%(integration_bridge)s"
msgstr ""

#: nova/virt/vmwareapi/vim_util.py:115
#, python-format
msgid "Unable to retrieve value for %(path)s Reason: %(reason)s"
msgstr ""

#: nova/virt/vmwareapi/vm_util.py:1124
#, python-format
msgid "Failed to get cluster references %s"
msgstr ""

#: nova/virt/vmwareapi/vm_util.py:1136
#, python-format
msgid "Failed to get resource pool references %s"
msgstr ""

#: nova/virt/vmwareapi/vm_util.py:1247
#, python-format
msgid ""
"vmware_ostype from image is not recognised: '%(ostype)s'. An invalid os "
"type may be one cause of this instance creation failure"
msgstr ""

#: nova/virt/vmwareapi/vm_util.py:1344
msgid "vmwareapi:vm_util:clone_vmref_for_instance, called with vm_ref=None"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:375
#, python-format
msgid ""
"Destination %s already exists! Concurrent moves can lead to unexpected "
"results."
msgstr ""

#: nova/virt/vmwareapi/vmops.py:837
msgid "Instance does not exist on backend"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:866
#, python-format
msgid ""
"In vmwareapi:vmops:_destroy_instance, got this exception while un-"
"registering the VM: %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:889
msgid ""
"In vmwareapi:vmops:_destroy_instance, exception while deleting the VM "
"contents from the disk"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1124
#, python-format
msgid ""
"In vmwareapi:vmops:confirm_migration, got this exception while destroying"
" the VM: %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1580
#, python-format
msgid "Root disk file creation failed - %s"
msgstr ""

#: nova/virt/xenapi/agent.py:194
#, python-format
msgid "Ignoring error while configuring instance with agent: %s"
msgstr ""

#: nova/virt/xenapi/agent.py:270
#, python-format
msgid "Unable to update the agent due to: %(exc)s"
msgstr ""

#: nova/virt/xenapi/agent.py:422
msgid "Invalid 'agent_present' value. Falling back to the default."
msgstr ""

#: nova/virt/xenapi/driver.py:386
#, python-format
msgid "Could not determine key: %s"
msgstr ""

#: nova/virt/xenapi/host.py:292
#, python-format
msgid "Failed to extract instance support from %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:326 nova/virt/xenapi/vm_utils.py:341
msgid "VM already halted, skipping shutdown..."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:845
#, python-format
msgid "Multiple base images for image: %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1235
#, python-format
msgid ""
"Fast cloning is only supported on default local SR of type ext. SR on "
"this system was found to be of type %s. Ignoring the cow flag."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1310
#, python-format
msgid "Unrecognized cache_images value '%s', defaulting to True"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1386
#, python-format
msgid "Invalid value '%s' for torrent_images"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1409
#, python-format
msgid "Invalid value '%d' for image_compression_level"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1846
#, python-format
msgid "Retry SR scan due to error: %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1879
#, python-format
msgid "Flag sr_matching_filter '%s' does not respect formatting convention"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2588
msgid "ipxe_boot_menu_url not set, user will have to enter URL manually..."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2594
msgid "ipxe_network_name not set, user will have to enter IP manually..."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2605
#, python-format
msgid ""
"Unable to find network matching '%(network_name)s', user will have to "
"enter IP manually..."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2629
#, python-format
msgid "ISO creation tool '%s' does not exist."
msgstr ""

#: nova/virt/xenapi/vmops.py:454
msgid "ipxe_boot is True but no ISO image found"
msgstr ""

#: nova/virt/xenapi/vmops.py:1131
#, python-format
msgid "_migrate_disk_resizing_up failed to rollback: %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:1265
msgid ""
"Reboot failed due to bad volumes, detaching bad volumes and starting "
"halted instance"
msgstr ""

#: nova/virt/xenapi/vmops.py:1343
msgid "Unable to update metadata, VM not found."
msgstr ""

#: nova/virt/xenapi/vmops.py:1495
msgid "VM is not present, skipping destroy..."
msgstr ""

#: nova/virt/xenapi/vmops.py:1616
msgid "VM is not present, skipping soft delete..."
msgstr ""

#: nova/virt/xenapi/volume_utils.py:229
msgid "Cannot purge SR with referenced VDIs"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:246
#, python-format
msgid "Ignoring exception %(exc)s when getting PBDs for %(sr_ref)s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:254
#, python-format
msgid "Ignoring exception %(exc)s when unplugging PBD %(pbd)s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:278
#, python-format
msgid "Mountpoint cannot be translated: %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:145
#, python-format
msgid "Skipping detach because VBD for %s was not found"
msgstr ""

#: nova/virt/xenapi/client/session.py:239
#, python-format
msgid "%(plugin)s.%(fn)s failed. Retrying call."
msgstr ""

#: nova/virt/xenapi/client/session.py:248
#, python-format
msgid ""
"Lost connection to XenAPI during call to %(plugin)s.%(fn)s.  Retrying "
"call."
msgstr ""

#: nova/volume/cinder.py:122
msgid ""
"Cinder V1 API is deprecated as of the Juno release, and Nova is still "
"configured to use it. Enable the V2 API in Cinder and set "
"cinder_catalog_info in nova.conf to use it."
msgstr ""

