# English (United States) translations for nova.
# Copyright (C) 2012 ORGANIZATION
# This file is distributed under the same license as the nova project.
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version:  Nova\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/nova\n"
"POT-Creation-Date: 2015-01-27 06:15+0000\n"
"PO-Revision-Date: 2013-01-21 18:28+0000\n"
"Last-Translator: Jeremy Stanley <fungi@yuggoth.org>\n"
"Language-Team: en_US <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: nova/block_device.py:100
msgid "Some fields are invalid."
msgstr ""

#: nova/block_device.py:110
msgid "Some required fields are missing"
msgstr ""

#: nova/block_device.py:126
msgid "Boot index is invalid."
msgstr ""

#: nova/block_device.py:169
msgid "Unrecognized legacy format."
msgstr ""

#: nova/block_device.py:186
msgid "Invalid source_type field."
msgstr ""

#: nova/block_device.py:189
msgid "Invalid device UUID."
msgstr ""

#: nova/block_device.py:193
msgid "Missing device UUID."
msgstr ""

#: nova/block_device.py:372
msgid "Device name empty or too long."
msgstr ""

#: nova/block_device.py:376
msgid "Device name contains spaces."
msgstr ""

#: nova/block_device.py:389
msgid "Invalid volume_size."
msgstr ""

#: nova/context.py:143
#, python-format
msgid "read_deleted can only be one of 'no', 'yes' or 'only', not %r"
msgstr "read_deleted can only be one of 'no', 'yes' or 'only', not %r"

#: nova/crypto.py:53
msgid "Filename of root CA"
msgstr "Filename of root CA"

#: nova/crypto.py:56
msgid "Filename of private key"
msgstr "Filename of private key"

#: nova/crypto.py:59
msgid "Filename of root Certificate Revocation List"
msgstr "Filename of root Certificate Revocation List"

#: nova/crypto.py:62
msgid "Where we keep our keys"
msgstr "Where we keep our keys"

#: nova/crypto.py:65
msgid "Where we keep our root CA"
msgstr "Where we keep our root CA"

#: nova/crypto.py:68
msgid "Should we use a CA for each project?"
msgstr "Should we use a CA for each project?"

#: nova/crypto.py:72
#, python-format
msgid "Subject for certificate for users, %s for project, user, timestamp"
msgstr "Subject for certificate for users, %s for project, user, timestamp"

#: nova/crypto.py:77
#, python-format
msgid "Subject for certificate for projects, %s for project, timestamp"
msgstr "Subject for certificate for projects, %s for project, timestamp"

#: nova/crypto.py:142
msgid "failed to generate fingerprint"
msgstr ""

#: nova/crypto.py:211
#, fuzzy
msgid "Unable to find the key"
msgstr "Unable to find address %r"

#: nova/exception.py:102
msgid "An unknown exception occurred."
msgstr "An unknown exception occurred."

#: nova/exception.py:143
#, fuzzy, python-format
msgid "Failed to encrypt text: %(reason)s"
msgstr "Failed to decrypt text"

#: nova/exception.py:147
#, fuzzy, python-format
msgid "Failed to decrypt text: %(reason)s"
msgstr "Failed to decrypt text"

#: nova/exception.py:151
#, python-format
msgid "Failed to revoke certificate for %(project_id)s"
msgstr ""

#: nova/exception.py:155
msgid "Virtual Interface creation failed"
msgstr "Virtual Interface creation failed"

#: nova/exception.py:159
msgid "Creation of virtual interface with unique mac address failed"
msgstr ""

#: nova/exception.py:164
msgid "Virtual interface plugin failed"
msgstr ""

#: nova/exception.py:168
#, python-format
msgid "Connection to glance host %(host)s:%(port)s failed: %(reason)s"
msgstr "Connection to glance host %(host)s:%(port)s failed: %(reason)s"

#: nova/exception.py:173
#, python-format
msgid "Connection to cinder host failed: %(reason)s"
msgstr ""

#: nova/exception.py:178
msgid "Not authorized."
msgstr "Not authorized."

#: nova/exception.py:183
msgid "User does not have admin privileges"
msgstr "User does not have admin privileges"

#: nova/exception.py:187
#, python-format
msgid "Policy doesn't allow %(action)s to be performed."
msgstr "Policy doesn't allow %(action)s to be performed."

#: nova/exception.py:194
#, python-format
msgid "Image %(image_id)s is not active."
msgstr "Image %(image_id)s is not active."

#: nova/exception.py:198
#, python-format
msgid "Not authorized for image %(image_id)s."
msgstr "Not authorized for image %(image_id)s."

#: nova/exception.py:202 nova/exception.py:350
msgid "Unacceptable parameters."
msgstr "Unacceptable parameters."

#: nova/exception.py:207
#, fuzzy
msgid "Block Device Mapping is Invalid."
msgstr "block_device_mapping %s"

#: nova/exception.py:211
#, python-format
msgid "Block Device Mapping is Invalid: failed to get snapshot %(id)s."
msgstr ""

#: nova/exception.py:216
#, python-format
msgid "Block Device Mapping is Invalid: failed to get volume %(id)s."
msgstr ""

#: nova/exception.py:221
#, python-format
msgid "Block Device Mapping is Invalid: failed to get image %(id)s."
msgstr ""

#: nova/exception.py:226
msgid ""
"Block Device Mapping is Invalid: Boot sequence for the instance and "
"image/block device mapping combination is not valid."
msgstr ""

#: nova/exception.py:233
msgid ""
"Block Device Mapping is Invalid: You specified more local devices than "
"the limit allows"
msgstr ""

#: nova/exception.py:239
msgid "Ephemeral disks requested are larger than the instance type allows."
msgstr ""

#: nova/exception.py:244
msgid "Swap drive requested is larger than instance type allows."
msgstr ""

#: nova/exception.py:248
#, python-format
msgid "Block Device Mapping is Invalid: %(details)s"
msgstr ""

#: nova/exception.py:253
msgid "Block Device Mapping cannot be converted to legacy format. "
msgstr ""

#: nova/exception.py:258
#, python-format
msgid "Block Device %(id)s is not bootable."
msgstr ""

#: nova/exception.py:262
#, python-format
msgid "Attribute not supported: %(attr)s"
msgstr ""

#: nova/exception.py:271
#, python-format
msgid "Volume %(volume_id)s is not attached to anything"
msgstr "Volume %(volume_id)s is not attached to anything"

#: nova/exception.py:275
#, python-format
msgid ""
"Volume %(volume_id)s did not finish being created even after we waited "
"%(seconds)s seconds or %(attempts)s attempts."
msgstr ""

#: nova/exception.py:282
#, python-format
msgid "Keypair data is invalid: %(reason)s"
msgstr ""

#: nova/exception.py:286
msgid "The request is invalid."
msgstr "The request is invalid."

#: nova/exception.py:290
#, python-format
msgid "Invalid input received: %(reason)s"
msgstr ""

#: nova/exception.py:295
#, python-format
msgid "Invalid volume: %(reason)s"
msgstr ""

#: nova/exception.py:299
#, python-format
msgid "Invalid volume access mode: %(access_mode)s"
msgstr ""

#: nova/exception.py:303
#, python-format
msgid "Invalid metadata: %(reason)s"
msgstr ""

#: nova/exception.py:307
#, python-format
msgid "Invalid metadata size: %(reason)s"
msgstr ""

#: nova/exception.py:312
#, python-format
msgid "Invalid port range %(from_port)s:%(to_port)s. %(msg)s"
msgstr "Invalid port range %(from_port)s:%(to_port)s. %(msg)s"

#: nova/exception.py:316
#, python-format
msgid "Invalid IP protocol %(protocol)s."
msgstr "Invalid IP protocol %(protocol)s."

#: nova/exception.py:320
#, python-format
msgid "Invalid content type %(content_type)s."
msgstr "Invalid content type %(content_type)s."

#: nova/exception.py:324
msgid "Invalid Parameter: Unicode is not supported by the current database."
msgstr "Invalid Parameter: Unicode is not supported by the current database."

#: nova/exception.py:329
#, python-format
msgid ""
"API Version String %(version)s is of invalid format. Must be of format "
"MajorNum.MinorNum."
msgstr ""

#: nova/exception.py:334
#, python-format
msgid "API version %(version)s is not supported on this method."
msgstr ""

#: nova/exception.py:338
#, python-format
msgid ""
"Version %(req_ver)s is not supported by the API. Minimum is %(min_ver)s "
"and maximum is %(max_ver)s."
msgstr ""

#: nova/exception.py:346
#, python-format
msgid "%(err)s"
msgstr "%(err)s"

#: nova/exception.py:355
#, python-format
msgid "Cannot add host to aggregate %(aggregate_id)s. Reason: %(reason)s."
msgstr ""

#: nova/exception.py:360
#, python-format
msgid "Cannot remove host from aggregate %(aggregate_id)s. Reason: %(reason)s."
msgstr ""

#: nova/exception.py:365
#, python-format
msgid "Cannot update aggregate %(aggregate_id)s. Reason: %(reason)s."
msgstr ""

#: nova/exception.py:370
#, python-format
msgid "Cannot update metadata of aggregate %(aggregate_id)s. Reason: %(reason)s."
msgstr ""

#: nova/exception.py:375
#, python-format
msgid "Group not valid. Reason: %(reason)s"
msgstr "Group not valid. Reason: %(reason)s"

#: nova/exception.py:379
msgid "Sort key supplied was not valid."
msgstr "Sort key supplied was not valid."

#: nova/exception.py:383
#, python-format
msgid "Invalid datetime string: %(reason)s"
msgstr ""

#: nova/exception.py:387
#, python-format
msgid ""
"Instance %(instance_uuid)s in %(attr)s %(state)s. Cannot %(method)s while"
" the instance is in this state."
msgstr ""
"Instance %(instance_uuid)s in %(attr)s %(state)s. Cannot %(method)s while"
" the instance is in this state."

#: nova/exception.py:392
#, python-format
msgid "Instance %(instance_id)s is not running."
msgstr "Instance %(instance_id)s is not running."

#: nova/exception.py:396
#, python-format
msgid "Instance %(instance_id)s is not in rescue mode"
msgstr "Instance %(instance_id)s is not in rescue mode"

#: nova/exception.py:400
#, fuzzy, python-format
msgid "Instance %(instance_id)s cannot be rescued: %(reason)s"
msgstr "Instance %(instance_id)s is not in rescue mode"

#: nova/exception.py:404
#, python-format
msgid "Instance %(instance_id)s is not ready"
msgstr "Instance %(instance_id)s is not ready"

#: nova/exception.py:408
#, python-format
msgid "Failed to suspend instance: %(reason)s"
msgstr ""

#: nova/exception.py:412
#, python-format
msgid "Failed to resume instance: %(reason)s"
msgstr ""

#: nova/exception.py:416
#, python-format
msgid "Failed to power on instance: %(reason)s"
msgstr ""

#: nova/exception.py:420
#, python-format
msgid "Failed to power off instance: %(reason)s"
msgstr ""

#: nova/exception.py:424
#, python-format
msgid "Failed to reboot instance: %(reason)s"
msgstr ""

#: nova/exception.py:428
#, python-format
msgid "Failed to terminate instance: %(reason)s"
msgstr ""

#: nova/exception.py:432
#, python-format
msgid "Failed to deploy instance: %(reason)s"
msgstr ""

#: nova/exception.py:436 nova/exception.py:440
#, python-format
msgid "Failed to launch instances: %(reason)s"
msgstr ""

#: nova/exception.py:444
msgid "Service is unavailable at this time."
msgstr "Service is unavailable at this time."

#: nova/exception.py:448
#, python-format
msgid "Insufficient compute resources: %(reason)s."
msgstr ""

#: nova/exception.py:452
#, python-format
msgid "Connection to the hypervisor is broken on host: %(host)s"
msgstr ""

#: nova/exception.py:456
#, fuzzy, python-format
msgid "Compute service of %(host)s is unavailable at this time."
msgstr "Compute service is unavailable at this time."

#: nova/exception.py:460
#, python-format
msgid "Compute service of %(host)s is still in use."
msgstr ""

#: nova/exception.py:464
#, python-format
msgid "Unable to migrate instance (%(instance_id)s) to current host (%(host)s)."
msgstr "Unable to migrate instance (%(instance_id)s) to current host (%(host)s)."

#: nova/exception.py:469
msgid "The supplied hypervisor type of is invalid."
msgstr "The supplied hypervisor type of is invalid."

#: nova/exception.py:473
msgid "The instance requires a newer hypervisor version than has been provided."
msgstr "The instance requires a newer hypervisor version than has been provided."

#: nova/exception.py:478
#, python-format
msgid ""
"The supplied disk path (%(path)s) already exists, it is expected not to "
"exist."
msgstr ""
"The supplied disk path (%(path)s) already exists, it is expected not to "
"exist."

#: nova/exception.py:483
#, python-format
msgid "The supplied device path (%(path)s) is invalid."
msgstr "The supplied device path (%(path)s) is invalid."

#: nova/exception.py:487
#, python-format
msgid "The supplied device path (%(path)s) is in use."
msgstr "The supplied device path (%(path)s) is in use."

#: nova/exception.py:492
#, python-format
msgid "The supplied device (%(device)s) is busy."
msgstr "The supplied device (%(device)s) is busy."

#: nova/exception.py:496
#, python-format
msgid "Unacceptable CPU info: %(reason)s"
msgstr ""

#: nova/exception.py:500
#, python-format
msgid "%(address)s is not a valid IP v4/6 address."
msgstr "%(address)s is not a valid IP v4/6 address."

#: nova/exception.py:504
#, python-format
msgid ""
"VLAN tag is not appropriate for the port group %(bridge)s. Expected VLAN "
"tag is %(tag)s, but the one associated with the port group is %(pgroup)s."
msgstr ""
"VLAN tag is not appropriate for the port group %(bridge)s. Expected VLAN "
"tag is %(tag)s, but the one associated with the port group is %(pgroup)s."

#: nova/exception.py:510
#, python-format
msgid ""
"vSwitch which contains the port group %(bridge)s is not associated with "
"the desired physical adapter. Expected vSwitch is %(expected)s, but the "
"one associated is %(actual)s."
msgstr ""
"vSwitch which contains the port group %(bridge)s is not associated with "
"the desired physical adapter. Expected vSwitch is %(expected)s, but the "
"one associated is %(actual)s."

#: nova/exception.py:517
#, python-format
msgid "Disk format %(disk_format)s is not acceptable"
msgstr "Disk format %(disk_format)s is not acceptable"

#: nova/exception.py:521
#, python-format
msgid "Disk info file is invalid: %(reason)s"
msgstr ""

#: nova/exception.py:525
#, python-format
msgid "Failed to read or write disk info file: %(reason)s"
msgstr ""

#: nova/exception.py:529
#, python-format
msgid "Image %(image_id)s is unacceptable: %(reason)s"
msgstr "Image %(image_id)s is unacceptable: %(reason)s"

#: nova/exception.py:533
#, python-format
msgid "Instance %(instance_id)s is unacceptable: %(reason)s"
msgstr "Instance %(instance_id)s is unacceptable: %(reason)s"

#: nova/exception.py:537
#, python-format
msgid "Ec2 id %(ec2_id)s is unacceptable."
msgstr "Ec2 id %(ec2_id)s is unacceptable."

#: nova/exception.py:541
#, python-format
msgid "Expected a uuid but received %(uuid)s."
msgstr "Expected a uuid but received %(uuid)s."

#: nova/exception.py:545
#, fuzzy, python-format
msgid "Invalid ID received %(id)s."
msgstr "Invalid cidr %(cidr)s."

#: nova/exception.py:549
msgid "Constraint not met."
msgstr "Constraint not met."

#: nova/exception.py:554
msgid "Resource could not be found."
msgstr "Resource could not be found."

#: nova/exception.py:559
#, fuzzy, python-format
msgid "No agent-build associated with id %(id)s."
msgstr "No fixed IP associated with id %(id)s."

#: nova/exception.py:563
#, python-format
msgid ""
"Agent-build with hypervisor %(hypervisor)s os %(os)s architecture "
"%(architecture)s exists."
msgstr ""

#: nova/exception.py:569
#, python-format
msgid "Volume %(volume_id)s could not be found."
msgstr "Volume %(volume_id)s could not be found."

#: nova/exception.py:573
#, python-format
msgid "No volume Block Device Mapping with id %(volume_id)s."
msgstr ""

#: nova/exception.py:577
#, python-format
msgid "No volume Block Device Mapping at path: %(path)s"
msgstr ""

#: nova/exception.py:582
#, python-format
msgid "Snapshot %(snapshot_id)s could not be found."
msgstr "Snapshot %(snapshot_id)s could not be found."

#: nova/exception.py:586
#, python-format
msgid "No disk at %(location)s"
msgstr "No disk at %(location)s"

#: nova/exception.py:590
#, python-format
msgid "Could not find a handler for %(driver_type)s volume."
msgstr "Could not find a handler for %(driver_type)s volume."

#: nova/exception.py:594
#, python-format
msgid "Invalid image href %(image_href)s."
msgstr "Invalid image href %(image_href)s."

#: nova/exception.py:598
#, python-format
msgid "Requested image %(image)s has automatic disk resize disabled."
msgstr ""

#: nova/exception.py:603
#, python-format
msgid "Image %(image_id)s could not be found."
msgstr "Image %(image_id)s could not be found."

#: nova/exception.py:607
msgid "The current driver does not support preserving ephemeral partitions."
msgstr ""

#: nova/exception.py:613
#, python-format
msgid ""
"Image %(image_id)s could not be found. The nova EC2 API assigns image ids"
" dynamically when they are listed for the first time. Have you listed "
"image ids since adding this image?"
msgstr ""
"Image %(image_id)s could not be found. The nova EC2 API assigns image ids"
" dynamically when they are listed for the first time. Have you listed "
"image ids since adding this image?"

#: nova/exception.py:620
#, python-format
msgid "Project %(project_id)s could not be found."
msgstr "Project %(project_id)s could not be found."

#: nova/exception.py:624
msgid "Cannot find SR to read/write VDI."
msgstr "Cannot find SR to read/write VDI."

#: nova/exception.py:628
#, fuzzy, python-format
msgid "Network %(network_id)s is duplicated."
msgstr "Network %(network_id)s is still in use."

#: nova/exception.py:632
#, python-format
msgid "Failed to release IP %(address)s with MAC %(mac_address)s"
msgstr ""

#: nova/exception.py:636
#, python-format
msgid "Network %(network_id)s is still in use."
msgstr "Network %(network_id)s is still in use."

#: nova/exception.py:640
#, python-format
msgid "%(req)s is required to create a network."
msgstr "%(req)s is required to create a network."

#: nova/exception.py:644
msgid "Maximum allowed length for 'label' is 255."
msgstr "Maximum allowed length for 'label' is 255."

#: nova/exception.py:648
#, python-format
msgid "%(key)s must be an integer."
msgstr ""

#: nova/exception.py:652
#, python-format
msgid "%(cidr)s is not a valid ip network."
msgstr ""

#: nova/exception.py:656
#, python-format
msgid "%(address)s is not a valid ip address."
msgstr ""

#: nova/exception.py:660
#, python-format
msgid "%(address)s is not within %(cidr)s."
msgstr ""

#: nova/exception.py:664
#, python-format
msgid "Detected existing vlan with id %(vlan)d"
msgstr "Detected existing vlan with id %(vlan)d"

#: nova/exception.py:669
#, python-format
msgid "Requested cidr (%(cidr)s) conflicts with existing cidr (%(other)s)"
msgstr ""

#: nova/exception.py:675
#, python-format
msgid ""
"Network must be disassociated from project %(project_id)s before it can "
"be deleted."
msgstr ""

#: nova/exception.py:680
#, python-format
msgid "Network %(network_id)s could not be found."
msgstr "Network %(network_id)s could not be found."

#: nova/exception.py:684
#, fuzzy, python-format
msgid "Port id %(port_id)s could not be found."
msgstr "Port %(port_id)s could not be found."

#: nova/exception.py:688
#, python-format
msgid "Network could not be found for bridge %(bridge)s"
msgstr "Network could not be found for bridge %(bridge)s"

#: nova/exception.py:692
#, python-format
msgid "Network could not be found for uuid %(uuid)s"
msgstr "Network could not be found for uuid %(uuid)s"

#: nova/exception.py:696
#, python-format
msgid "Network could not be found with cidr %(cidr)s."
msgstr "Network could not be found with cidr %(cidr)s."

#: nova/exception.py:700
#, python-format
msgid "Network could not be found for instance %(instance_id)s."
msgstr "Network could not be found for instance %(instance_id)s."

#: nova/exception.py:704
msgid "No networks defined."
msgstr "No networks defined."

#: nova/exception.py:708
msgid "No more available networks."
msgstr ""

#: nova/exception.py:712
#, python-format
msgid ""
"Either network uuid %(network_uuid)s is not present or is not assigned to"
" the project %(project_id)s."
msgstr ""

#: nova/exception.py:717
msgid ""
"More than one possible network found. Specify network ID(s) to select "
"which one(s) to connect to."
msgstr ""

#: nova/exception.py:722
#, python-format
msgid "Network %(network_uuid)s requires a subnet in order to boot instances on."
msgstr ""

#: nova/exception.py:727
#, python-format
msgid ""
"It is not allowed to create an interface on external network "
"%(network_uuid)s"
msgstr ""

#: nova/exception.py:732
#, python-format
msgid "Physical network is missing for network %(network_uuid)s"
msgstr ""

#: nova/exception.py:736
msgid "Could not find the datastore reference(s) which the VM uses."
msgstr "Could not find the datastore reference(s) which the VM uses."

#: nova/exception.py:740
#, python-format
msgid "Port %(port_id)s is still in use."
msgstr "Port %(port_id)s is still in use."

#: nova/exception.py:744
#, python-format
msgid "Port %(port_id)s requires a FixedIP in order to be used."
msgstr ""

#: nova/exception.py:748
#, fuzzy, python-format
msgid "Port %(port_id)s not usable for instance %(instance)s."
msgstr "Network could not be found for instance %(instance_id)s."

#: nova/exception.py:752
#, fuzzy, python-format
msgid "No free port available for instance %(instance)s."
msgstr "Network could not be found for instance %(instance_id)s."

#: nova/exception.py:756
#, python-format
msgid "Fixed ip %(address)s already exists."
msgstr ""

#: nova/exception.py:760
#, python-format
msgid "No fixed IP associated with id %(id)s."
msgstr "No fixed IP associated with id %(id)s."

#: nova/exception.py:764
#, python-format
msgid "Fixed ip not found for address %(address)s."
msgstr "Fixed ip not found for address %(address)s."

#: nova/exception.py:768
#, python-format
msgid "Instance %(instance_uuid)s has zero fixed ips."
msgstr "Instance %(instance_uuid)s has zero fixed ips."

#: nova/exception.py:772
#, python-format
msgid "Network host %(host)s has zero fixed ips in network %(network_id)s."
msgstr "Network host %(host)s has zero fixed ips in network %(network_id)s."

#: nova/exception.py:777
#, python-format
msgid "Instance %(instance_uuid)s doesn't have fixed ip '%(ip)s'."
msgstr "Instance %(instance_uuid)s doesn't have fixed ip '%(ip)s'."

#: nova/exception.py:781
#, python-format
msgid ""
"Fixed IP address (%(address)s) does not exist in network "
"(%(network_uuid)s)."
msgstr ""
"Fixed IP address (%(address)s) does not exist in network "
"(%(network_uuid)s)."

#: nova/exception.py:786
#, python-format
msgid ""
"Fixed IP address %(address)s is already in use on instance "
"%(instance_uuid)s."
msgstr ""
"Fixed IP address %(address)s is already in use on instance "
"%(instance_uuid)s."

#: nova/exception.py:791
#, python-format
msgid "More than one instance is associated with fixed ip address '%(address)s'."
msgstr "More than one instance is associated with fixed ip address '%(address)s'."

#: nova/exception.py:796
#, python-format
msgid "Fixed IP address %(address)s is invalid."
msgstr "Fixed IP address %(address)s is invalid."

#: nova/exception.py:801
#, python-format
msgid "No fixed IP addresses available for network: %(net)s"
msgstr ""

#: nova/exception.py:805
msgid "Zero fixed ips could be found."
msgstr "Zero fixed ips could be found."

#: nova/exception.py:809
#, python-format
msgid "Floating ip %(address)s already exists."
msgstr "Floating ip %(address)s already exists."

#: nova/exception.py:814
#, python-format
msgid "Floating ip not found for id %(id)s."
msgstr "Floating ip not found for id %(id)s."

#: nova/exception.py:818
#, python-format
msgid "The DNS entry %(name)s already exists in domain %(domain)s."
msgstr "The DNS entry %(name)s already exists in domain %(domain)s."

#: nova/exception.py:822
#, python-format
msgid "Floating ip not found for address %(address)s."
msgstr "Floating ip not found for address %(address)s."

#: nova/exception.py:826
#, python-format
msgid "Floating ip not found for host %(host)s."
msgstr "Floating ip not found for host %(host)s."

#: nova/exception.py:830
#, python-format
msgid "Multiple floating ips are found for address %(address)s."
msgstr "Multiple floating ips are found for address %(address)s."

#: nova/exception.py:834
msgid "Floating ip pool not found."
msgstr "Floating ip pool not found."

#: nova/exception.py:839
msgid "Zero floating ips available."
msgstr "Zero floating ips available."

#: nova/exception.py:845
#, python-format
msgid "Floating ip %(address)s is associated."
msgstr "Floating ip %(address)s is associated."

#: nova/exception.py:849
#, python-format
msgid "Floating ip %(address)s is not associated."
msgstr "Floating ip %(address)s is not associated."

#: nova/exception.py:853
msgid "Zero floating ips exist."
msgstr "Zero floating ips exist."

#: nova/exception.py:858
#, python-format
msgid "Interface %(interface)s not found."
msgstr "Interface %(interface)s not found."

#: nova/exception.py:863 nova/api/openstack/compute/contrib/floating_ips.py:73
#: nova/api/openstack/compute/contrib/floating_ips.py:154
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:81
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:172
msgid "Cannot disassociate auto assigned floating ip"
msgstr "Cannot disassociate auto assigned floating ip"

#: nova/exception.py:868
#, python-format
msgid "Keypair %(name)s not found for user %(user_id)s"
msgstr "Keypair %(name)s not found for user %(user_id)s"

#: nova/exception.py:872
#, python-format
msgid "Service %(service_id)s could not be found."
msgstr "Service %(service_id)s could not be found."

#: nova/exception.py:876
#, python-format
msgid "Service with host %(host)s binary %(binary)s exists."
msgstr ""

#: nova/exception.py:880
#, python-format
msgid "Service with host %(host)s topic %(topic)s exists."
msgstr ""

#: nova/exception.py:884
#, python-format
msgid "Host %(host)s could not be found."
msgstr "Host %(host)s could not be found."

#: nova/exception.py:888
#, python-format
msgid "Compute host %(host)s could not be found."
msgstr "Compute host %(host)s could not be found."

#: nova/exception.py:892
#, python-format
msgid "Compute host %(name)s needs to be created first before updating."
msgstr ""

#: nova/exception.py:897
#, python-format
msgid "Could not find binary %(binary)s on host %(host)s."
msgstr "Could not find binary %(binary)s on host %(host)s."

#: nova/exception.py:901
#, python-format
msgid "Invalid reservation expiration %(expire)s."
msgstr "Invalid reservation expiration %(expire)s."

#: nova/exception.py:905
#, python-format
msgid ""
"Change would make usage less than 0 for the following resources: "
"%(unders)s"
msgstr ""
"Change would make usage less than 0 for the following resources: "
"%(unders)s"

#: nova/exception.py:910
#, python-format
msgid "Wrong quota method %(method)s used on resource %(res)s"
msgstr ""

#: nova/exception.py:914
msgid "Quota could not be found"
msgstr "Quota could not be found"

#: nova/exception.py:918
#, python-format
msgid "Quota exists for project %(project_id)s, resource %(resource)s"
msgstr ""

#: nova/exception.py:923
#, python-format
msgid "Unknown quota resources %(unknown)s."
msgstr "Unknown quota resources %(unknown)s."

#: nova/exception.py:927
#, python-format
msgid "Quota for user %(user_id)s in project %(project_id)s could not be found."
msgstr ""

#: nova/exception.py:932
#, python-format
msgid "Quota for project %(project_id)s could not be found."
msgstr "Quota for project %(project_id)s could not be found."

#: nova/exception.py:936
#, python-format
msgid "Quota class %(class_name)s could not be found."
msgstr "Quota class %(class_name)s could not be found."

#: nova/exception.py:940
#, python-format
msgid "Quota usage for project %(project_id)s could not be found."
msgstr "Quota usage for project %(project_id)s could not be found."

#: nova/exception.py:944
#, python-format
msgid "Quota reservation %(uuid)s could not be found."
msgstr "Quota reservation %(uuid)s could not be found."

#: nova/exception.py:948
#, python-format
msgid "Quota exceeded for resources: %(overs)s"
msgstr "Quota exceeded for resources: %(overs)s"

#: nova/exception.py:952
#, python-format
msgid "Security group %(security_group_id)s not found."
msgstr "Security group %(security_group_id)s not found."

#: nova/exception.py:956
#, python-format
msgid "Security group %(security_group_id)s not found for project %(project_id)s."
msgstr "Security group %(security_group_id)s not found for project %(project_id)s."

#: nova/exception.py:961
#, python-format
msgid "Security group with rule %(rule_id)s not found."
msgstr "Security group with rule %(rule_id)s not found."

#: nova/exception.py:966
#, python-format
msgid ""
"Security group %(security_group_name)s already exists for project "
"%(project_id)s."
msgstr ""

#: nova/exception.py:971
#, python-format
msgid ""
"Security group %(security_group_id)s is already associated with the "
"instance %(instance_id)s"
msgstr ""
"Security group %(security_group_id)s is already associated with the "
"instance %(instance_id)s"

#: nova/exception.py:976
#, python-format
msgid ""
"Security group %(security_group_id)s is not associated with the instance "
"%(instance_id)s"
msgstr ""
"Security group %(security_group_id)s is not associated with the instance "
"%(instance_id)s"

#: nova/exception.py:981
#, fuzzy, python-format
msgid "Security group default rule (%rule_id)s not found."
msgstr "Security group with rule %(rule_id)s not found."

#: nova/exception.py:985
msgid ""
"Network requires port_security_enabled and subnet associated in order to "
"apply security groups."
msgstr ""

#: nova/exception.py:991
#, python-format
msgid "Rule already exists in group: %(rule)s"
msgstr ""

#: nova/exception.py:995
msgid "No Unique Match Found."
msgstr ""

#: nova/exception.py:1000
#, python-format
msgid "Migration %(migration_id)s could not be found."
msgstr "Migration %(migration_id)s could not be found."

#: nova/exception.py:1004
#, python-format
msgid "Migration not found for instance %(instance_id)s with status %(status)s."
msgstr "Migration not found for instance %(instance_id)s with status %(status)s."

#: nova/exception.py:1009
#, python-format
msgid "Console pool %(pool_id)s could not be found."
msgstr "Console pool %(pool_id)s could not be found."

#: nova/exception.py:1013
#, python-format
msgid ""
"Console pool with host %(host)s, console_type %(console_type)s and "
"compute_host %(compute_host)s already exists."
msgstr ""

#: nova/exception.py:1019
#, python-format
msgid ""
"Console pool of type %(console_type)s for compute host %(compute_host)s "
"on proxy host %(host)s not found."
msgstr ""
"Console pool of type %(console_type)s for compute host %(compute_host)s "
"on proxy host %(host)s not found."

#: nova/exception.py:1025
#, python-format
msgid "Console %(console_id)s could not be found."
msgstr "Console %(console_id)s could not be found."

#: nova/exception.py:1029
#, python-format
msgid "Console for instance %(instance_uuid)s could not be found."
msgstr "Console for instance %(instance_uuid)s could not be found."

#: nova/exception.py:1033
#, python-format
msgid ""
"Console for instance %(instance_uuid)s in pool %(pool_id)s could not be "
"found."
msgstr ""
"Console for instance %(instance_uuid)s in pool %(pool_id)s could not be "
"found."

#: nova/exception.py:1038
#, fuzzy, python-format
msgid "Invalid console type %(console_type)s"
msgstr "Invalid console type %(console_type)s "

#: nova/exception.py:1042
#, python-format
msgid "Unavailable console type %(console_type)s."
msgstr ""

#: nova/exception.py:1046
#, python-format
msgid "The console port range %(min_port)d-%(max_port)d is exhausted."
msgstr ""

#: nova/exception.py:1051
#, python-format
msgid "Flavor %(flavor_id)s could not be found."
msgstr "Flavor %(flavor_id)s could not be found."

#: nova/exception.py:1055
#, python-format
msgid "Flavor with name %(flavor_name)s could not be found."
msgstr ""

#: nova/exception.py:1059
#, fuzzy, python-format
msgid "Flavor access not found for %(flavor_id)s / %(project_id)s combination."
msgstr "Flavor access not found for %(flavor_id) / %(project_id) combination."

#: nova/exception.py:1064
#, python-format
msgid ""
"Flavor %(id)d extra spec cannot be updated or created after %(retries)d "
"retries."
msgstr ""

#: nova/exception.py:1069
#, fuzzy, python-format
msgid "Cell %(cell_name)s doesn't exist."
msgstr "pool %s doesn't exist"

#: nova/exception.py:1073
#, python-format
msgid "Cell with name %(name)s already exists."
msgstr ""

#: nova/exception.py:1077
#, python-format
msgid "Inconsistency in cell routing: %(reason)s"
msgstr ""

#: nova/exception.py:1081
#, python-format
msgid "Service API method not found: %(detail)s"
msgstr ""

#: nova/exception.py:1085
#, fuzzy
msgid "Timeout waiting for response from cell"
msgstr "Timed out waiting for RPC response: %s"

#: nova/exception.py:1089
#, python-format
msgid "Cell message has reached maximum hop count: %(hop_count)s"
msgstr ""

#: nova/exception.py:1093
msgid "No cells available matching scheduling criteria."
msgstr ""

#: nova/exception.py:1097
msgid "Cannot update cells configuration file."
msgstr ""

#: nova/exception.py:1101
#, fuzzy, python-format
msgid "Cell is not known for instance %(instance_uuid)s"
msgstr "Destroying VDIs for Instance %(instance_uuid)s"

#: nova/exception.py:1105
#, python-format
msgid "Scheduler Host Filter %(filter_name)s could not be found."
msgstr "Scheduler Host Filter %(filter_name)s could not be found."

#: nova/exception.py:1109
#, python-format
msgid "Flavor %(flavor_id)s has no extra specs with key %(extra_specs_key)s."
msgstr ""

#: nova/exception.py:1114
#, python-format
msgid ""
"Metric %(name)s could not be found on the compute host node "
"%(host)s.%(node)s."
msgstr ""

#: nova/exception.py:1119
#, python-format
msgid "File %(file_path)s could not be found."
msgstr "File %(file_path)s could not be found."

#: nova/exception.py:1123
#, python-format
msgid "Virtual switch associated with the network adapter %(adapter)s not found."
msgstr "Virtual switch associated with the network adapter %(adapter)s not found."

#: nova/exception.py:1128
#, python-format
msgid "Network adapter %(adapter)s could not be found."
msgstr "Network adapter %(adapter)s could not be found."

#: nova/exception.py:1132
#, python-format
msgid "Class %(class_name)s could not be found: %(exception)s"
msgstr "Class %(class_name)s could not be found: %(exception)s"

#: nova/exception.py:1136
msgid "Action not allowed."
msgstr "Action not allowed."

#: nova/exception.py:1140
#, python-format
msgid "Instance %(instance_id)s has no tag '%(tag)s'"
msgstr ""

#: nova/exception.py:1144
msgid "Rotation is not allowed for snapshots"
msgstr "Rotation is not allowed for snapshots"

#: nova/exception.py:1148
msgid "Rotation param is required for backup image_type"
msgstr "Rotation param is required for backup image_type"

#: nova/exception.py:1153
#, fuzzy, python-format
msgid "Key pair '%(key_name)s' already exists."
msgstr "Key pair %(key_name)s already exists."

#: nova/exception.py:1157
#, python-format
msgid "Instance %(name)s already exists."
msgstr "Instance %(name)s already exists."

#: nova/exception.py:1161
#, python-format
msgid "Flavor with name %(name)s already exists."
msgstr ""

#: nova/exception.py:1165
#, python-format
msgid "Flavor with ID %(flavor_id)s already exists."
msgstr ""

#: nova/exception.py:1169
#, python-format
msgid ""
"Flavor access already exists for flavor %(flavor_id)s and project "
"%(project_id)s combination."
msgstr ""

#: nova/exception.py:1174
#, python-format
msgid "%(path)s is not on shared storage: %(reason)s"
msgstr "%(path)s is not on shared storage: %(reason)s"

#: nova/exception.py:1178
#, python-format
msgid "%(path)s is not on local storage: %(reason)s"
msgstr "%(path)s is not on local storage: %(reason)s"

#: nova/exception.py:1182
#, python-format
msgid "Storage error: %(reason)s"
msgstr ""

#: nova/exception.py:1186
#, python-format
msgid "Migration error: %(reason)s"
msgstr ""

#: nova/exception.py:1190
#, python-format
msgid "Migration pre-check error: %(reason)s"
msgstr ""

#: nova/exception.py:1194
#, python-format
msgid "Malformed message body: %(reason)s"
msgstr "Malformed message body: %(reason)s"

#: nova/exception.py:1200
#, python-format
msgid "Could not find config at %(path)s"
msgstr "Could not find config at %(path)s"

#: nova/exception.py:1204
#, python-format
msgid "Could not load paste app '%(name)s' from %(path)s"
msgstr "Could not load paste app '%(name)s' from %(path)s"

#: nova/exception.py:1208
msgid "When resizing, instances must change flavor!"
msgstr "When resizing, instances must change flavor!"

#: nova/exception.py:1212
#, python-format
msgid "Resize error: %(reason)s"
msgstr ""

#: nova/exception.py:1216
#, python-format
msgid "Server disk was unable to be resized because: %(reason)s"
msgstr ""

#: nova/exception.py:1220
msgid "Flavor's memory is too small for requested image."
msgstr ""

#: nova/exception.py:1224
msgid "Flavor's disk is too small for requested image."
msgstr ""

#: nova/exception.py:1228
#, python-format
msgid "Insufficient free memory on compute node to start %(uuid)s."
msgstr "Insufficient free memory on compute node to start %(uuid)s."

#: nova/exception.py:1232
#, python-format
msgid "No valid host was found. %(reason)s"
msgstr "No valid host was found. %(reason)s"

#: nova/exception.py:1237
#, python-format
msgid "Quota exceeded: code=%(code)s"
msgstr ""

#: nova/exception.py:1247
#, python-format
msgid ""
"Quota exceeded for %(overs)s: Requested %(req)s, but already used "
"%(used)d of %(allowed)d %(resource)s"
msgstr ""
"Quota exceeded for %(overs)s: Requested %(req)s, but already used "
"%(used)d of %(allowed)d %(resource)s"

#: nova/exception.py:1252
msgid "Maximum number of floating ips exceeded"
msgstr "Maximum number of floating ips exceeded"

#: nova/exception.py:1256
#, fuzzy
msgid "Maximum number of fixed ips exceeded"
msgstr "Maximum number of floating ips exceeded"

#: nova/exception.py:1260
#, python-format
msgid "Maximum number of metadata items exceeds %(allowed)d"
msgstr "Maximum number of metadata items exceeds %(allowed)d"

#: nova/exception.py:1264
msgid "Personality file limit exceeded"
msgstr "Personality file limit exceeded"

#: nova/exception.py:1268
msgid "Personality file path too long"
msgstr "Personality file path too long"

#: nova/exception.py:1272
msgid "Personality file content too long"
msgstr "Personality file content too long"

#: nova/exception.py:1276
msgid "Maximum number of key pairs exceeded"
msgstr "Maximum number of key pairs exceeded"

#: nova/exception.py:1281
msgid "Maximum number of security groups or rules exceeded"
msgstr "Maximum number of security groups or rules exceeded"

#: nova/exception.py:1285
msgid "Maximum number of ports exceeded"
msgstr ""

#: nova/exception.py:1289
#, python-format
msgid ""
"Aggregate %(aggregate_id)s: action '%(action)s' caused an error: "
"%(reason)s."
msgstr ""
"Aggregate %(aggregate_id)s: action '%(action)s' caused an error: "
"%(reason)s."

#: nova/exception.py:1294
#, python-format
msgid "Aggregate %(aggregate_id)s could not be found."
msgstr "Aggregate %(aggregate_id)s could not be found."

#: nova/exception.py:1298
#, python-format
msgid "Aggregate %(aggregate_name)s already exists."
msgstr "Aggregate %(aggregate_name)s already exists."

#: nova/exception.py:1302
#, python-format
msgid "Aggregate %(aggregate_id)s has no host %(host)s."
msgstr "Aggregate %(aggregate_id)s has no host %(host)s."

#: nova/exception.py:1306
#, python-format
msgid "Aggregate %(aggregate_id)s has no metadata with key %(metadata_key)s."
msgstr "Aggregate %(aggregate_id)s has no metadata with key %(metadata_key)s."

#: nova/exception.py:1311
#, python-format
msgid "Aggregate %(aggregate_id)s already has host %(host)s."
msgstr "Aggregate %(aggregate_id)s already has host %(host)s."

#: nova/exception.py:1315
msgid "Unable to create flavor"
msgstr ""

#: nova/exception.py:1319
#, python-format
msgid "Failed to set admin password on %(instance)s because %(reason)s"
msgstr "Failed to set admin password on %(instance)s because %(reason)s"

#: nova/exception.py:1326
#, python-format
msgid "Instance %(instance_id)s could not be found."
msgstr "Instance %(instance_id)s could not be found."

#: nova/exception.py:1330
#, fuzzy, python-format
msgid "Info cache for instance %(instance_uuid)s could not be found."
msgstr "Console for instance %(instance_uuid)s could not be found."

#: nova/exception.py:1336
msgid "Invalid association."
msgstr ""

#: nova/exception.py:1340
#, fuzzy, python-format
msgid "Node %(node_id)s could not be found."
msgstr "Volume %(volume_id)s could not be found."

#: nova/exception.py:1344
#, fuzzy, python-format
msgid "Node with UUID %(node_uuid)s could not be found."
msgstr "Port %(port_id)s could not be found."

#: nova/exception.py:1348
#, python-format
msgid "Marker %(marker)s could not be found."
msgstr "Marker %(marker)s could not be found."

#: nova/exception.py:1352
#, python-format
msgid "Invalid id: %(instance_id)s (expecting \"i-...\")"
msgstr ""

#: nova/exception.py:1357
#, python-format
msgid "Invalid id: %(volume_id)s (expecting \"i-...\")"
msgstr ""

#: nova/exception.py:1362
#, python-format
msgid "Could not fetch image %(image_id)s"
msgstr "Could not fetch image %(image_id)s"

#: nova/exception.py:1366
#, fuzzy, python-format
msgid "Could not upload image %(image_id)s"
msgstr "Could not fetch image %(image_id)s"

#: nova/exception.py:1370
#, python-format
msgid "Task %(task_name)s is already running on host %(host)s"
msgstr "Task %(task_name)s is already running on host %(host)s"

#: nova/exception.py:1374
#, python-format
msgid "Task %(task_name)s is not running on host %(host)s"
msgstr "Task %(task_name)s is not running on host %(host)s"

#: nova/exception.py:1378
#, python-format
msgid "Instance %(instance_uuid)s is locked"
msgstr "Instance %(instance_uuid)s is locked"

#: nova/exception.py:1382
#, python-format
msgid "Invalid value for Config Drive option: %(option)s"
msgstr ""

#: nova/exception.py:1386
#, python-format
msgid "Could not mount vfat config drive. %(operation)s failed. Error: %(error)s"
msgstr "Could not mount vfat config drive. %(operation)s failed. Error: %(error)s"

#: nova/exception.py:1391
#, python-format
msgid "Unknown config drive format %(format)s. Select one of iso9660 or vfat."
msgstr "Unknown config drive format %(format)s. Select one of iso9660 or vfat."

#: nova/exception.py:1396
#, python-format
msgid "Failed to attach network adapter device to %(instance_uuid)s"
msgstr ""

#: nova/exception.py:1401
#, python-format
msgid "Failed to detach network adapter device from %(instance_uuid)s"
msgstr ""

#: nova/exception.py:1406
#, python-format
msgid ""
"User data too large. User data must be no larger than %(maxsize)s bytes "
"once base64 encoded. Your data is %(length)d bytes"
msgstr ""
"User data too large. User data must be no larger than %(maxsize)s bytes "
"once base64 encoded. Your data is %(length)d bytes"

#: nova/exception.py:1412
msgid "User data needs to be valid base 64."
msgstr "User data needs to be valid base 64."

#: nova/exception.py:1416
#, python-format
msgid ""
"Unexpected task state: expecting %(expected)s but the actual state is "
"%(actual)s"
msgstr ""

#: nova/exception.py:1425
#, fuzzy, python-format
msgid ""
"Action for request_id %(request_id)s on instance %(instance_uuid)s not "
"found"
msgstr "Attach volume %(volume_id)s to instance %(instance_id)s at %(device)s"

#: nova/exception.py:1430
#, fuzzy, python-format
msgid "Event %(event)s not found for action id %(action_id)s"
msgstr "Keypair %(name)s not found for user %(user_id)s"

#: nova/exception.py:1434
#, python-format
msgid ""
"Unexpected VM state: expecting %(expected)s but the actual state is "
"%(actual)s"
msgstr ""

#: nova/exception.py:1439
#, python-format
msgid "The CA file for %(project)s could not be found"
msgstr "The CA file for %(project)s could not be found"

#: nova/exception.py:1443
#, python-format
msgid "The CRL file for %(project)s could not be found"
msgstr "The CRL file for %(project)s could not be found"

#: nova/exception.py:1447
msgid "Instance recreate is not supported."
msgstr ""

#: nova/exception.py:1451
#, python-format
msgid ""
"The service from servicegroup driver %(driver)s is temporarily "
"unavailable."
msgstr ""

#: nova/exception.py:1456
#, python-format
msgid "%(binary)s attempted direct database access which is not allowed by policy"
msgstr ""

#: nova/exception.py:1461
#, python-format
msgid "Virtualization type '%(virt)s' is not supported by this compute driver"
msgstr ""

#: nova/exception.py:1466
#, python-format
msgid ""
"Requested hardware '%(model)s' is not supported by the '%(virt)s' virt "
"driver"
msgstr ""

#: nova/exception.py:1471
#, python-format
msgid "Invalid Base 64 data for file %(path)s"
msgstr ""

#: nova/exception.py:1475
#, fuzzy, python-format
msgid "Build of instance %(instance_uuid)s aborted: %(reason)s"
msgstr "Instance %(instance_id)s is not in rescue mode"

#: nova/exception.py:1479
#, fuzzy, python-format
msgid "Build of instance %(instance_uuid)s was re-scheduled: %(reason)s"
msgstr "Instance %(instance_id)s is not in rescue mode"

#: nova/exception.py:1484
#, fuzzy, python-format
msgid "Shadow table with name %(name)s already exists."
msgstr "Instance Type with name %(name)s already exists."

#: nova/exception.py:1489
#, python-format
msgid "Instance rollback performed due to: %s"
msgstr ""

#: nova/exception.py:1495
#, fuzzy, python-format
msgid "Unsupported object type %(objtype)s"
msgstr "Expected object of type: %s"

#: nova/exception.py:1499
#, python-format
msgid "Cannot call %(method)s on orphaned %(objtype)s object"
msgstr ""

#: nova/exception.py:1503
#, python-format
msgid "Version %(objver)s of %(objname)s is not supported"
msgstr ""

#: nova/exception.py:1507
#, python-format
msgid "Cannot modify readonly field %(field)s"
msgstr ""

#: nova/exception.py:1511
#, python-format
msgid "Object action %(action)s failed because: %(reason)s"
msgstr ""

#: nova/exception.py:1515
#, python-format
msgid "Field %(field)s of %(objname)s is not an instance of Field"
msgstr ""

#: nova/exception.py:1519
#, python-format
msgid "Core API extensions are missing: %(missing_apis)s"
msgstr ""

#: nova/exception.py:1523
#, python-format
msgid "Error during following call to agent: %(method)s"
msgstr ""

#: nova/exception.py:1527
#, python-format
msgid "Unable to contact guest agent. The following call timed out: %(method)s"
msgstr ""

#: nova/exception.py:1532
#, python-format
msgid "Agent does not support the call: %(method)s"
msgstr ""

#: nova/exception.py:1536
#, python-format
msgid "Instance group %(group_uuid)s could not be found."
msgstr ""

#: nova/exception.py:1540
#, python-format
msgid "Instance group %(group_uuid)s already exists."
msgstr ""

#: nova/exception.py:1544
#, python-format
msgid "Instance group %(group_uuid)s has no metadata with key %(metadata_key)s."
msgstr ""

#: nova/exception.py:1549
#, python-format
msgid "Instance group %(group_uuid)s has no member with id %(instance_id)s."
msgstr ""

#: nova/exception.py:1554
#, python-format
msgid "Instance group %(group_uuid)s has no policy %(policy)s."
msgstr ""

#: nova/exception.py:1558
#, python-format
msgid "Number of retries to plugin (%(num_retries)d) exceeded."
msgstr ""

#: nova/exception.py:1562
#, python-format
msgid "There was an error with the download module %(module)s. %(reason)s"
msgstr ""

#: nova/exception.py:1567
#, python-format
msgid ""
"The metadata for this location will not work with this module %(module)s."
"  %(reason)s."
msgstr ""

#: nova/exception.py:1572
#, python-format
msgid "The method %(method_name)s is not implemented."
msgstr ""

#: nova/exception.py:1576
#, python-format
msgid "The module %(module)s is misconfigured: %(reason)s."
msgstr ""

#: nova/exception.py:1580
#, python-format
msgid "Error when creating resource monitor: %(monitor)s"
msgstr ""

#: nova/exception.py:1584
#, python-format
msgid "The PCI address %(address)s has an incorrect format."
msgstr ""

#: nova/exception.py:1588
#, python-format
msgid ""
"Invalid PCI Whitelist: The PCI address %(address)s has an invalid "
"%(field)s."
msgstr ""

#: nova/exception.py:1593
msgid ""
"Invalid PCI Whitelist: The PCI whitelist can specify devname or address, "
"but not both"
msgstr ""

#: nova/exception.py:1599
#, python-format
msgid "PCI device %(id)s not found"
msgstr ""

#: nova/exception.py:1603
#, python-format
msgid "PCI Device %(node_id)s:%(address)s not found."
msgstr ""

#: nova/exception.py:1607
#, python-format
msgid ""
"PCI device %(compute_node_id)s:%(address)s is %(status)s instead of "
"%(hopestatus)s"
msgstr ""

#: nova/exception.py:1613
#, python-format
msgid ""
"PCI device %(compute_node_id)s:%(address)s is owned by %(owner)s instead "
"of %(hopeowner)s"
msgstr ""

#: nova/exception.py:1619
#, python-format
msgid "PCI device request (%requests)s failed"
msgstr ""

#: nova/exception.py:1624
#, python-format
msgid ""
"Attempt to consume PCI device %(compute_node_id)s:%(address)s from empty "
"pool"
msgstr ""

#: nova/exception.py:1630
#, python-format
msgid "Invalid PCI alias definition: %(reason)s"
msgstr ""

#: nova/exception.py:1634
#, python-format
msgid "PCI alias %(alias)s is not defined"
msgstr ""

#: nova/exception.py:1639
#, python-format
msgid "Not enough parameters: %(reason)s"
msgstr ""

#: nova/exception.py:1644
#, python-format
msgid "Invalid PCI devices Whitelist config %(reason)s"
msgstr ""

#: nova/exception.py:1648
#, python-format
msgid "Cannot change %(node_id)s to %(new_node_id)s"
msgstr ""

#: nova/exception.py:1658
#, python-format
msgid ""
"Failed to prepare PCI device %(id)s for instance %(instance_uuid)s: "
"%(reason)s"
msgstr ""

#: nova/exception.py:1663
#, python-format
msgid "Failed to detach PCI device %(dev)s: %(reason)s"
msgstr ""

#: nova/exception.py:1667
#, python-format
msgid "%(type)s hypervisor does not support PCI devices"
msgstr ""

#: nova/exception.py:1671
#, python-format
msgid "Key manager error: %(reason)s"
msgstr ""

#: nova/exception.py:1675
#, python-format
msgid "Failed to remove volume(s): (%(reason)s)"
msgstr ""

#: nova/exception.py:1679
#, python-format
msgid "Provided video model (%(model)s) is not supported."
msgstr ""

#: nova/exception.py:1683
#, python-format
msgid "The provided RNG device path: (%(path)s) is not present on the host."
msgstr ""

#: nova/exception.py:1688
#, python-format
msgid ""
"The requested amount of video memory %(req_vram)d is higher than the "
"maximum allowed by flavor %(max_vram)d."
msgstr ""

#: nova/exception.py:1693
#, python-format
msgid "Provided watchdog action (%(action)s) is not supported."
msgstr ""

#: nova/exception.py:1697
msgid ""
"Live migration of instances with config drives is not supported in "
"libvirt unless libvirt instance path and drive data is shared across "
"compute nodes."
msgstr ""

#: nova/exception.py:1703
#, python-format
msgid ""
"Host %(server)s is running an old version of Nova, live migrations "
"involving that version may cause data loss. Upgrade Nova on %(server)s "
"and try again."
msgstr ""

#: nova/exception.py:1709
#, python-format
msgid "Error during unshelve instance %(instance_id)s: %(reason)s"
msgstr ""

#: nova/exception.py:1713
#, python-format
msgid ""
"Image vCPU limits %(sockets)d:%(cores)d:%(threads)d exceeds permitted "
"%(maxsockets)d:%(maxcores)d:%(maxthreads)d"
msgstr ""

#: nova/exception.py:1718
#, python-format
msgid ""
"Image vCPU topology %(sockets)d:%(cores)d:%(threads)d exceeds permitted "
"%(maxsockets)d:%(maxcores)d:%(maxthreads)d"
msgstr ""

#: nova/exception.py:1723
#, python-format
msgid ""
"Requested vCPU limits %(sockets)d:%(cores)d:%(threads)d are impossible to"
" satisfy for vcpus count %(vcpus)d"
msgstr ""

#: nova/exception.py:1728
#, python-format
msgid "Architecture name '%(arch)s' is not recognised"
msgstr ""

#: nova/exception.py:1732
msgid "CPU and memory allocation must be provided for all NUMA nodes"
msgstr ""

#: nova/exception.py:1737
#, python-format
msgid ""
"Image property '%(name)s' is not permitted to override NUMA configuration"
" set against the flavor"
msgstr ""

#: nova/exception.py:1742
msgid ""
"Asymmetric NUMA topologies require explicit assignment of CPUs and memory"
" to nodes in image or flavor"
msgstr ""

#: nova/exception.py:1747
#, python-format
msgid "CPU number %(cpunum)d is larger than max %(cpumax)d"
msgstr ""

#: nova/exception.py:1751
#, python-format
msgid "CPU number %(cpunum)d is assigned to two nodes"
msgstr ""

#: nova/exception.py:1755
#, python-format
msgid "CPU number %(cpuset)s is not assigned to any node"
msgstr ""

#: nova/exception.py:1759
#, python-format
msgid "%(memsize)d MB of memory assigned, but expected %(memtotal)d MB"
msgstr ""

#: nova/exception.py:1764
#, python-format
msgid "Invalid characters in hostname '%(hostname)s'"
msgstr ""

#: nova/exception.py:1768
#, python-format
msgid "Instance %(instance_uuid)s does not specify a NUMA topology"
msgstr ""

#: nova/exception.py:1772
#, python-format
msgid "Not able to acquire a free port for %(host)s"
msgstr ""

#: nova/exception.py:1776
#, python-format
msgid "Not able to bind %(host)s:%(port)d, %(error)s"
msgstr ""

#: nova/exception.py:1780
#, python-format
msgid ""
"Number of serial ports '%(num_ports)s' specified in '%(property)s' isn't "
"valid."
msgstr ""

#: nova/exception.py:1785
msgid ""
"Forbidden to exceed flavor value of number of serial ports passed in "
"image meta."
msgstr ""

#: nova/exception.py:1790
#, python-format
msgid "Image's config drive option '%(config_drive)s' is invalid"
msgstr ""

#: nova/exception.py:1794
#, python-format
msgid "Hypervisor virtualization type '%(hv_type)s' is not recognised"
msgstr ""

#: nova/exception.py:1799
#, python-format
msgid "Virtual machine mode '%(vmmode)s' is not recognised"
msgstr ""

#: nova/exception.py:1803
#, python-format
msgid "The token '%(token)s' is invalid or has expired"
msgstr ""

#: nova/exception.py:1807
msgid "Invalid Connection Info"
msgstr ""

#: nova/exception.py:1811
#, python-format
msgid "Quiescing is not supported in instance %(instance_id)s: %(reason)s"
msgstr ""

#: nova/exception.py:1816
#, python-format
msgid "Invalid memory page size '%(pagesize)s'"
msgstr ""

#: nova/exception.py:1820
#, python-format
msgid "Page size %(pagesize)s forbidden against '%(against)s'"
msgstr ""

#: nova/exception.py:1824
#, python-format
msgid "Page size %(pagesize)s is not supported by the host."
msgstr ""

#: nova/exception.py:1828
#, python-format
msgid ""
"Cannot pin/unpin cpus %(requested)s from the following pinned set "
"%(pinned)s"
msgstr ""

#: nova/exception.py:1833
msgid ""
"Image property 'hw_cpu_policy' is not permitted to override CPU pinning "
"policy set against the flavor"
msgstr ""

#: nova/hooks.py:77
msgid "Wrong type of hook method. Only 'pre' and 'post' type allowed"
msgstr ""

#: nova/service.py:161
#, fuzzy, python-format
msgid "Starting %(topic)s node (version %(version)s)"
msgstr "Starting %(topic)s node (version %(vcs_string)s)"

#: nova/service.py:345
#, python-format
msgid "%(worker_name)s value of %(workers)s is invalid, must be greater than 0"
msgstr ""

#: nova/service.py:438
msgid "serve() can only be called once"
msgstr "serve() can only be called once"

#: nova/utils.py:334
#, python-format
msgid "Link Local address is not found.:%s"
msgstr "Link Local address is not found.:%s"

#: nova/utils.py:337
#, python-format
msgid "Couldn't get Link Local IP of %(interface)s :%(ex)s"
msgstr "Couldn't get Link Local IP of %(interface)s :%(ex)s"

#: nova/utils.py:358
#, python-format
msgid "Invalid backend: %s"
msgstr "Invalid backend: %s"

#: nova/utils.py:401
#, python-format
msgid "Expected object of type: %s"
msgstr "Expected object of type: %s"

#: nova/utils.py:888
msgid "The input is not a string or unicode"
msgstr ""

#: nova/utils.py:890
#, fuzzy, python-format
msgid "%s is not a string or unicode"
msgstr "Server name is not a string or unicode"

#: nova/utils.py:897
#, python-format
msgid "%(name)s has a minimum character requirement of %(min_length)s."
msgstr ""

#: nova/utils.py:902
#, python-format
msgid "%(name)s has more than %(max_length)s characters."
msgstr ""

#: nova/utils.py:912
#, python-format
msgid "%(value_name)s must be an integer"
msgstr ""

#: nova/utils.py:918
#, python-format
msgid "%(value_name)s must be >= %(min_value)d"
msgstr ""

#: nova/utils.py:924
#, python-format
msgid "%(value_name)s must be <= %(max_value)d"
msgstr ""

#: nova/utils.py:958
#, python-format
msgid "Hypervisor version %s is invalid."
msgstr ""

#: nova/wsgi.py:170 nova/openstack/common/sslutils.py:53
#, fuzzy, python-format
msgid "Unable to find cert_file : %s"
msgstr "Unable to find address %r"

#: nova/wsgi.py:174 nova/openstack/common/sslutils.py:56
#, fuzzy, python-format
msgid "Unable to find ca_file : %s"
msgstr "Unable to find address %r"

#: nova/wsgi.py:178 nova/openstack/common/sslutils.py:59
#, fuzzy, python-format
msgid "Unable to find key_file : %s"
msgstr "Unable to find address %r"

#: nova/wsgi.py:182 nova/openstack/common/sslutils.py:62
msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""

#: nova/wsgi.py:342
msgid "You must implement __call__"
msgstr "You must implement __call__"

#: nova/api/auth.py:140
msgid "Invalid service catalog json."
msgstr "Invalid service catalog json."

#: nova/api/ec2/__init__.py:165
msgid "Too many failed authentications."
msgstr "Too many failed authentications."

#: nova/api/ec2/__init__.py:230
msgid "Signature not provided"
msgstr "Signature not provided"

#: nova/api/ec2/__init__.py:235
msgid "Access key not provided"
msgstr "Access key not provided"

#: nova/api/ec2/__init__.py:292
#, python-format
msgid "Failure parsing response from keystone: %s"
msgstr ""

#: nova/api/ec2/__init__.py:355
#, fuzzy
msgid "Timestamp failed validation."
msgstr "Too many failed authentications."

#: nova/api/ec2/__init__.py:457
#, python-format
msgid "Unauthorized request for controller=%(controller)s and action=%(action)s"
msgstr "Unauthorized request for controller=%(controller)s and action=%(action)s"

#: nova/api/ec2/__init__.py:576
msgid "Unknown error occurred."
msgstr ""

#: nova/api/ec2/cloud.py:407
#, python-format
msgid "Create snapshot of volume %s"
msgstr "Create snapshot of volume %s"

#: nova/api/ec2/cloud.py:434
#, python-format
msgid "Could not find key pair(s): %s"
msgstr "Could not find key pair(s): %s"

#: nova/api/ec2/cloud.py:450
#, python-format
msgid "Create key pair %s"
msgstr "Create key pair %s"

#: nova/api/ec2/cloud.py:462
#, python-format
msgid "Import key %s"
msgstr "Import key %s"

#: nova/api/ec2/cloud.py:475
#, python-format
msgid "Delete key pair %s"
msgstr "Delete key pair %s"

#: nova/api/ec2/cloud.py:617 nova/api/ec2/cloud.py:747
msgid "need group_name or group_id"
msgstr ""

#: nova/api/ec2/cloud.py:622
msgid "can't build a valid rule"
msgstr ""

#: nova/api/ec2/cloud.py:630
#, python-format
msgid "Invalid IP protocol %(protocol)s"
msgstr ""

#: nova/api/ec2/cloud.py:664 nova/api/ec2/cloud.py:700
msgid "No rule for the specified parameters."
msgstr "No rule for the specified parameters."

#: nova/api/ec2/cloud.py:778
#, python-format
msgid "Get console output for instance %s"
msgstr "Get console output for instance %s"

#: nova/api/ec2/cloud.py:851
#, python-format
msgid "Create volume from snapshot %s"
msgstr "Create volume from snapshot %s"

#: nova/api/ec2/cloud.py:855 nova/api/openstack/compute/contrib/volumes.py:162
#, python-format
msgid "Create volume of %s GB"
msgstr "Create volume of %s GB"

#: nova/api/ec2/cloud.py:895
#, python-format
msgid "Attach volume %(volume_id)s to instance %(instance_id)s at %(device)s"
msgstr "Attach volume %(volume_id)s to instance %(instance_id)s at %(device)s"

#: nova/api/ec2/cloud.py:925 nova/api/openstack/compute/contrib/volumes.py:393
#, python-format
msgid "Detach volume %s"
msgstr "Detach volume %s"

#: nova/api/ec2/cloud.py:1291
msgid "Allocate address"
msgstr "Allocate address"

#: nova/api/ec2/cloud.py:1296
#, python-format
msgid "Release address %s"
msgstr "Release address %s"

#: nova/api/ec2/cloud.py:1301
#, python-format
msgid "Associate address %(public_ip)s to instance %(instance_id)s"
msgstr "Associate address %(public_ip)s to instance %(instance_id)s"

#: nova/api/ec2/cloud.py:1312
msgid "Unable to associate IP Address, no fixed_ips."
msgstr "Unable to associate IP Address, no fixed_ips."

#: nova/api/ec2/cloud.py:1334
#, python-format
msgid "Disassociate address %s"
msgstr "Disassociate address %s"

#: nova/api/ec2/cloud.py:1338
msgid "Floating ip is not associated."
msgstr ""

#: nova/api/ec2/cloud.py:1354 nova/api/openstack/compute/servers.py:567
#: nova/api/openstack/compute/plugins/v3/multiple_create.py:56
msgid "min_count must be <= max_count"
msgstr "min_count must be <= max_count"

#: nova/api/ec2/cloud.py:1386
msgid "Image must be available"
msgstr "Image must be available"

#: nova/api/ec2/cloud.py:1486
#, python-format
msgid "Reboot instance %r"
msgstr "Reboot instance %r"

#: nova/api/ec2/cloud.py:1601
#, python-format
msgid "De-registering image %s"
msgstr "De-registering image %s"

#: nova/api/ec2/cloud.py:1617
msgid "imageLocation is required"
msgstr "imageLocation is required"

#: nova/api/ec2/cloud.py:1637
#, python-format
msgid "Registered image %(image_location)s with id %(image_id)s"
msgstr "Registered image %(image_location)s with id %(image_id)s"

#: nova/api/ec2/cloud.py:1698
msgid "user or group not specified"
msgstr "user or group not specified"

#: nova/api/ec2/cloud.py:1701
msgid "only group \"all\" is supported"
msgstr "only group \"all\" is supported"

#: nova/api/ec2/cloud.py:1704
msgid "operation_type must be add or remove"
msgstr "operation_type must be add or remove"

#: nova/api/ec2/cloud.py:1706
#, python-format
msgid "Updating image %s publicity"
msgstr "Updating image %s publicity"

#: nova/api/ec2/cloud.py:1719
#, python-format
msgid "Not allowed to modify attributes for image %s"
msgstr "Not allowed to modify attributes for image %s"

#: nova/api/ec2/cloud.py:1749
#, python-format
msgid ""
"Invalid value '%(ec2_instance_id)s' for instanceId. Instance does not "
"have a volume attached at root (%(root)s)"
msgstr ""
"Invalid value '%(ec2_instance_id)s' for instanceId. Instance does not "
"have a volume attached at root (%(root)s)"

#: nova/api/ec2/cloud.py:1782
#, python-format
msgid ""
"Couldn't stop instance %(instance)s within 1 hour. Current vm_state: "
"%(vm_state)s, current task_state: %(task_state)s"
msgstr ""

#: nova/api/ec2/cloud.py:1806
#, python-format
msgid "image of %(instance)s at %(now)s"
msgstr "image of %(instance)s at %(now)s"

#: nova/api/ec2/cloud.py:1831 nova/api/ec2/cloud.py:1881
msgid "resource_id and tag are required"
msgstr ""

#: nova/api/ec2/cloud.py:1835 nova/api/ec2/cloud.py:1885
#, fuzzy
msgid "Expecting a list of resources"
msgstr "Getting list of instances"

#: nova/api/ec2/cloud.py:1840 nova/api/ec2/cloud.py:1890
#: nova/api/ec2/cloud.py:1948
#, fuzzy
msgid "Only instances implemented"
msgstr "instance not present"

#: nova/api/ec2/cloud.py:1844 nova/api/ec2/cloud.py:1894
#, fuzzy
msgid "Expecting a list of tagSets"
msgstr "Getting list of instances"

#: nova/api/ec2/cloud.py:1850 nova/api/ec2/cloud.py:1903
msgid "Expecting tagSet to be key/value pairs"
msgstr ""

#: nova/api/ec2/cloud.py:1857
msgid "Expecting both key and value to be set"
msgstr ""

#: nova/api/ec2/cloud.py:1908
msgid "Expecting key to be set"
msgstr ""

#: nova/api/ec2/cloud.py:1982
msgid "Invalid CIDR"
msgstr "Invalid CIDR"

#: nova/api/ec2/ec2utils.py:256
#, python-format
msgid "Unacceptable attach status:%s for ec2 API."
msgstr ""

#: nova/api/ec2/ec2utils.py:279
msgid "Request must include either Timestamp or Expires, but cannot contain both"
msgstr ""

#: nova/api/ec2/ec2utils.py:297
#, fuzzy
msgid "Timestamp is invalid."
msgstr "The request is invalid."

#: nova/api/metadata/handler.py:149 nova/api/metadata/handler.py:208
msgid "An unknown error has occurred. Please try your request again."
msgstr "An unknown error has occurred. Please try your request again."

#: nova/api/metadata/handler.py:169
msgid "X-Instance-ID header is missing from request."
msgstr ""

#: nova/api/metadata/handler.py:171
msgid "X-Tenant-ID header is missing from request."
msgstr ""

#: nova/api/metadata/handler.py:173
msgid "Multiple X-Instance-ID headers found within request."
msgstr ""

#: nova/api/metadata/handler.py:175
msgid "Multiple X-Tenant-ID headers found within request."
msgstr ""

#: nova/api/metadata/handler.py:199
#, fuzzy
msgid "Invalid proxy request signature."
msgstr "Invalid request: %s"

#: nova/api/metadata/password.py:62
msgid "Request is too large."
msgstr "Request is too large."

#: nova/api/openstack/__init__.py:190
msgid "Must specify an ExtensionManager class"
msgstr "Must specify an ExtensionManager class"

#: nova/api/openstack/common.py:222
#, python-format
msgid "%s param must be an integer"
msgstr ""

#: nova/api/openstack/common.py:225
#, python-format
msgid "%s param must be positive"
msgstr ""

#: nova/api/openstack/common.py:250
msgid "offset param must be an integer"
msgstr "offset param must be an integer"

#: nova/api/openstack/common.py:256
msgid "limit param must be an integer"
msgstr "limit param must be an integer"

#: nova/api/openstack/common.py:260
msgid "limit param must be positive"
msgstr "limit param must be positive"

#: nova/api/openstack/common.py:264
msgid "offset param must be positive"
msgstr "offset param must be positive"

#: nova/api/openstack/common.py:317
#, python-format
msgid "href %s does not contain version"
msgstr "href %s does not contain version"

#: nova/api/openstack/common.py:330
msgid "Image metadata limit exceeded"
msgstr "Image metadata limit exceeded"

#: nova/api/openstack/common.py:337
msgid "Image metadata key cannot be blank"
msgstr "Image metadata key cannot be blank"

#: nova/api/openstack/common.py:340
msgid "Image metadata key too long"
msgstr "Image metadata key too long"

#: nova/api/openstack/common.py:343
msgid "Invalid image metadata"
msgstr "Invalid image metadata"

#: nova/api/openstack/common.py:406
#, python-format
msgid ""
"Cannot '%(action)s' instance %(server_id)s while it is in %(attr)s "
"%(state)s"
msgstr ""

#: nova/api/openstack/common.py:411
#, python-format
msgid "Cannot '%(action)' instance %(server_id)s which has never been active"
msgstr ""

#: nova/api/openstack/common.py:415
#, python-format
msgid "Instance %(server_id)s is in an invalid state for '%(action)s'"
msgstr ""

#: nova/api/openstack/common.py:426
msgid "Instance snapshots are not permitted at this time."
msgstr "Instance snapshots are not permitted at this time."

#: nova/api/openstack/common.py:548
msgid "Cells is not enabled."
msgstr ""

#: nova/api/openstack/extensions.py:302
#, python-format
msgid "Failed to load extension %(classpath)s: %(exc)s"
msgstr "Failed to load extension %(classpath)s: %(exc)s"

#: nova/api/openstack/extensions.py:325
#, fuzzy, python-format
msgid "Failed to load extension %(ext_name)s:%(exc)s"
msgstr "Failed to load extension %(ext_name)s: %(exc)s"

#: nova/api/openstack/extensions.py:474
#, python-format
msgid ""
"Unexpected API Error. Please report this at "
"http://bugs.launchpad.net/nova/ and attach the Nova API log if possible."
"\n"
"%s"
msgstr ""

#: nova/api/openstack/wsgi.py:270 nova/api/openstack/wsgi.py:480
msgid "cannot understand JSON"
msgstr "cannot understand JSON"

#: nova/api/openstack/wsgi.py:485
msgid "too many body keys"
msgstr "too many body keys"

#: nova/api/openstack/wsgi.py:762
#, python-format
msgid "There is no such action: %s"
msgstr "There is no such action: %s"

#: nova/api/openstack/wsgi.py:765 nova/api/openstack/wsgi.py:791
#: nova/api/openstack/compute/server_metadata.py:54
#: nova/api/openstack/compute/server_metadata.py:73
#: nova/api/openstack/compute/server_metadata.py:100
#: nova/api/openstack/compute/server_metadata.py:130
#: nova/api/openstack/compute/contrib/evacuate.py:47
msgid "Malformed request body"
msgstr "Malformed request body"

#: nova/api/openstack/wsgi.py:769
#, python-format
msgid "Action: '%(action)s', calling method: %(meth)s, body: %(body)s"
msgstr ""

#: nova/api/openstack/wsgi.py:788
msgid "Unsupported Content-Type"
msgstr "Unsupported Content-Type"

#: nova/api/openstack/wsgi.py:800
#, python-format
msgid ""
"Malformed request URL: URL's project_id '%(project_id)s' doesn't match "
"Context's project_id '%(context_project_id)s'"
msgstr ""

#: nova/api/openstack/compute/flavors.py:67
#: nova/api/openstack/compute/plugins/v3/flavors.py:73
#, python-format
msgid "Invalid is_public filter [%s]"
msgstr "Invalid is_public filter [%s]"

#: nova/api/openstack/compute/flavors.py:90
#, python-format
msgid "Invalid minRam filter [%s]"
msgstr "Invalid minRam filter [%s]"

#: nova/api/openstack/compute/flavors.py:97
#: nova/api/openstack/compute/plugins/v3/flavors.py:103
#, python-format
msgid "Invalid minDisk filter [%s]"
msgstr "Invalid minDisk filter [%s]"

#: nova/api/openstack/compute/flavors.py:105
#: nova/api/openstack/compute/servers.py:225
#: nova/api/openstack/compute/plugins/v3/flavors.py:112
#: nova/api/openstack/compute/plugins/v3/servers.py:367
#, python-format
msgid "marker [%s] not found"
msgstr "marker [%s] not found"

#: nova/api/openstack/compute/image_metadata.py:37
#: nova/api/openstack/compute/images.py:85
#: nova/api/openstack/compute/images.py:101
#: nova/api/openstack/compute/plugins/v3/image_metadata.py:42
#: nova/api/openstack/compute/plugins/v3/images.py:89
#: nova/api/openstack/compute/plugins/v3/images.py:107
msgid "Image not found."
msgstr "Image not found."

#: nova/api/openstack/compute/image_metadata.py:75
msgid "Incorrect request body format"
msgstr "Incorrect request body format"

#: nova/api/openstack/compute/image_metadata.py:79
#: nova/api/openstack/compute/server_metadata.py:81
#: nova/api/openstack/compute/contrib/flavorextraspecs.py:98
#: nova/api/openstack/compute/plugins/v3/flavors_extraspecs.py:91
#: nova/api/openstack/compute/plugins/v3/image_metadata.py:85
#: nova/api/openstack/compute/plugins/v3/server_metadata.py:78
msgid "Request body and URI mismatch"
msgstr "Request body and URI mismatch"

#: nova/api/openstack/compute/image_metadata.py:82
#: nova/api/openstack/compute/server_metadata.py:85
#: nova/api/openstack/compute/contrib/flavorextraspecs.py:101
msgid "Request body contains too many items"
msgstr "Request body contains too many items"

#: nova/api/openstack/compute/image_metadata.py:114
#: nova/api/openstack/compute/plugins/v3/image_metadata.py:120
msgid "Invalid metadata key"
msgstr "Invalid metadata key"

#: nova/api/openstack/compute/images.py:106
#: nova/api/openstack/compute/plugins/v3/images.py:112
msgid "You are not allowed to delete the image."
msgstr ""

#: nova/api/openstack/compute/ips.py:45
#: nova/api/openstack/compute/plugins/v3/ips.py:50
msgid "Instance is not a member of specified network"
msgstr "Instance is not a member of specified network"

#: nova/api/openstack/compute/limits.py:132
#, python-format
msgid ""
"Only %(value)s %(verb)s request(s) can be made to %(uri)s every "
"%(unit_string)s."
msgstr ""
"Only %(value)s %(verb)s request(s) can be made to %(uri)s every "
"%(unit_string)s."

#: nova/api/openstack/compute/limits.py:260
msgid "This request was rate-limited."
msgstr "This request was rate-limited."

#: nova/api/openstack/compute/server_metadata.py:37
#: nova/api/openstack/compute/server_metadata.py:126
#: nova/api/openstack/compute/server_metadata.py:178
#: nova/api/openstack/compute/plugins/v3/server_metadata.py:45
msgid "Server does not exist"
msgstr "Server does not exist"

#: nova/api/openstack/compute/server_metadata.py:57
#: nova/api/openstack/compute/server_metadata.py:104
msgid "Malformed request body. metadata must be object"
msgstr ""

#: nova/api/openstack/compute/server_metadata.py:77
msgid "Malformed request body. meta item must be object"
msgstr ""

#: nova/api/openstack/compute/server_metadata.py:158
#: nova/api/openstack/compute/server_metadata.py:169
#: nova/api/openstack/compute/plugins/v3/server_metadata.py:130
#: nova/api/openstack/compute/plugins/v3/server_metadata.py:142
msgid "Metadata item was not found"
msgstr "Metadata item was not found"

#: nova/api/openstack/compute/servers.py:91
#: nova/api/openstack/compute/plugins/v3/servers.py:552
msgid "Can not find requested image"
msgstr "Can not find requested image"

#: nova/api/openstack/compute/servers.py:92
#: nova/api/openstack/compute/servers.py:876
#: nova/api/openstack/compute/plugins/v3/servers.py:529
#: nova/api/openstack/compute/plugins/v3/servers.py:555
msgid "Invalid flavorRef provided."
msgstr "Invalid flavorRef provided."

#: nova/api/openstack/compute/servers.py:93
#: nova/api/openstack/compute/plugins/v3/servers.py:558
msgid "Invalid key_name provided."
msgstr "Invalid key_name provided."

#: nova/api/openstack/compute/servers.py:94
#: nova/api/openstack/compute/plugins/v3/servers.py:561
msgid "Invalid config_drive provided."
msgstr ""

#: nova/api/openstack/compute/servers.py:167
#: nova/api/openstack/compute/contrib/cells.py:332
#: nova/api/openstack/compute/plugins/v3/servers.py:294
msgid "Invalid changes-since value"
msgstr "Invalid changes-since value"

#: nova/api/openstack/compute/servers.py:186
#: nova/api/openstack/compute/plugins/v3/servers.py:313
msgid "Only administrators may list deleted instances"
msgstr "Only administrators may list deleted instances"

#: nova/api/openstack/compute/servers.py:272
#, python-format
msgid "Bad personality format: missing %s"
msgstr "Bad personality format: missing %s"

#: nova/api/openstack/compute/servers.py:275
msgid "Bad personality format"
msgstr "Bad personality format"

#: nova/api/openstack/compute/servers.py:278
#, python-format
msgid "Personality content for %s cannot be decoded"
msgstr "Personality content for %s cannot be decoded"

#: nova/api/openstack/compute/servers.py:293
#, python-format
msgid "Bad port format: port uuid is not in proper format (%s)"
msgstr "Bad port format: port uuid is not in proper format (%s)"

#: nova/api/openstack/compute/servers.py:301
msgid "Unknown argument : port"
msgstr ""

#: nova/api/openstack/compute/servers.py:310
#: nova/api/openstack/compute/plugins/v3/servers.py:432
#, python-format
msgid "Bad networks format: network uuid is not in proper format (%s)"
msgstr "Bad networks format: network uuid is not in proper format (%s)"

#: nova/api/openstack/compute/servers.py:321
#, python-format
msgid "Invalid fixed IP address (%s)"
msgstr "Invalid fixed IP address (%s)"

#: nova/api/openstack/compute/servers.py:326
#: nova/api/openstack/compute/plugins/v3/servers.py:439
#, python-format
msgid "Duplicate networks (%s) are not allowed"
msgstr "Duplicate networks (%s) are not allowed"

#: nova/api/openstack/compute/servers.py:333
#: nova/api/openstack/compute/plugins/v3/servers.py:446
#, python-format
msgid "Bad network format: missing %s"
msgstr "Bad network format: missing %s"

#: nova/api/openstack/compute/servers.py:336
#: nova/api/openstack/compute/servers.py:479
#: nova/api/openstack/compute/plugins/v3/servers.py:449
msgid "Bad networks format"
msgstr "Bad networks format"

#: nova/api/openstack/compute/servers.py:359
msgid "accessIPv4 is not proper IPv4 format"
msgstr "accessIPv4 is not proper IPv4 format"

#: nova/api/openstack/compute/servers.py:364
msgid "accessIPv6 is not proper IPv6 format"
msgstr "accessIPv6 is not proper IPv6 format"

#: nova/api/openstack/compute/servers.py:380
msgid "Userdata content cannot be decoded"
msgstr "Userdata content cannot be decoded"

#: nova/api/openstack/compute/servers.py:392
msgid "block_device_mapping must be a list"
msgstr ""

#: nova/api/openstack/compute/servers.py:412
#: nova/api/openstack/compute/plugins/v3/block_device_mapping.py:54
#: nova/api/openstack/compute/plugins/v3/block_device_mapping_v1.py:53
msgid ""
"Using different block_device_mapping syntaxes is not allowed in the same "
"request."
msgstr ""

#: nova/api/openstack/compute/servers.py:417
msgid "block_device_mapping_v2 must be a list"
msgstr ""

#: nova/api/openstack/compute/servers.py:496
msgid "Server name is not defined"
msgstr "Server name is not defined"

#: nova/api/openstack/compute/servers.py:684
msgid "HostId cannot be updated."
msgstr "HostId cannot be updated."

#: nova/api/openstack/compute/servers.py:688
#, fuzzy
msgid "Personality cannot be updated."
msgstr "HostId cannot be updated."

#: nova/api/openstack/compute/servers.py:698
#: nova/api/openstack/compute/servers.py:816
#: nova/api/openstack/compute/servers.py:1003
#: nova/api/openstack/compute/plugins/v3/servers.py:735
#: nova/api/openstack/compute/plugins/v3/servers.py:856
#: nova/api/openstack/compute/plugins/v3/servers.py:963
msgid "Instance could not be found"
msgstr "Instance could not be found"

#: nova/api/openstack/compute/servers.py:711
#: nova/api/openstack/compute/servers.py:727
#: nova/api/openstack/compute/plugins/v3/servers.py:750
#: nova/api/openstack/compute/plugins/v3/servers.py:767
msgid "Instance has not been resized."
msgstr "Instance has not been resized."

#: nova/api/openstack/compute/servers.py:730
#: nova/api/openstack/compute/plugins/v3/servers.py:770
#, fuzzy
msgid "Flavor used by the instance could not be found."
msgstr "Instance %(instance_id)s could not be found."

#: nova/api/openstack/compute/servers.py:744
#: nova/api/openstack/compute/plugins/v3/servers.py:784
msgid "Argument 'type' for reboot must be a string"
msgstr ""

#: nova/api/openstack/compute/servers.py:750
#: nova/api/openstack/compute/plugins/v3/servers.py:790
msgid "Argument 'type' for reboot is not HARD or SOFT"
msgstr "Argument 'type' for reboot is not HARD or SOFT"

#: nova/api/openstack/compute/servers.py:754
#: nova/api/openstack/compute/plugins/v3/servers.py:794
msgid "Missing argument 'type' for reboot"
msgstr "Missing argument 'type' for reboot"

#: nova/api/openstack/compute/servers.py:781
#: nova/api/openstack/compute/plugins/v3/servers.py:821
msgid "Unable to locate requested flavor."
msgstr "Unable to locate requested flavor."

#: nova/api/openstack/compute/servers.py:784
#: nova/api/openstack/compute/plugins/v3/servers.py:824
msgid "Resize requires a flavor change."
msgstr "Resize requires a flavor change."

#: nova/api/openstack/compute/servers.py:794
#: nova/api/openstack/compute/plugins/v3/servers.py:835
msgid "You are not authorized to access the image the instance was started with."
msgstr ""

#: nova/api/openstack/compute/servers.py:798
#: nova/api/openstack/compute/plugins/v3/servers.py:839
#, fuzzy
msgid "Image that the instance was started with could not be found."
msgstr "Instance %(instance_id)s could not be found."

#: nova/api/openstack/compute/servers.py:805
#: nova/api/openstack/compute/plugins/v3/servers.py:846
#, fuzzy
msgid "Invalid instance image."
msgstr "%s is a valid instance name"

#: nova/api/openstack/compute/servers.py:828
#: nova/api/openstack/compute/plugins/v3/servers.py:889
msgid "Missing imageRef attribute"
msgstr "Missing imageRef attribute"

#: nova/api/openstack/compute/servers.py:833
#: nova/api/openstack/compute/servers.py:841
#: nova/api/openstack/compute/plugins/v3/servers.py:870
msgid "Invalid imageRef provided."
msgstr "Invalid imageRef provided."

#: nova/api/openstack/compute/servers.py:871
msgid "Missing flavorRef attribute"
msgstr "Missing flavorRef attribute"

#: nova/api/openstack/compute/servers.py:885
msgid "No adminPass was specified"
msgstr "No adminPass was specified"

#: nova/api/openstack/compute/servers.py:898
#: nova/api/openstack/compute/plugins/v3/admin_password.py:59
#, fuzzy
msgid "Unable to set password on instance"
msgstr "Failed to soft reboot instance."

#: nova/api/openstack/compute/servers.py:907
msgid "Unable to parse metadata key/value pairs."
msgstr "Unable to parse metadata key/value pairs."

#: nova/api/openstack/compute/servers.py:918
msgid "Resize request has invalid 'flavorRef' attribute."
msgstr "Resize request has invalid 'flavorRef' attribute."

#: nova/api/openstack/compute/servers.py:921
msgid "Resize requests require 'flavorRef' attribute."
msgstr "Resize requests require 'flavorRef' attribute."

#: nova/api/openstack/compute/servers.py:939
msgid "Could not parse imageRef from request."
msgstr "Could not parse imageRef from request."

#: nova/api/openstack/compute/servers.py:1009
#: nova/api/openstack/compute/plugins/v3/servers.py:966
msgid "Cannot find image for rebuild"
msgstr "Cannot find image for rebuild"

#: nova/api/openstack/compute/servers.py:1043
#: nova/api/openstack/compute/plugins/v3/servers.py:1001
msgid "createImage entity requires name attribute"
msgstr "createImage entity requires name attribute"

#: nova/api/openstack/compute/servers.py:1052
#: nova/api/openstack/compute/contrib/admin_actions.py:291
#: nova/api/openstack/compute/plugins/v3/servers.py:1010
msgid "Invalid metadata"
msgstr "Invalid metadata"

#: nova/api/openstack/compute/servers.py:1110
msgid "Invalid adminPass"
msgstr "Invalid adminPass"

#: nova/api/openstack/compute/contrib/admin_actions.py:66
#: nova/api/openstack/compute/contrib/admin_actions.py:89
#: nova/api/openstack/compute/contrib/admin_actions.py:112
#: nova/api/openstack/compute/contrib/admin_actions.py:135
#: nova/api/openstack/compute/contrib/admin_actions.py:178
#: nova/api/openstack/compute/contrib/admin_actions.py:198
#: nova/api/openstack/compute/contrib/admin_actions.py:218
#: nova/api/openstack/compute/contrib/admin_actions.py:238
#: nova/api/openstack/compute/contrib/admin_actions.py:395
msgid "Server not found"
msgstr "Server not found"

#: nova/api/openstack/compute/contrib/admin_actions.py:268
#, python-format
msgid "createBackup entity requires %s attribute"
msgstr "createBackup entity requires %s attribute"

#: nova/api/openstack/compute/contrib/admin_actions.py:272
msgid "Malformed createBackup entity"
msgstr "Malformed createBackup entity"

#: nova/api/openstack/compute/contrib/admin_actions.py:278
msgid "createBackup attribute 'rotation' must be an integer"
msgstr "createBackup attribute 'rotation' must be an integer"

#: nova/api/openstack/compute/contrib/admin_actions.py:281
#, fuzzy
msgid "createBackup attribute 'rotation' must be greater than or equal to zero"
msgstr "createBackup attribute 'rotation' must be an integer"

#: nova/api/openstack/compute/contrib/admin_actions.py:324
msgid ""
"host, block_migration and disk_over_commit must be specified for live "
"migration."
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:363
#, fuzzy, python-format
msgid "Live migration of instance %s to another host failed"
msgstr "Live migration of instance %(id)s to host %(host)s failed"

#: nova/api/openstack/compute/contrib/admin_actions.py:366
#, python-format
msgid "Live migration of instance %(id)s to host %(host)s failed"
msgstr "Live migration of instance %(id)s to host %(host)s failed"

#: nova/api/openstack/compute/contrib/admin_actions.py:384
#, python-format
msgid "Desired state must be specified.  Valid states are: %s"
msgstr "Desired state must be specified.  Valid states are: %s"

#: nova/api/openstack/compute/contrib/agents.py:82
#: nova/api/openstack/compute/contrib/agents.py:100
#: nova/api/openstack/compute/contrib/agents.py:138
#: nova/api/openstack/compute/contrib/cloudpipe_update.py:56
#, python-format
msgid "Invalid request body: %s"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:39
msgid "Only host parameter can be specified"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:42
msgid "Host parameter must be specified"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:176
#, python-format
msgid "Aggregates does not have %s action"
msgstr "Aggregates does not have %s action"

#: nova/api/openstack/compute/contrib/aggregates.py:180
#: nova/api/openstack/compute/contrib/flavormanage.py:53
#: nova/api/openstack/compute/contrib/keypairs.py:69
msgid "Invalid request body"
msgstr "Invalid request body"

#: nova/api/openstack/compute/contrib/aggregates.py:190
#, python-format
msgid "Cannot add host %(host)s in aggregate %(id)s: not found"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:195
#, python-format
msgid "Cannot add host %(host)s in aggregate %(id)s: host exists"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:209
#, python-format
msgid "Cannot remove host %(host)s in aggregate %(id)s: not found"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:213
#, python-format
msgid "Cannot remove host %(host)s in aggregate %(id)s: invalid"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:232
msgid "The value of metadata must be a dict"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:245
#, python-format
msgid "Cannot set metadata %(metadata)s in aggregate %(id)s"
msgstr "Cannot set metadata %(metadata)s in aggregate %(id)s"

#: nova/api/openstack/compute/contrib/assisted_volume_snapshots.py:53
#: nova/api/openstack/compute/plugins/v3/assisted_volume_snapshots.py:57
#, python-format
msgid "Create assisted snapshot from volume %s"
msgstr ""

#: nova/api/openstack/compute/contrib/assisted_volume_snapshots.py:64
#: nova/api/openstack/compute/contrib/volumes.py:503
#: nova/api/openstack/compute/plugins/v3/assisted_volume_snapshots.py:73
#, python-format
msgid "Delete snapshot with id: %s"
msgstr "Delete snapshot with id: %s"

#: nova/api/openstack/compute/contrib/attach_interfaces.py:79
#: nova/api/openstack/compute/plugins/v3/attach_interfaces.py:82
#, python-format
msgid "Instance %(instance)s does not have a port with id %(port)s"
msgstr ""

#: nova/api/openstack/compute/contrib/attach_interfaces.py:104
#: nova/api/openstack/compute/plugins/v3/attach_interfaces.py:109
msgid "Must not input both network_id and port_id"
msgstr ""

#: nova/api/openstack/compute/contrib/attach_interfaces.py:107
#: nova/api/openstack/compute/plugins/v3/attach_interfaces.py:112
msgid "Must input network_id when request IP address"
msgstr ""

#: nova/api/openstack/compute/contrib/attach_interfaces.py:120
#, fuzzy
msgid "Attach interface"
msgstr "Failed to add interface: %s"

#: nova/api/openstack/compute/contrib/attach_interfaces.py:133
#: nova/api/openstack/compute/contrib/attach_interfaces.py:161
#: nova/api/openstack/compute/contrib/attach_interfaces.py:183
#: nova/api/openstack/compute/plugins/v3/attach_interfaces.py:179
#: nova/network/security_group/neutron_driver.py:524
#: nova/network/security_group/neutron_driver.py:528
#: nova/network/security_group/neutron_driver.py:532
#: nova/network/security_group/neutron_driver.py:536
#: nova/network/security_group/neutron_driver.py:540
#, fuzzy
msgid "Network driver does not support this function."
msgstr "Virt driver does not implement uptime function."

#: nova/api/openstack/compute/contrib/attach_interfaces.py:136
#, fuzzy
msgid "Failed to attach interface"
msgstr "Failed to add interface: %s"

#: nova/api/openstack/compute/contrib/attach_interfaces.py:152
#, fuzzy, python-format
msgid "Detach interface %s"
msgstr "Starting VLAN interface %s"

#: nova/api/openstack/compute/contrib/baremetal_nodes.py:77
#: nova/api/openstack/compute/plugins/v3/baremetal_nodes.py:75
#, python-format
msgid ""
"Command Not supported. Please use Ironic command %(cmd)s to perform this "
"action."
msgstr ""

#: nova/api/openstack/compute/contrib/cells.py:155
#, fuzzy, python-format
msgid "Cell %(id)s not found."
msgstr "Rule (%s) not found"

#: nova/api/openstack/compute/contrib/cells.py:190
#, fuzzy
msgid "Cell name cannot be empty"
msgstr "Security group name cannot be empty"

#: nova/api/openstack/compute/contrib/cells.py:193
msgid "Cell name cannot contain '!' or '.'"
msgstr ""

#: nova/api/openstack/compute/contrib/cells.py:199
msgid "Cell type must be 'parent' or 'child'"
msgstr ""

#: nova/api/openstack/compute/contrib/cells.py:235
msgid "rpc_port must be integer"
msgstr ""

#: nova/api/openstack/compute/contrib/cells.py:260
#: nova/api/openstack/compute/contrib/cells.py:283
#, fuzzy
msgid "No cell information in request"
msgstr "Block device information present: %s"

#: nova/api/openstack/compute/contrib/cells.py:264
msgid "No cell name in request"
msgstr ""

#: nova/api/openstack/compute/contrib/cells.py:320
msgid "Only 'updated_since', 'project_id' and 'deleted' are understood."
msgstr ""

#: nova/api/openstack/compute/contrib/certificates.py:44
#: nova/api/openstack/compute/plugins/v3/certificates.py:49
msgid "Only root certificate can be retrieved."
msgstr "Only root certificate can be retrieved."

#: nova/api/openstack/compute/contrib/cloudpipe.py:129
#: nova/api/openstack/compute/plugins/v3/cloudpipe.py:136
msgid ""
"Unable to claim IP for VPN instances, ensure it isn't running, and try "
"again in a few minutes"
msgstr ""
"Unable to claim IP for VPN instances, ensure it isn't running, and try "
"again in a few minutes"

#: nova/api/openstack/compute/contrib/cloudpipe_update.py:41
#: nova/api/openstack/compute/plugins/v3/cloudpipe.py:160
#, fuzzy, python-format
msgid "Unknown action %s"
msgstr "Unknown chain: %r"

#: nova/api/openstack/compute/contrib/console_auth_tokens.py:40
#: nova/api/openstack/compute/plugins/v3/console_auth_tokens.py:45
msgid "Token not found"
msgstr ""

#: nova/api/openstack/compute/contrib/console_auth_tokens.py:46
#: nova/api/openstack/compute/plugins/v3/console_auth_tokens.py:51
msgid "The requested console type details are not accessible"
msgstr ""

#: nova/api/openstack/compute/contrib/console_output.py:48
msgid "os-getConsoleOutput malformed or missing from request body"
msgstr "os-getConsoleOutput malformed or missing from request body"

#: nova/api/openstack/compute/contrib/console_output.py:59
msgid "Length in request body must be an integer value"
msgstr "Length in request body must be an integer value"

#: nova/api/openstack/compute/contrib/console_output.py:67
msgid "Unable to get console"
msgstr "Unable to get console"

#: nova/api/openstack/compute/contrib/console_output.py:72
#: nova/api/openstack/compute/plugins/v3/console_output.py:65
msgid "Unable to get console log, functionality not implemented"
msgstr ""

#: nova/api/openstack/compute/contrib/consoles.py:50
#, fuzzy
msgid "Instance not yet ready"
msgstr "instance %s:not booted"

#: nova/api/openstack/compute/contrib/consoles.py:57
#: nova/api/openstack/compute/plugins/v3/remote_consoles.py:60
msgid "Unable to get vnc console, functionality not implemented"
msgstr ""

#: nova/api/openstack/compute/contrib/consoles.py:85
#: nova/api/openstack/compute/plugins/v3/remote_consoles.py:89
msgid "Unable to get spice console, functionality not implemented"
msgstr ""

#: nova/api/openstack/compute/contrib/consoles.py:114
#: nova/api/openstack/compute/plugins/v3/remote_consoles.py:121
msgid "Unable to get rdp console, functionality not implemented"
msgstr ""

#: nova/api/openstack/compute/contrib/consoles.py:144
#: nova/api/openstack/compute/plugins/v3/remote_consoles.py:151
msgid "Unable to get serial console, functionality not implemented"
msgstr ""

#: nova/api/openstack/compute/contrib/disk_config.py:41
#: nova/api/openstack/compute/plugins/v3/disk_config.py:41
#, python-format
msgid "%s must be either 'MANUAL' or 'AUTO'."
msgstr "%s must be either 'MANUAL' or 'AUTO'."

#: nova/api/openstack/compute/contrib/evacuate.py:54
msgid "host must be specified."
msgstr ""

#: nova/api/openstack/compute/contrib/evacuate.py:61
msgid "onSharedStorage must be specified."
msgstr ""

#: nova/api/openstack/compute/contrib/evacuate.py:69
#: nova/api/openstack/compute/plugins/v3/evacuate.py:67
msgid "admin password can't be changed on existing disk"
msgstr ""

#: nova/api/openstack/compute/contrib/evacuate.py:80
#: nova/api/openstack/compute/plugins/v3/evacuate.py:78
#, python-format
msgid "Compute host %s not found."
msgstr ""

#: nova/api/openstack/compute/contrib/evacuate.py:87
#: nova/api/openstack/compute/plugins/v3/evacuate.py:84
msgid "The target host can't be the same one."
msgstr ""

#: nova/api/openstack/compute/contrib/fixed_ips.py:43
#: nova/api/openstack/compute/plugins/v3/fixed_ips.py:46
#, python-format
msgid "Fixed IP %s has been deleted"
msgstr ""

#: nova/api/openstack/compute/contrib/fixed_ips.py:76
#: nova/api/openstack/compute/plugins/v3/fixed_ips.py:84
#, fuzzy, python-format
msgid "Fixed IP %s not found"
msgstr "Fixed ip %(fixed_ip_id)s not found"

#: nova/api/openstack/compute/contrib/flavor_access.py:54
msgid "Flavor not found."
msgstr "Flavor not found."

#: nova/api/openstack/compute/contrib/flavor_access.py:59
#: nova/api/openstack/compute/plugins/v3/flavor_access.py:61
msgid "Access list not available for public flavors."
msgstr "Access list not available for public flavors."

#: nova/api/openstack/compute/contrib/flavor_access.py:71
msgid "No request body"
msgstr "No request body"

#: nova/api/openstack/compute/contrib/flavor_access.py:112
#: nova/api/openstack/compute/contrib/flavor_access.py:135
msgid "Missing tenant parameter"
msgstr ""

#: nova/api/openstack/compute/contrib/flavorextraspecs.py:40
msgid "No Request Body"
msgstr "No Request Body"

#: nova/api/openstack/compute/contrib/flavorextraspecs.py:45
msgid "Bad extra_specs provided"
msgstr ""

#: nova/api/openstack/compute/contrib/flavorextraspecs.py:51
msgid "Fail to validate provided extra specs keys. Expected string"
msgstr ""

#: nova/api/openstack/compute/contrib/flavorextraspecs.py:123
#: nova/api/openstack/compute/contrib/flavorextraspecs.py:139
#: nova/api/openstack/compute/plugins/v3/flavors_extraspecs.py:115
#: nova/api/openstack/compute/plugins/v3/flavors_extraspecs.py:136
#, python-format
msgid "Flavor %(flavor_id)s has no extra specs with key %(key)s."
msgstr ""

#: nova/api/openstack/compute/contrib/flavormanage.py:58
msgid "A valid name parameter is required"
msgstr ""

#: nova/api/openstack/compute/contrib/flavormanage.py:64
msgid "A valid ram parameter is required"
msgstr ""

#: nova/api/openstack/compute/contrib/flavormanage.py:69
msgid "A valid vcpus parameter is required"
msgstr ""

#: nova/api/openstack/compute/contrib/flavormanage.py:74
msgid "A valid disk parameter is required"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ip_dns.py:93
#: nova/api/openstack/compute/plugins/v3/floating_ip_dns.py:192
msgid "Unable to get dns domain"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ip_dns.py:130
#: nova/api/openstack/compute/plugins/v3/floating_ip_dns.py:98
#: nova/api/openstack/compute/plugins/v3/floating_ip_dns.py:138
msgid "Unable to create dns domain"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ip_dns.py:149
#: nova/api/openstack/compute/plugins/v3/floating_ip_dns.py:157
#: nova/api/openstack/compute/plugins/v3/floating_ip_dns.py:252
msgid "Unable to delete dns domain"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ip_dns.py:181
msgid "Unable to get dns entry"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ip_dns.py:185
#: nova/api/openstack/compute/plugins/v3/floating_ip_dns.py:196
#, fuzzy
msgid "DNS entries not found."
msgstr "Instance not found"

#: nova/api/openstack/compute/contrib/floating_ip_dns.py:222
msgid "Unable to create dns entry"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ip_dns.py:242
msgid "Unable to delete dns entry"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:93
#: nova/api/openstack/compute/contrib/floating_ips.py:142
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:102
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:157
#, python-format
msgid "Floating ip not found for id %s"
msgstr "Floating ip not found for id %s"

#: nova/api/openstack/compute/contrib/floating_ips.py:119
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:132
#, python-format
msgid "No more floating ips in pool %s."
msgstr "No more floating ips in pool %s."

#: nova/api/openstack/compute/contrib/floating_ips.py:121
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:134
msgid "No more floating ips available."
msgstr "No more floating ips available."

#: nova/api/openstack/compute/contrib/floating_ips.py:125
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:138
#, python-format
msgid "IP allocation over quota in pool %s."
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:127
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:140
msgid "IP allocation over quota."
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:175
#: nova/api/openstack/compute/contrib/floating_ips.py:245
#: nova/api/openstack/compute/contrib/security_groups.py:352
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:192
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:262
#: nova/api/openstack/compute/plugins/v3/security_groups.py:367
msgid "Missing parameter dict"
msgstr "Missing parameter dict"

#: nova/api/openstack/compute/contrib/floating_ips.py:178
#: nova/api/openstack/compute/contrib/floating_ips.py:248
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:195
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:265
msgid "Address not specified"
msgstr "Address not specified"

#: nova/api/openstack/compute/contrib/floating_ips.py:185
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:202
msgid "No nw_info cache associated with instance"
msgstr "No nw_info cache associated with instance"

#: nova/api/openstack/compute/contrib/floating_ips.py:190
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:207
msgid "No fixed ips associated to instance"
msgstr "No fixed ips associated to instance"

#: nova/api/openstack/compute/contrib/floating_ips.py:201
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:217
#, fuzzy
msgid "Specified fixed address not assigned to instance"
msgstr "No fixed ips associated to instance"

#: nova/api/openstack/compute/contrib/floating_ips.py:215
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:231
msgid "floating ip is already associated"
msgstr "floating ip is already associated"

#: nova/api/openstack/compute/contrib/floating_ips.py:218
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:234
msgid "l3driver call to add floating ip failed"
msgstr "l3driver call to add floating ip failed"

#: nova/api/openstack/compute/contrib/floating_ips.py:221
#: nova/api/openstack/compute/contrib/floating_ips.py:256
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:237
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:273
msgid "floating ip not found"
msgstr "floating ip not found"

#: nova/api/openstack/compute/contrib/floating_ips.py:226
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:242
#, python-format
msgid ""
"Unable to associate floating ip %(address)s to fixed ip %(fixed_address)s"
" for instance %(id)s. Error: %(error)s"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:271
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:288
msgid "Floating ip is not associated"
msgstr "Floating ip is not associated"

#: nova/api/openstack/compute/contrib/floating_ips.py:275
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:292
#, fuzzy, python-format
msgid "Floating ip %(address)s is not associated with instance %(id)s."
msgstr "Floating ip %(address)s is not associated."

#: nova/api/openstack/compute/contrib/floating_ips_bulk.py:118
#: nova/api/openstack/compute/contrib/services.py:124
#: nova/api/openstack/compute/plugins/v3/floating_ips_bulk.py:123
#: nova/api/openstack/compute/plugins/v3/services.py:114
msgid "Unknown action"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips_bulk.py:146
#: nova/api/openstack/compute/plugins/v3/floating_ips_bulk.py:146
#: nova/cmd/manage.py:423
#, python-format
msgid "/%s should be specified as single address(es) not in cidr format"
msgstr ""

#: nova/api/openstack/compute/contrib/fping.py:52
#: nova/api/openstack/compute/plugins/v3/fping.py:50
#, fuzzy
msgid "fping utility is not found."
msgstr "floating ip not found"

#: nova/api/openstack/compute/contrib/hosts.py:122
#, python-format
msgid "Invalid update setting: '%s'"
msgstr "Invalid update setting: '%s'"

#: nova/api/openstack/compute/contrib/hosts.py:125
#, python-format
msgid "Invalid status: '%s'"
msgstr "Invalid status: '%s'"

#: nova/api/openstack/compute/contrib/hosts.py:127
#, python-format
msgid "Invalid mode: '%s'"
msgstr "Invalid mode: '%s'"

#: nova/api/openstack/compute/contrib/hosts.py:129
msgid "'status' or 'maintenance_mode' needed for host update"
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:145
#: nova/api/openstack/compute/plugins/v3/hosts.py:136
#, fuzzy, python-format
msgid "Putting host %(host_name)s in maintenance mode %(mode)s."
msgstr "Putting host %(host)s in maintenance mode %(mode)s."

#: nova/api/openstack/compute/contrib/hosts.py:151
#: nova/api/openstack/compute/plugins/v3/hosts.py:142
#, fuzzy
msgid "Virt driver does not implement host maintenance mode."
msgstr "Virt driver does not implement uptime function."

#: nova/api/openstack/compute/contrib/hosts.py:168
#: nova/api/openstack/compute/plugins/v3/hosts.py:158
#, fuzzy, python-format
msgid "Enabling host %s."
msgstr "Calling setter %s"

#: nova/api/openstack/compute/contrib/hosts.py:170
#: nova/api/openstack/compute/plugins/v3/hosts.py:160
#, fuzzy, python-format
msgid "Disabling host %s."
msgstr "Updating host stats"

#: nova/api/openstack/compute/contrib/hosts.py:175
#: nova/api/openstack/compute/plugins/v3/hosts.py:165
#, fuzzy
msgid "Virt driver does not implement host disabled status."
msgstr "Virt driver does not implement uptime function."

#: nova/api/openstack/compute/contrib/hosts.py:193
#: nova/api/openstack/compute/plugins/v3/hosts.py:183
#, fuzzy
msgid "Virt driver does not implement host power management."
msgstr "Virt driver does not implement uptime function."

#: nova/api/openstack/compute/contrib/hosts.py:279
#: nova/api/openstack/compute/plugins/v3/hosts.py:277
msgid "Describe-resource is admin only functionality"
msgstr "Describe-resource is admin only functionality"

#: nova/api/openstack/compute/contrib/hypervisors.py:105
#: nova/api/openstack/compute/contrib/hypervisors.py:116
#: nova/api/openstack/compute/plugins/v3/hypervisors.py:101
#: nova/api/openstack/compute/plugins/v3/hypervisors.py:113
#, python-format
msgid "Hypervisor with ID '%s' could not be found."
msgstr "Hypervisor with ID '%s' could not be found."

#: nova/api/openstack/compute/contrib/hypervisors.py:124
#: nova/api/openstack/compute/plugins/v3/hypervisors.py:121
msgid "Virt driver does not implement uptime function."
msgstr "Virt driver does not implement uptime function."

#: nova/api/openstack/compute/contrib/hypervisors.py:139
#: nova/api/openstack/compute/contrib/hypervisors.py:148
#: nova/api/openstack/compute/plugins/v3/hypervisors.py:137
#: nova/api/openstack/compute/plugins/v3/hypervisors.py:147
#, python-format
msgid "No hypervisor matching '%s' could be found."
msgstr "No hypervisor matching '%s' could be found."

#: nova/api/openstack/compute/contrib/instance_usage_audit_log.py:56
#: nova/api/openstack/compute/plugins/v3/instance_usage_audit_log.py:59
#, python-format
msgid "Invalid timestamp for date %s"
msgstr "Invalid timestamp for date %s"

#: nova/api/openstack/compute/contrib/keypairs.py:87
#: nova/api/openstack/compute/plugins/v3/keypairs.py:90
msgid "Quota exceeded, too many key pairs."
msgstr "Quota exceeded, too many key pairs."

#: nova/api/openstack/compute/contrib/multinic.py:48
msgid "Missing 'networkId' argument for addFixedIp"
msgstr "Missing 'networkId' argument for addFixedIp"

#: nova/api/openstack/compute/contrib/multinic.py:69
msgid "Missing 'address' argument for removeFixedIp"
msgstr "Missing 'address' argument for removeFixedIp"

#: nova/api/openstack/compute/contrib/networks_associate.py:39
#: nova/api/openstack/compute/contrib/networks_associate.py:55
#: nova/api/openstack/compute/contrib/networks_associate.py:73
#: nova/api/openstack/compute/contrib/os_networks.py:106
#: nova/api/openstack/compute/contrib/os_networks.py:121
#: nova/api/openstack/compute/contrib/os_networks.py:133
#: nova/api/openstack/compute/contrib/os_tenant_networks.py:106
#: nova/api/openstack/compute/contrib/os_tenant_networks.py:136
#: nova/api/openstack/compute/plugins/v3/networks.py:102
#: nova/api/openstack/compute/plugins/v3/networks.py:117
#: nova/api/openstack/compute/plugins/v3/networks.py:132
#: nova/api/openstack/compute/plugins/v3/networks_associate.py:41
#: nova/api/openstack/compute/plugins/v3/networks_associate.py:57
#: nova/api/openstack/compute/plugins/v3/networks_associate.py:75
#: nova/api/openstack/compute/plugins/v3/tenant_networks.py:100
#: nova/api/openstack/compute/plugins/v3/tenant_networks.py:132
msgid "Network not found"
msgstr "Network not found"

#: nova/api/openstack/compute/contrib/networks_associate.py:42
#: nova/api/openstack/compute/plugins/v3/networks_associate.py:44
msgid "Disassociate host is not implemented by the configured Network API"
msgstr ""

#: nova/api/openstack/compute/contrib/networks_associate.py:58
#: nova/api/openstack/compute/plugins/v3/networks_associate.py:60
msgid "Disassociate project is not implemented by the configured Network API"
msgstr ""

#: nova/api/openstack/compute/contrib/networks_associate.py:76
#: nova/api/openstack/compute/plugins/v3/networks_associate.py:78
msgid "Associate host is not implemented by the configured Network API"
msgstr ""

#: nova/api/openstack/compute/contrib/os_networks.py:109
#: nova/api/openstack/compute/plugins/v3/networks.py:105
msgid "Disassociate network is not implemented by the configured Network API"
msgstr ""

#: nova/api/openstack/compute/contrib/os_networks.py:145
#: nova/api/openstack/compute/plugins/v3/networks.py:144
msgid "Missing network in body"
msgstr "Missing network in body"

#: nova/api/openstack/compute/contrib/os_networks.py:149
#: nova/api/openstack/compute/plugins/v3/networks.py:148
msgid "Network label is required"
msgstr "Network label is required"

#: nova/api/openstack/compute/contrib/os_networks.py:153
#: nova/api/openstack/compute/plugins/v3/networks.py:152
msgid "Network cidr or cidr_v6 is required"
msgstr "Network cidr or cidr_v6 is required"

#: nova/api/openstack/compute/contrib/os_networks.py:162
#: nova/api/openstack/compute/plugins/v3/networks.py:161
#, python-format
msgid "%s is not a valid ip network"
msgstr ""

#: nova/api/openstack/compute/contrib/os_networks.py:195
#: nova/api/openstack/compute/plugins/v3/networks.py:191
msgid "VLAN support must be enabled"
msgstr ""

#: nova/api/openstack/compute/contrib/os_tenant_networks.py:160
#: nova/api/openstack/compute/plugins/v3/tenant_networks.py:155
#, fuzzy
msgid "No CIDR requested"
msgstr "Can not find requested image"

#: nova/api/openstack/compute/contrib/os_tenant_networks.py:166
#: nova/api/openstack/compute/plugins/v3/tenant_networks.py:161
msgid "Requested network does not contain enough (2+) usable hosts"
msgstr ""

#: nova/api/openstack/compute/contrib/os_tenant_networks.py:170
#: nova/api/openstack/compute/plugins/v3/tenant_networks.py:165
msgid "CIDR is malformed."
msgstr ""

#: nova/api/openstack/compute/contrib/os_tenant_networks.py:173
#: nova/api/openstack/compute/plugins/v3/tenant_networks.py:168
#, fuzzy
msgid "Address could not be converted."
msgstr "Resource could not be found."

#: nova/api/openstack/compute/contrib/os_tenant_networks.py:181
#: nova/api/openstack/compute/plugins/v3/tenant_networks.py:176
#, fuzzy
msgid "Quota exceeded, too many networks."
msgstr "Quota exceeded, too many key pairs."

#: nova/api/openstack/compute/contrib/os_tenant_networks.py:194
#: nova/api/openstack/compute/plugins/v3/tenant_networks.py:189
#, fuzzy
msgid "Create networks failed"
msgstr "Create failed"

#: nova/api/openstack/compute/contrib/quota_classes.py:79
#: nova/api/openstack/compute/plugins/v3/quota_classes.py:83
msgid "quota_class_set not specified"
msgstr ""

#: nova/api/openstack/compute/contrib/quota_classes.py:94
#: nova/api/openstack/compute/contrib/quotas.py:167
#: nova/api/openstack/compute/plugins/v3/quota_classes.py:98
#, python-format
msgid "Bad key(s) %s in quota_set"
msgstr ""

#: nova/api/openstack/compute/contrib/quotas.py:70
#: nova/api/openstack/compute/plugins/v3/quota_sets.py:53
#, python-format
msgid "Quota limit %(limit)s for %(resource)s must be -1 or greater."
msgstr ""

#: nova/api/openstack/compute/contrib/quotas.py:79
#: nova/api/openstack/compute/plugins/v3/quota_sets.py:62
#, python-format
msgid ""
"Quota limit %(limit)s for %(resource)s must be greater than or equal to "
"already used and reserved %(minimum)s."
msgstr ""

#: nova/api/openstack/compute/contrib/quotas.py:85
#: nova/api/openstack/compute/plugins/v3/quota_sets.py:68
#, python-format
msgid ""
"Quota limit %(limit)s for %(resource)s must be less than or equal to "
"%(maximum)s."
msgstr ""

#: nova/api/openstack/compute/contrib/quotas.py:146
msgid "quota_set not specified"
msgstr ""

#: nova/api/openstack/compute/contrib/scheduler_hints.py:37
msgid "Malformed scheduler_hints attribute"
msgstr "Malformed scheduler_hints attribute"

#: nova/api/openstack/compute/contrib/security_group_default_rules.py:51
#: nova/api/openstack/compute/contrib/security_groups.py:259
#: nova/api/openstack/compute/plugins/v3/security_group_default_rules.py:60
#: nova/api/openstack/compute/plugins/v3/security_groups.py:257
msgid "Not enough parameters to build a valid rule."
msgstr "Not enough parameters to build a valid rule."

#: nova/api/openstack/compute/contrib/security_group_default_rules.py:55
#: nova/api/openstack/compute/plugins/v3/security_group_default_rules.py:64
#, fuzzy
msgid "This default rule already exists."
msgstr "This rule already exists in group %s"

#: nova/api/openstack/compute/contrib/security_group_default_rules.py:78
#, fuzzy
msgid "security group default rule not found"
msgstr "Security group with rule %(rule_id)s not found."

#: nova/api/openstack/compute/contrib/security_groups.py:134
#: nova/api/openstack/compute/plugins/v3/security_groups.py:109
msgid "The request body can't be empty"
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:138
#: nova/api/openstack/compute/plugins/v3/security_groups.py:113
#, python-format
msgid "Missing parameter %s"
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:267
#: nova/api/openstack/compute/plugins/v3/security_groups.py:265
#, fuzzy, python-format
msgid "Bad prefix for network in cidr %s"
msgstr "Bad prefix for to_global_ipv6: %s"

#: nova/api/openstack/compute/contrib/security_groups.py:355
#: nova/api/openstack/compute/plugins/v3/security_groups.py:370
msgid "Security group not specified"
msgstr "Security group not specified"

#: nova/api/openstack/compute/contrib/security_groups.py:359
#: nova/api/openstack/compute/plugins/v3/security_groups.py:374
msgid "Security group name cannot be empty"
msgstr "Security group name cannot be empty"

#: nova/api/openstack/compute/contrib/server_diagnostics.py:45
#: nova/api/openstack/compute/plugins/v3/server_diagnostics.py:53
msgid "Unable to get diagnostics, functionality not implemented"
msgstr ""

#: nova/api/openstack/compute/contrib/server_external_events.py:63
#, python-format
msgid "event entity requires key %(key)s"
msgstr ""

#: nova/api/openstack/compute/contrib/server_external_events.py:67
#, python-format
msgid "event entity contains unsupported items: %s"
msgstr ""

#: nova/api/openstack/compute/contrib/server_external_events.py:73
#, python-format
msgid "Invalid event status `%s'"
msgstr ""

#: nova/api/openstack/compute/contrib/server_external_events.py:96
#: nova/api/openstack/compute/plugins/v3/server_external_events.py:86
#, python-format
msgid "Creating event %(name)s:%(tag)s for instance %(instance_uuid)s"
msgstr ""

#: nova/api/openstack/compute/contrib/server_external_events.py:118
#: nova/api/openstack/compute/plugins/v3/server_external_events.py:108
msgid "No instances found for any event"
msgstr ""

#: nova/api/openstack/compute/contrib/server_groups.py:83
msgid "Conflicting policies configured!"
msgstr ""

#: nova/api/openstack/compute/contrib/server_groups.py:88
#, python-format
msgid "Invalid policies: %s"
msgstr ""

#: nova/api/openstack/compute/contrib/server_groups.py:93
msgid "Duplicate policies configured!"
msgstr ""

#: nova/api/openstack/compute/contrib/server_groups.py:98
msgid "the body is invalid."
msgstr ""

#: nova/api/openstack/compute/contrib/server_groups.py:107
#, python-format
msgid "'%s' is either missing or empty."
msgstr ""

#: nova/api/openstack/compute/contrib/server_groups.py:113
#, python-format
msgid "Invalid format for name: '%s'"
msgstr ""

#: nova/api/openstack/compute/contrib/server_groups.py:121
#, python-format
msgid "'%s' is not a list"
msgstr ""

#: nova/api/openstack/compute/contrib/server_groups.py:125
#, python-format
msgid "unsupported fields: %s"
msgstr ""

#: nova/api/openstack/compute/contrib/server_groups.py:202
#: nova/api/openstack/compute/plugins/v3/server_groups.py:139
msgid "Quota exceeded, too many server groups."
msgstr ""

#: nova/api/openstack/compute/contrib/server_start_stop.py:37
msgid "Instance not found"
msgstr "Instance not found"

#: nova/api/openstack/compute/contrib/services.py:100
#: nova/api/openstack/compute/plugins/v3/services.py:88
#, python-format
msgid "Service %s not found."
msgstr ""

#: nova/api/openstack/compute/contrib/services.py:143
msgid ""
"The string containing the reason for disabling the service contains "
"invalid characters or is too long."
msgstr ""

#: nova/api/openstack/compute/contrib/services.py:151
msgid "Invalid attribute in the request"
msgstr ""

#: nova/api/openstack/compute/contrib/services.py:153
#: nova/api/openstack/compute/plugins/v3/services.py:134
msgid "Missing disabled reason field"
msgstr ""

#: nova/api/openstack/compute/contrib/simple_tenant_usage.py:196
#: nova/api/openstack/compute/plugins/v3/simple_tenant_usage.py:198
msgid "Datetime is in invalid format"
msgstr ""

#: nova/api/openstack/compute/contrib/simple_tenant_usage.py:215
#: nova/api/openstack/compute/plugins/v3/simple_tenant_usage.py:217
msgid "Invalid start time. The start time cannot occur after the end time."
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:76
#, python-format
msgid "vol=%s"
msgstr "vol=%s"

#: nova/api/openstack/compute/contrib/volumes.py:110
#, python-format
msgid "Delete volume with id: %s"
msgstr "Delete volume with id: %s"

#: nova/api/openstack/compute/contrib/volumes.py:142
msgid "volume not specified"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:251
#: nova/api/openstack/compute/contrib/volumes.py:403
#: nova/api/openstack/compute/plugins/v3/volumes.py:247
#: nova/api/openstack/compute/plugins/v3/volumes.py:381
#, python-format
msgid "Instance %s is not attached."
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:262
#: nova/api/openstack/compute/contrib/volumes.py:381
#: nova/api/openstack/compute/contrib/volumes.py:429
#: nova/api/openstack/compute/plugins/v3/volumes.py:258
#: nova/api/openstack/compute/plugins/v3/volumes.py:410
#, python-format
msgid "volume_id not found: %s"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:272
#, fuzzy, python-format
msgid "Bad volumeId format: volumeId is not in proper format (%s)"
msgstr "Bad port format: port uuid is not in proper format (%s)"

#: nova/api/openstack/compute/contrib/volumes.py:283
#: nova/api/openstack/compute/contrib/volumes.py:341
msgid "volumeAttachment not specified"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:288
#: nova/api/openstack/compute/contrib/volumes.py:350
msgid "volumeId must be specified."
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:294
#, python-format
msgid "Attach volume %(volume_id)s to instance %(server_id)s at %(device)s"
msgstr "Attach volume %(volume_id)s to instance %(server_id)s at %(device)s"

#: nova/api/openstack/compute/contrib/volumes.py:412
#: nova/api/openstack/compute/plugins/v3/extended_volumes.py:185
#: nova/api/openstack/compute/plugins/v3/volumes.py:390
msgid "Can't detach root device volume"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:535
msgid "snapshot not specified"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:541
#, python-format
msgid "Create snapshot from volume %s"
msgstr "Create snapshot from volume %s"

#: nova/api/openstack/compute/contrib/volumes.py:548
#, fuzzy, python-format
msgid "Invalid value '%s' for force."
msgstr "Invalid value '%s' for force. "

#: nova/api/openstack/compute/plugins/v3/aggregates.py:165
#: nova/api/openstack/compute/plugins/v3/aggregates.py:169
#, python-format
msgid "Cannot remove host %(host)s in aggregate %(id)s"
msgstr "Cannot remove host %(host)s in aggregate %(id)s"

#: nova/api/openstack/compute/plugins/v3/cells.py:191
#, python-format
msgid "Cell %s doesn't exist."
msgstr ""

#: nova/api/openstack/compute/plugins/v3/console_auth_tokens.py:40
msgid "token not provided"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/extended_volumes.py:97
#: nova/api/openstack/compute/plugins/v3/volumes.py:356
msgid "The volume was either invalid or not attached to the instance."
msgstr ""

#: nova/api/openstack/compute/plugins/v3/extended_volumes.py:176
#: nova/api/openstack/compute/plugins/v3/extended_volumes.py:202
#, python-format
msgid "Volume %(volume_id)s is not attached to the instance %(server_id)s"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/fixed_ips.py:87
#, python-format
msgid "Fixed IP %s not valid"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/flavors.py:96
#, python-format
msgid "Invalid min_ram filter [%s]"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/floating_ip_dns.py:122
msgid "you can not pass project if the scope is private"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/floating_ip_dns.py:125
msgid "you can not pass av_zone if the scope is public"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/floating_ip_dns.py:232
msgid "Unable to update dns domain"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/instance_actions.py:73
#, python-format
msgid "Action %s not found"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/networks.py:181
#: nova/api/openstack/compute/plugins/v3/tenant_networks.py:141
msgid "Missing request body"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/pause_server.py:57
#: nova/api/openstack/compute/plugins/v3/pause_server.py:79
msgid "Virt driver does not implement pause function."
msgstr ""

#: nova/api/openstack/compute/plugins/v3/servers.py:416
msgid "Unknown argument: port"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/servers.py:419
#, python-format
msgid ""
"Specified Fixed IP '%(addr)s' cannot be used with port '%(port)s': port "
"already has a Fixed IP allocated."
msgstr ""

#: nova/api/openstack/compute/plugins/v3/servers.py:716
msgid "host_id cannot be updated."
msgstr ""

#: nova/api/validation/validators.py:107
#, python-format
msgid "Invalid input for field/attribute %(path)s. Value: %(value)s. %(message)s"
msgstr ""

#: nova/cells/messaging.py:366 nova/cells/messaging.py:374
#, python-format
msgid "destination is %(target_cell)s but routing_path is %(routing_path)s"
msgstr ""

#: nova/cells/messaging.py:386
#, python-format
msgid "Unknown %(cell_type)s when routing to %(target_cell)s"
msgstr ""

#: nova/cells/messaging.py:437
#, fuzzy, python-format
msgid "Failed to send message to cell: %(next_hop)s: %(exc)s"
msgstr "Failed to load extension %(ext_factory)s: %(exc)s"

#: nova/cells/messaging.py:554
#, python-format
msgid "Error waiting for responses from neighbor cells: %(exc)s"
msgstr ""

#: nova/cells/messaging.py:665
#, fuzzy, python-format
msgid "Unknown method '%(method)s' in compute API"
msgstr "Casted '%(method)s' to compute '%(host)s'"

#: nova/cloudpipe/pipelib.py:47
msgid "Flavor for vpn instances"
msgstr ""

#: nova/cloudpipe/pipelib.py:50
msgid "Template for cloudpipe instance boot script"
msgstr "Template for cloudpipe instance boot script"

#: nova/cloudpipe/pipelib.py:53
msgid "Network to push into openvpn config"
msgstr "Network to push into openvpn config"

#: nova/cloudpipe/pipelib.py:56
msgid "Netmask to push into openvpn config"
msgstr "Netmask to push into openvpn config"

#: nova/cmd/manage.py:220
msgid ""
"The above error may show that the database has not been created.\n"
"Please create a database using 'nova-manage db sync' before running this "
"command."
msgstr ""

#: nova/cmd/manage.py:261
msgid "Quota limit must be -1 or greater."
msgstr "Quota limit must be -1 or greater."

#: nova/cmd/manage.py:265
#, python-format
msgid "Quota limit must be greater than %s."
msgstr ""

#: nova/cmd/manage.py:268
#, python-format
msgid "Quota limit must be less than %s."
msgstr ""

#: nova/cmd/manage.py:277
#, python-format
msgid "%(key)s is not a valid quota key. Valid options are: %(options)s."
msgstr ""

#: nova/cmd/manage.py:283
msgid "Quota"
msgstr ""

#: nova/cmd/manage.py:284
msgid "Limit"
msgstr ""

#: nova/cmd/manage.py:285
msgid "In Use"
msgstr ""

#: nova/cmd/manage.py:286
#, fuzzy
msgid "Reserved"
msgstr "received %s"

#: nova/cmd/manage.py:329 nova/cmd/manage.py:404 nova/cmd/manage.py:743
#: nova/cmd/manage.py:757 nova/cmd/manage.py:827
#, fuzzy, python-format
msgid "error: %s"
msgstr "DB error: %s"

#: nova/cmd/manage.py:337
#, fuzzy
msgid "network"
msgstr "Reset network"

#: nova/cmd/manage.py:338
#, fuzzy
msgid "IP address"
msgstr "start address"

#: nova/cmd/manage.py:339
msgid "hostname"
msgstr ""

#: nova/cmd/manage.py:340 nova/cmd/manage.py:883
msgid "host"
msgstr ""

#: nova/cmd/manage.py:352 nova/cmd/manage.py:376
#, fuzzy
msgid "No fixed IP found."
msgstr "Zero fixed ips could be found."

#: nova/cmd/manage.py:368
#, fuzzy, python-format
msgid "WARNING: fixed ip %s allocated to missing instance"
msgstr "No fixed ips associated to instance"

#: nova/cmd/manage.py:430
#, python-format
msgid ""
"Too many IP addresses will be generated.  Please increase /%s to reduce "
"the number generated."
msgstr ""

#: nova/cmd/manage.py:481
#, fuzzy
msgid "No floating IP addresses have been defined."
msgstr "Floating ip %(address)s already exists."

#: nova/cmd/manage.py:500
msgid ""
"ERROR: Network commands are not supported when using the Neutron API.  "
"Use python-neutronclient instead."
msgstr ""

#: nova/cmd/manage.py:557
msgid "id"
msgstr "id"

#: nova/cmd/manage.py:558
msgid "IPv4"
msgstr "IPv4"

#: nova/cmd/manage.py:559
msgid "IPv6"
msgstr "IPv6"

#: nova/cmd/manage.py:560
msgid "start address"
msgstr "start address"

#: nova/cmd/manage.py:561
msgid "DNS1"
msgstr "DNS1"

#: nova/cmd/manage.py:562
msgid "DNS2"
msgstr "DNS2"

#: nova/cmd/manage.py:563
msgid "VlanID"
msgstr "VlanID"

#: nova/cmd/manage.py:564 nova/cmd/manage.py:671
msgid "project"
msgstr "project"

#: nova/cmd/manage.py:565
msgid "uuid"
msgstr "uuid"

#: nova/cmd/manage.py:572
#, fuzzy
msgid "No networks found"
msgstr "Network not found"

#: nova/cmd/manage.py:591
msgid "Please specify either fixed_range or uuid"
msgstr ""

#: nova/cmd/manage.py:596
msgid "UUID is required to delete Neutron Networks"
msgstr ""

#: nova/cmd/manage.py:599
msgid "Deleting by fixed_range is not supported with the NeutronManager"
msgstr ""

#: nova/cmd/manage.py:663
#, fuzzy
msgid "instance"
msgstr "stop instance"

#: nova/cmd/manage.py:664
msgid "node"
msgstr ""

#: nova/cmd/manage.py:665
msgid "type"
msgstr ""

#: nova/cmd/manage.py:666
msgid "state"
msgstr ""

#: nova/cmd/manage.py:667
msgid "launched"
msgstr ""

#: nova/cmd/manage.py:668
msgid "image"
msgstr ""

#: nova/cmd/manage.py:669
msgid "kernel"
msgstr ""

#: nova/cmd/manage.py:670
msgid "ramdisk"
msgstr ""

#: nova/cmd/manage.py:672
msgid "user"
msgstr ""

#: nova/cmd/manage.py:673 nova/cmd/manage.py:884
msgid "zone"
msgstr ""

#: nova/cmd/manage.py:674
msgid "index"
msgstr ""

#: nova/cmd/manage.py:718
msgid "Binary"
msgstr ""

#: nova/cmd/manage.py:719
msgid "Host"
msgstr ""

#: nova/cmd/manage.py:720
msgid "Zone"
msgstr ""

#: nova/cmd/manage.py:721
msgid "Status"
msgstr ""

#: nova/cmd/manage.py:722
msgid "State"
msgstr ""

#: nova/cmd/manage.py:723
msgid "Updated_At"
msgstr ""

#: nova/cmd/manage.py:745
#, fuzzy, python-format
msgid "Service %(service)s on host %(host)s enabled."
msgstr "Service %(service_id)s could not be found."

#: nova/cmd/manage.py:759
#, fuzzy, python-format
msgid "Service %(service)s on host %(host)s disabled."
msgstr "Service %(service_id)s could not be found."

#: nova/cmd/manage.py:831
#, fuzzy
msgid "An unexpected error has occurred."
msgstr "Unexpected error: %s"

#: nova/cmd/manage.py:832
msgid "[Result]"
msgstr ""

#: nova/cmd/manage.py:836
msgid "HOST"
msgstr ""

#: nova/cmd/manage.py:837
#, fuzzy
msgid "PROJECT"
msgstr "project"

#: nova/cmd/manage.py:838
msgid "cpu"
msgstr ""

#: nova/cmd/manage.py:839
msgid "mem(mb)"
msgstr ""

#: nova/cmd/manage.py:840
msgid "hdd"
msgstr ""

#: nova/cmd/manage.py:923
msgid "Must supply a positive value for max_rows"
msgstr ""

#: nova/cmd/manage.py:942
#, python-format
msgid "Deleted %(records)d records from table '%(table_name)s'."
msgstr ""

#: nova/cmd/manage.py:946
#, python-format
msgid ""
"There are %(records)d records in the '%(table_name)s' table where the "
"uuid or instance_uuid column is NULL. Run this command again with the "
"--delete option after you have backed up any necessary data."
msgstr ""

#: nova/cmd/manage.py:954
msgid "There were no records found where instance_uuid was NULL."
msgstr ""

#: nova/cmd/manage.py:1013
#, fuzzy, python-format
msgid "Hypervisor: %s"
msgstr "hyperv vm state: %s"

#: nova/cmd/manage.py:1062
#, python-format
msgid "Line %(linenum)d : %(line)s"
msgstr ""

#: nova/cmd/manage.py:1065
msgid "No errors in logfiles!"
msgstr ""

#: nova/cmd/manage.py:1079
msgid "Unable to find system log file!"
msgstr ""

#: nova/cmd/manage.py:1083
#, python-format
msgid "Last %s nova syslog entries:-"
msgstr ""

#: nova/cmd/manage.py:1092
msgid "No nova entries in syslog!"
msgstr ""

#: nova/cmd/manage.py:1109
#, python-format
msgid "Invalid broker_hosts value: %s. It should be in hostname:port format"
msgstr ""

#: nova/cmd/manage.py:1115
#, python-format
msgid "Invalid port value: %s. It should be an integer"
msgstr ""

#: nova/cmd/manage.py:1128
#, python-format
msgid "Invalid port value: %s. Should be an integer"
msgstr ""

#: nova/cmd/manage.py:1294
#, python-format
msgid "Could not read %s. Re-running with sudo"
msgstr ""

#: nova/cmd/manage.py:1298
msgid "sudo failed, continuing as if nothing happened"
msgstr ""

#: nova/cmd/manage.py:1300
msgid "Please re-run nova-manage as root."
msgstr ""

#: nova/cmd/manage.py:1347
msgid "Command failed, please check log for more info"
msgstr ""

#: nova/compute/api.py:419
msgid "Cannot run any more instances of this type."
msgstr "Cannot run any more instances of this type."

#: nova/compute/api.py:426
#, python-format
msgid "Can only run %s more instances of this type."
msgstr "Can only run %s more instances of this type."

#: nova/compute/api.py:463
msgid "Metadata type should be dict."
msgstr ""

#: nova/compute/api.py:485
msgid "Metadata property key greater than 255 characters"
msgstr "Metadata property key greater than 255 characters"

#: nova/compute/api.py:488
msgid "Metadata property value greater than 255 characters"
msgstr "Metadata property value greater than 255 characters"

#: nova/compute/api.py:717
#, python-format
msgid "The volume cannot be assigned the same device name as the root device %s"
msgstr ""

#: nova/compute/api.py:746
#, fuzzy
msgid "Cannot attach one or more volumes to multiple instances"
msgstr "Unable to attach boot volume to instance %s"

#: nova/compute/api.py:786
msgid "The requested availability zone is not available"
msgstr ""

#: nova/compute/api.py:929
msgid "Quota exceeded, too many servers in group"
msgstr ""

#: nova/compute/api.py:1036
msgid "Server group scheduler hint must be a UUID."
msgstr ""

#: nova/compute/api.py:1235
msgid ""
"Images with destination_type 'volume' need to have a non-zero size "
"specified"
msgstr ""

#: nova/compute/api.py:1267
msgid "More than one swap drive requested."
msgstr ""

#: nova/compute/api.py:1413
msgid ""
"Unable to launch multiple instances with a single configured port ID. "
"Please launch your instance one by one with different ports."
msgstr ""

#: nova/compute/api.py:1423
msgid "max_count cannot be greater than 1 if an fixed_ip is specified."
msgstr ""

#: nova/compute/api.py:1790
#, python-format
msgid "Ignoring volume cleanup failure due to %s"
msgstr "Ignoring volume cleanup failure due to %s"

#: nova/compute/api.py:2217
#, python-format
msgid "snapshot for %s"
msgstr "snapshot for %s"

#: nova/compute/api.py:2562
msgid "Resize to zero disk flavor is not allowed."
msgstr ""

#: nova/compute/api.py:2779
msgid "Cannot rescue a volume-backed instance"
msgstr ""

#: nova/compute/api.py:3026
msgid "Volume must be attached in order to detach."
msgstr "Volume must be attached in order to detach."

#: nova/compute/api.py:3046
msgid "Old volume is attached to a different instance."
msgstr ""

#: nova/compute/api.py:3049
msgid "New volume must be detached in order to swap."
msgstr ""

#: nova/compute/api.py:3052
msgid "New volume must be the same size or larger."
msgstr ""

#: nova/compute/api.py:3526
msgid "Host aggregate is not empty"
msgstr ""

#: nova/compute/api.py:3593
#, python-format
msgid "Unexpected aggregate action %s"
msgstr ""

#: nova/compute/api.py:3611
#, python-format
msgid "Host already in availability zone %s"
msgstr ""

#: nova/compute/api.py:3694
msgid "Keypair name contains unsafe characters"
msgstr "Keypair name contains unsafe characters"

#: nova/compute/api.py:3700
msgid "Keypair name must be string and between 1 and 255 characters long"
msgstr ""

#: nova/compute/api.py:3789
#, python-format
msgid "Security group %s is not a string or unicode"
msgstr "Security group %s is not a string or unicode"

#: nova/compute/api.py:3799
#, python-format
msgid ""
"Value (%(value)s) for parameter Group%(property)s is invalid. Content "
"limited to '%(allowed)s'."
msgstr ""

#: nova/compute/api.py:3820
msgid "Quota exceeded, too many security groups."
msgstr "Quota exceeded, too many security groups."

#: nova/compute/api.py:3823
#, python-format
msgid "Create Security Group %s"
msgstr "Create Security Group %s"

#: nova/compute/api.py:3835
#, python-format
msgid "Security group %s already exists"
msgstr "Security group %s already exists"

#: nova/compute/api.py:3848
#, fuzzy, python-format
msgid "Unable to update system group '%s'"
msgstr "Unable to destroy vbd %s"

#: nova/compute/api.py:3910
#, fuzzy, python-format
msgid "Unable to delete system group '%s'"
msgstr "Unable to destroy vbd %s"

#: nova/compute/api.py:3915
msgid "Security group is still in use"
msgstr "Security group is still in use"

#: nova/compute/api.py:3928
#, python-format
msgid "Delete security group %s"
msgstr "Delete security group %s"

#: nova/compute/api.py:4004
#, python-format
msgid "Rule (%s) not found"
msgstr "Rule (%s) not found"

#: nova/compute/api.py:4020
msgid "Quota exceeded, too many security group rules."
msgstr "Quota exceeded, too many security group rules."

#: nova/compute/api.py:4023
#, python-format
msgid ""
"Security group %(name)s added %(protocol)s ingress "
"(%(from_port)s:%(to_port)s)"
msgstr ""

#: nova/compute/api.py:4038
#, python-format
msgid ""
"Security group %(name)s removed %(protocol)s ingress "
"(%(from_port)s:%(to_port)s)"
msgstr ""

#: nova/compute/api.py:4090
msgid "Security group id should be integer"
msgstr "Security group id should be integer"

#: nova/compute/claims.py:154
#, python-format
msgid "Attempting claim: memory %(memory_mb)d MB, disk %(disk_gb)d GB"
msgstr ""

#: nova/compute/claims.py:169
msgid "Claim successful"
msgstr ""

#: nova/compute/claims.py:172
msgid "memory"
msgstr ""

#: nova/compute/claims.py:181
msgid "disk"
msgstr ""

#: nova/compute/claims.py:197 nova/compute/claims.py:285
msgid "Claim pci failed."
msgstr ""

#: nova/compute/claims.py:214
msgid "Requested instance NUMA topology cannot fit the given host NUMA topology"
msgstr ""

#: nova/compute/claims.py:223
#, fuzzy, python-format
msgid "Total %(type)s: %(total)d %(unit)s, used: %(used).02f %(unit)s"
msgstr "Total VCPUs: %(total_vcpus)d, used: %(used_vcpus)d"

#: nova/compute/claims.py:230
#, fuzzy, python-format
msgid "%(type)s limit not specified, defaulting to unlimited"
msgstr "Disk limit not specified, defaulting to unlimited"

#: nova/compute/claims.py:237
#, fuzzy, python-format
msgid "%(type)s limit: %(limit).02f %(unit)s, free: %(free).02f %(unit)s"
msgstr "Disk limit: %(disk_gb_limit)d GB, free: %(free_disk_gb)d GB"

#: nova/compute/claims.py:243
#, python-format
msgid "Free %(type)s %(free).02f %(unit)s < requested %(requested)d %(unit)s"
msgstr ""

#: nova/compute/flavors.py:116
msgid "Flavor names can only contain printable characters and horizontal spaces."
msgstr ""

#: nova/compute/flavors.py:126
msgid "id cannot contain leading and/or trailing whitespace(s)"
msgstr ""

#: nova/compute/flavors.py:136
msgid ""
"Flavor id can only contain letters from A-Z (both cases), periods, "
"dashes, underscores and spaces."
msgstr ""

#: nova/compute/flavors.py:162
#, python-format
msgid "'rxtx_factor' argument must be a float between 0 and %g"
msgstr ""

#: nova/compute/flavors.py:173
msgid "is_public must be a boolean"
msgstr ""

#: nova/compute/flavors.py:354
msgid ""
"Key Names can only contain alphanumeric characters, periods, dashes, "
"underscores, colons and spaces."
msgstr ""

#: nova/compute/manager.py:531
msgid "Instance event failed"
msgstr ""

#: nova/compute/manager.py:638
#, python-format
msgid "%s is not a valid node managed by this compute host."
msgstr ""

#: nova/compute/manager.py:1343 nova/compute/manager.py:2240
msgid "Success"
msgstr ""

#: nova/compute/manager.py:1367
msgid "Instance disappeared before we could start it"
msgstr ""

#: nova/compute/manager.py:1394
msgid "Anti-affinity instance group policy was violated."
msgstr ""

#: nova/compute/manager.py:1490
msgid "Instance disappeared during build"
msgstr ""

#: nova/compute/manager.py:1646 nova/compute/manager.py:2045
msgid "Starting instance..."
msgstr "Starting instance..."

#: nova/compute/manager.py:2196
#, python-format
msgid "Failed to allocate the network(s) with error %s, not rescheduling."
msgstr ""

#: nova/compute/manager.py:2206 nova/compute/manager.py:2263
msgid "Failed to allocate the network(s), not rescheduling."
msgstr ""

#: nova/compute/manager.py:2298
msgid "Failure prepping block device."
msgstr ""

#: nova/compute/manager.py:2319
msgid "Could not clean up failed build, not rescheduling"
msgstr ""

#: nova/compute/manager.py:2417
#, python-format
msgid "%(action_str)s instance"
msgstr "%(action_str)s instance"

#: nova/compute/manager.py:2782
msgid "Rebuilding instance"
msgstr "Rebuilding instance"

#: nova/compute/manager.py:2795
msgid "Invalid state of instance files on shared storage"
msgstr ""

#: nova/compute/manager.py:2949
msgid "Rebooting instance"
msgstr "Rebooting instance"

#: nova/compute/manager.py:3090
msgid "instance snapshotting"
msgstr "instance snapshotting"

#: nova/compute/manager.py:3134
msgid "Image not found during snapshot"
msgstr ""

#: nova/compute/manager.py:3219
#, python-format
msgid "Failed to set admin password. Instance %s is not running"
msgstr "Failed to set admin password. Instance %s is not running"

#: nova/compute/manager.py:3226
msgid "Root password set"
msgstr "Root password set"

#: nova/compute/manager.py:3237
#, fuzzy
msgid "set_admin_password is not implemented by this driver or guest instance."
msgstr "set_admin_password is not implemented by this driver."

#: nova/compute/manager.py:3252
msgid "error setting admin password"
msgstr "error setting admin password"

#: nova/compute/manager.py:3274
#, python-format
msgid "injecting file to %s"
msgstr ""

#: nova/compute/manager.py:3312
msgid "Rescuing"
msgstr "Rescuing"

#: nova/compute/manager.py:3339
#, fuzzy, python-format
msgid "Driver Error: %s"
msgstr "DB error: %s"

#: nova/compute/manager.py:3362
msgid "Unrescuing"
msgstr "Unrescuing"

#: nova/compute/manager.py:3675
#, fuzzy
msgid "Instance has no source host"
msgstr "Instance has no volume."

#: nova/compute/manager.py:3681
msgid "destination same as source!"
msgstr "destination same as source!"

#: nova/compute/manager.py:3698
msgid "Migrating"
msgstr "Migrating"

#: nova/compute/manager.py:4037
msgid "Pausing"
msgstr "Pausing"

#: nova/compute/manager.py:4054
msgid "Unpausing"
msgstr "Unpausing"

#: nova/compute/manager.py:4093 nova/compute/manager.py:4110
msgid "Retrieving diagnostics"
msgstr "Retrieving diagnostics"

#: nova/compute/manager.py:4149
msgid "Resuming"
msgstr "Resuming"

#: nova/compute/manager.py:4384
msgid "Get console output"
msgstr "Get console output"

#: nova/compute/manager.py:4628
#, python-format
msgid "Attaching volume %(volume_id)s to %(mountpoint)s"
msgstr "Attaching volume %(volume_id)s to %(mountpoint)s"

#: nova/compute/manager.py:4653
#, python-format
msgid "Detach volume %(volume_id)s from mountpoint %(mp)s"
msgstr "Detach volume %(volume_id)s from mountpoint %(mp)s"

#: nova/compute/manager.py:4880
#, python-format
msgid "Port %s is not attached"
msgstr ""

#: nova/compute/manager.py:5508
#, python-format
msgid "Instance %s not found"
msgstr ""

#: nova/compute/manager.py:5513
msgid "In ERROR state"
msgstr "In ERROR state"

#: nova/compute/manager.py:5541
#, fuzzy, python-format
msgid "In states %(vm_state)s/%(task_state)s, not RESIZED/None"
msgstr "In states %(vm_state)s/%(task_state)s, notRESIZED/None"

#: nova/compute/manager.py:6062
#, fuzzy, python-format
msgid "Deleting orphan compute node %s"
msgstr "Loading compute driver '%s'"

#: nova/compute/manager.py:6128
msgid "Failed to power off instance"
msgstr ""

#: nova/compute/manager.py:6148
#, python-format
msgid "Unrecognized value '%s' for CONF.running_deleted_instance_action"
msgstr ""

#: nova/compute/resource_tracker.py:314
msgid "Auditing locally available compute resources"
msgstr ""

#: nova/compute/resource_tracker.py:319
msgid ""
"Virt driver does not support 'get_available_resource'  Compute tracking "
"is disabled."
msgstr ""
"Virt driver does not support 'get_available_resource'  Compute tracking "
"is disabled."

#: nova/compute/resource_tracker.py:514
#, python-format
msgid ""
"Total physical ram (MB): %(pram)s, total allocated virtual ram (MB): "
"%(vram)s"
msgstr ""

#: nova/compute/resource_tracker.py:518
#, python-format
msgid ""
"Total physical disk (GB): %(pdisk)s, total allocated virtual disk (GB): "
"%(vdisk)s"
msgstr ""

#: nova/compute/resource_tracker.py:525
#, python-format
msgid "Total usable vcpus: %(tcpu)s, total allocated vcpus: %(ucpu)s"
msgstr ""

#: nova/compute/resource_tracker.py:529
msgid "Free VCPU information unavailable"
msgstr "Free VCPU information unavailable"

#: nova/compute/resource_tracker.py:532
#, python-format
msgid "PCI stats: %s"
msgstr ""

#: nova/compute/resource_tracker.py:598
#, fuzzy, python-format
msgid "Updating from migration %s"
msgstr "Starting finish_migration"

#: nova/compute/resource_tracker.py:797
#, python-format
msgid "Missing keys: %s"
msgstr "Missing keys: %s"

#: nova/compute/rpcapi.py:61
msgid "No compute host specified"
msgstr "No compute host specified"

#: nova/compute/rpcapi.py:63
#, python-format
msgid "Unable to find host for Instance %s"
msgstr "Unable to find host for Instance %s"

#: nova/compute/stats.py:50
msgid "Unexpected type adding stats"
msgstr ""

#: nova/compute/monitors/__init__.py:175
#, python-format
msgid ""
"Excluding monitor %(monitor_name)s due to metric name overlap; "
"overlapping metrics: %(overlap)s"
msgstr ""

#: nova/compute/monitors/__init__.py:183
#, python-format
msgid "Monitor %(monitor_name)s cannot be used: %(ex)s"
msgstr ""

#: nova/conductor/manager.py:543
msgid "No valid host found for cold migrate"
msgstr ""

#: nova/conductor/manager.py:545
msgid "No valid host found for resize"
msgstr ""

#: nova/conductor/manager.py:730
#, python-format
msgid "Unshelve attempted but the image %s cannot be found."
msgstr ""

#: nova/conductor/tasks/live_migrate.py:114
#, python-format
msgid ""
"Unable to migrate %(instance_uuid)s to %(dest)s: Lack of "
"memory(host:%(avail)s <= instance:%(mem_inst)s)"
msgstr ""
"Unable to migrate %(instance_uuid)s to %(dest)s: Lack of "
"memory(host:%(avail)s <= instance:%(mem_inst)s)"

#: nova/conductor/tasks/live_migrate.py:180
#, python-format
msgid ""
"Exceeded max scheduling retries %(max_retries)d for instance "
"%(instance_uuid)s during live migration"
msgstr ""

#: nova/console/websocketproxy.py:53
#, python-format
msgid ""
"We do not support scheme '%s' under Python < 2.7.4, please use http or "
"https"
msgstr ""

#: nova/console/websocketproxy.py:76
#, python-format
msgid "connect info: %s"
msgstr ""

#: nova/console/websocketproxy.py:81
#, python-format
msgid "connecting to: %(host)s:%(port)s"
msgstr ""

#: nova/console/websocketproxy.py:104
#, python-format
msgid "%(host)s:%(port)s: Target closed"
msgstr ""

#: nova/console/xvp.py:203
#, fuzzy
msgid "Failed to run xvp."
msgstr "Failed to resume server"

#: nova/consoleauth/manager.py:99
#, python-format
msgid "Received Token: %(token)s, %(token_dict)s"
msgstr ""

#: nova/consoleauth/manager.py:124
#, python-format
msgid "Checking Token: %(token)s, %(token_valid)s"
msgstr ""

#: nova/db/sqlalchemy/api.py:235
#, python-format
msgid "Unrecognized read_deleted value '%s'"
msgstr "Unrecognized read_deleted value '%s'"

#: nova/db/sqlalchemy/api.py:718
#, fuzzy, python-format
msgid "Invalid floating ip id %s in request"
msgstr "instance %s: rescued"

#: nova/db/sqlalchemy/api.py:966
#, fuzzy, python-format
msgid "Invalid floating IP %s in request"
msgstr "instance %s: rescued"

#: nova/db/sqlalchemy/api.py:1256
#, fuzzy, python-format
msgid "Invalid fixed IP Address %s in request"
msgstr "instance %s: rescued"

#: nova/db/sqlalchemy/api.py:1413
#, fuzzy, python-format
msgid "Invalid virtual interface address %s in request"
msgstr "instance %s: rescued"

#: nova/db/sqlalchemy/api.py:1507
#, python-format
msgid ""
"Unknown osapi_compute_unique_server_name_scope value: %s Flag must be "
"empty, \"global\" or \"project\""
msgstr ""

#: nova/db/sqlalchemy/api.py:1689
#, fuzzy, python-format
msgid "Invalid instance id %s in request"
msgstr "instance %s: rescued"

#: nova/db/sqlalchemy/api.py:2050
#, python-format
msgid "Invalid field name: %s"
msgstr ""

#: nova/db/sqlalchemy/api.py:2203
msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr ""

#: nova/db/sqlalchemy/api.py:2214
msgid "Sort direction size exceeds sort key size"
msgstr ""

#: nova/db/sqlalchemy/api.py:5483
#, python-format
msgid "Add metadata failed for aggregate %(id)s after %(retries)s retries"
msgstr ""

#: nova/db/sqlalchemy/api.py:5870
#, python-format
msgid "IntegrityError detected when archiving table %s"
msgstr ""

#: nova/db/sqlalchemy/migration.py:44
msgid "version should be an integer"
msgstr "version should be an integer"

#: nova/db/sqlalchemy/migration.py:72
msgid "Upgrade DB using Essex release first."
msgstr "Upgrade DB using Essex release first."

#: nova/db/sqlalchemy/utils.py:69
#, python-format
msgid "Missing column %(table)s.%(column)s in shadow table"
msgstr ""

#: nova/db/sqlalchemy/utils.py:75
#, python-format
msgid ""
"Different types in %(table)s.%(column)s and shadow table: %(c_type)s "
"%(shadow_c_type)s"
msgstr ""

#: nova/db/sqlalchemy/utils.py:84
#, python-format
msgid "Extra column %(table)s.%(column)s in shadow table"
msgstr ""

#: nova/db/sqlalchemy/utils.py:103
msgid "Specify `table_name` or `table` param"
msgstr ""

#: nova/db/sqlalchemy/utils.py:106
msgid "Specify only one param `table_name` `table`"
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/267_instance_uuid_non_nullable.py:55
#, python-format
msgid ""
"There are %(records)d records in the '%(table_name)s' table where the "
"uuid or instance_uuid column is NULL. These must be manually cleaned up "
"before the migration will pass. Consider running the 'nova-manage db "
"null_instance_uuid_scan' command."
msgstr ""

#: nova/image/glance.py:229
#, python-format
msgid ""
"Error contacting glance server '%(host)s:%(port)s' for '%(method)s', "
"%(extra)s."
msgstr ""
"Error contacting glance server '%(host)s:%(port)s' for '%(method)s', "
"%(extra)s."

#: nova/image/glance.py:342
#, python-format
msgid "Successfully transferred using %s"
msgstr ""

#: nova/image/s3.py:401
#, python-format
msgid "Failed to decrypt private key: %s"
msgstr "Failed to decrypt private key: %s"

#: nova/image/s3.py:408
#, python-format
msgid "Failed to decrypt initialization vector: %s"
msgstr "Failed to decrypt initialization vector: %s"

#: nova/image/s3.py:419
#, python-format
msgid "Failed to decrypt image file %(image_file)s: %(err)s"
msgstr "Failed to decrypt image file %(image_file)s: %(err)s"

#: nova/image/s3.py:431
msgid "Unsafe filenames in image"
msgstr "Unsafe filenames in image"

#: nova/image/download/file.py:30
msgid ""
"List of file systems that are configured in this file in the "
"image_file_url:<list entry name> sections"
msgstr ""

#: nova/image/download/file.py:78
msgid ""
"A unique ID given to each file system.  This is value is set in Glance "
"and agreed upon here so that the operator knowns they are dealing with "
"the same file system."
msgstr ""

#: nova/image/download/file.py:83
msgid "The path at which the file system is mounted."
msgstr ""

#: nova/image/download/file.py:92
#, python-format
msgid "The group %s(group_name) must be configured with an id."
msgstr ""

#: nova/image/download/file.py:110
#, python-format
msgid "The key %s is required in all file system descriptions."
msgstr ""

#: nova/image/download/file.py:120
#, python-format
msgid ""
"The key %(r)s is required in the location metadata to access the url "
"%(url)s."
msgstr ""

#: nova/image/download/file.py:127
#, python-format
msgid "The ID %(id)s is unknown."
msgstr ""

#: nova/image/download/file.py:135
#, python-format
msgid ""
"The mount point advertised by glance: %(glance_mount)s, does not match "
"the URL path: %(path)s"
msgstr ""

#: nova/image/download/file.py:153
#, python-format
msgid "No matching ID for the URL %s was found."
msgstr ""

#: nova/ipv6/account_identifier.py:39 nova/ipv6/rfc2462.py:34
#, python-format
msgid "Bad mac for to_global_ipv6: %s"
msgstr "Bad mac for to_global_ipv6: %s"

#: nova/ipv6/account_identifier.py:41 nova/ipv6/rfc2462.py:36
#, python-format
msgid "Bad prefix for to_global_ipv6: %s"
msgstr "Bad prefix for to_global_ipv6: %s"

#: nova/ipv6/account_identifier.py:43
#, python-format
msgid "Bad project_id for to_global_ipv6: %s"
msgstr "Bad project_id for to_global_ipv6: %s"

#: nova/keymgr/conf_key_mgr.py:58
msgid "keymgr.fixed_key not defined"
msgstr ""

#: nova/keymgr/single_key_mgr.py:60
msgid "cannot store arbitrary keys"
msgstr ""

#: nova/keymgr/single_key_mgr.py:70
msgid "cannot delete non-existent key"
msgstr ""

#: nova/network/base_api.py:71
msgid "instance is a required argument to use @refresh_cache"
msgstr "instance is a required argument to use @refresh_cache"

#: nova/network/ldapdns.py:322
msgid "ldap not installed"
msgstr ""

#: nova/network/ldapdns.py:333
msgid "This driver only supports type 'a' entries."
msgstr "This driver only supports type 'a' entries."

#: nova/network/linux_net.py:276
#, python-format
msgid "Unknown chain: %r"
msgstr "Unknown chain: %r"

#: nova/network/linux_net.py:1582
#, python-format
msgid "Failed to add interface: %s"
msgstr "Failed to add interface: %s"

#: nova/network/manager.py:2039
msgid ""
"The sum between the number of networks and the vlan start cannot be "
"greater than 4094"
msgstr ""
"The sum between the number of networks and the vlan start cannot be "
"greater than 4094"

#: nova/network/manager.py:2049
msgid "vlan must be an integer"
msgstr ""

#: nova/network/manager.py:2051
msgid "The vlan number cannot be greater than 4094"
msgstr ""

#: nova/network/manager.py:2054
msgid "The vlan number cannot be less than 1"
msgstr ""

#: nova/network/manager.py:2059
#, fuzzy, python-format
msgid ""
"The network range is not big enough to fit %(num_networks)s networks. "
"Network size is %(network_size)s"
msgstr ""
"The network range is not big enough to fit %(num_networks)s. Network size"
" is %(network_size)s"

#: nova/network/minidns.py:75 nova/network/minidns.py:106
#, fuzzy
msgid "Invalid name"
msgstr "Invalid volume"

#: nova/network/minidns.py:78
msgid "This driver only supports type 'a'"
msgstr "This driver only supports type 'a'"

#: nova/network/model.py:110
#, python-format
msgid "Invalid IP format %s"
msgstr ""

#: nova/network/neutronv2/api.py:281
#, python-format
msgid "Fixed IP %s is already in use."
msgstr ""

#: nova/network/neutronv2/api.py:359
#, python-format
msgid "empty project id for instance %s"
msgstr "empty project id for instance %s"

#: nova/network/neutronv2/api.py:405 nova/network/neutronv2/api.py:862
msgid "Multiple possible networks found, use a Network ID to be more specific."
msgstr ""

#: nova/network/neutronv2/api.py:433
#, python-format
msgid ""
"Multiple security groups found matching '%s'. Use an ID to be more "
"specific."
msgstr ""

#: nova/network/neutronv2/api.py:1208
#, python-format
msgid "Multiple floating IP pools matches found for name '%s'"
msgstr "Multiple floating IP pools matches found for name '%s'"

#: nova/network/security_group/neutron_driver.py:171
#, fuzzy
msgid "Security group id should be uuid"
msgstr "Security group id should be integer"

#: nova/network/security_group/neutron_driver.py:412
#: nova/network/security_group/neutron_driver.py:467
#, python-format
msgid "Security group %(name)s is not found for project %(project)s"
msgstr ""

#: nova/network/security_group/neutron_driver.py:428
#: nova/network/security_group/neutron_driver.py:483
#, python-format
msgid "instance_id %s could not be found as device id on any ports"
msgstr ""

#: nova/network/security_group/neutron_driver.py:511
#, python-format
msgid ""
"Security group %(security_group_name)s not associated with the instance "
"%(instance)s"
msgstr ""

#: nova/network/security_group/security_group_base.py:89
msgid "Type and Code must be integers for ICMP protocol type"
msgstr ""

#: nova/network/security_group/security_group_base.py:92
msgid "To and From ports must be integers"
msgstr ""

#: nova/network/security_group/security_group_base.py:134
#, python-format
msgid "This rule already exists in group %s"
msgstr "This rule already exists in group %s"

#: nova/objects/base.py:507
#, python-format
msgid "Cannot load '%s' in the base class"
msgstr ""

#: nova/objects/base.py:553
#, python-format
msgid "%(objname)s object has no attribute '%(attrname)s'"
msgstr ""

#: nova/objects/block_device.py:160
msgid "Volume does not belong to the requested instance."
msgstr ""

#: nova/objects/fields.py:30
#, python-format
msgid "Key %(key)s must be of type %(expected)s not %(actual)s"
msgstr ""

#: nova/objects/fields.py:40
#, python-format
msgid "Element %(key)s:%(val)s must be of type %(expected)s not %(actual)s"
msgstr ""

#: nova/objects/fields.py:166
#, python-format
msgid "Field `%s' cannot be None"
msgstr ""

#: nova/objects/fields.py:247
#, python-format
msgid "A string is required here, not %s"
msgstr ""

#: nova/objects/fields.py:287
msgid "A datetime.datetime is required here"
msgstr ""

#: nova/objects/fields.py:329 nova/objects/fields.py:338
#: nova/objects/fields.py:347
#, python-format
msgid "Network \"%s\" is not valid"
msgstr ""

#: nova/objects/fields.py:386
msgid "A list is required here"
msgstr ""

#: nova/objects/fields.py:406
msgid "A dict is required here"
msgstr ""

#: nova/objects/fields.py:473
msgid "A set is required here"
msgstr ""

#: nova/objects/fields.py:506
#, python-format
msgid "An object of type %s is required here"
msgstr ""

#: nova/objects/fields.py:549
msgid "A NetworkModel is required here"
msgstr ""

#: nova/objects/network.py:100
#, python-format
msgid "IPv6 netmask \"%s\" must be a netmask or integral prefix"
msgstr ""

#: nova/openstack/common/cliutils.py:36
#, python-format
msgid "Missing arguments: %s"
msgstr ""

#: nova/openstack/common/cliutils.py:154
#, python-format
msgid ""
"Field labels list %(labels)s has different number of elements than fields"
" list %(fields)s"
msgstr ""

#: nova/openstack/common/imageutils.py:76
#, python-format
msgid "Invalid input value \"%s\"."
msgstr ""

#: nova/openstack/common/imageutils.py:105
msgid "Snapshot list encountered but no header found!"
msgstr ""

#: nova/openstack/common/log.py:298
#, fuzzy, python-format
msgid "Deprecated: %s"
msgstr "Deprecated Config: %s"

#: nova/openstack/common/log.py:406
#, fuzzy, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr "Error reading image info file %(filename)s: %(error)s"

#: nova/openstack/common/log.py:467
#, python-format
msgid "syslog facility must be one of: %s"
msgstr "syslog facility must be one of: %s"

#: nova/openstack/common/log.py:715
#, fuzzy, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr "Fatal call to deprecated config %(msg)s"

#: nova/openstack/common/periodic_task.py:46
#, python-format
msgid "Unexpected argument for periodic task creation: %(arg)s."
msgstr ""

#: nova/openstack/common/policy.py:111
msgid "The JSON file that defines policies."
msgstr ""

#: nova/openstack/common/policy.py:114
msgid "Default rule. Enforced when a requested rule is not found."
msgstr ""

#: nova/openstack/common/policy.py:118
msgid ""
"Directories where policy configuration files are stored. They can be "
"relative to any directory in the search path defined by the config_dir "
"option, or absolute paths. The file defined by policy_file must exist for"
" these directories to be searched."
msgstr ""

#: nova/openstack/common/policy.py:142
#, python-format
msgid "Policy doesn't allow %s to be performed."
msgstr ""

#: nova/openstack/common/policy.py:239
#, python-format
msgid "Rules must be an instance of dict or Rules, got %s instead"
msgstr ""

#: nova/openstack/common/sslutils.py:101
#, python-format
msgid "Invalid SSL version : %s"
msgstr ""

#: nova/openstack/common/versionutils.py:90
#, python-format
msgid ""
"%(what)s is deprecated as of %(as_of)s in favor of %(in_favor_of)s and "
"may be removed in %(remove_in)s."
msgstr ""

#: nova/openstack/common/versionutils.py:94
#, python-format
msgid ""
"%(what)s is deprecated as of %(as_of)s and may be removed in "
"%(remove_in)s. It will not be superseded."
msgstr ""

#: nova/openstack/common/versionutils.py:98
#, python-format
msgid "%(what)s is deprecated as of %(as_of)s in favor of %(in_favor_of)s."
msgstr ""

#: nova/openstack/common/versionutils.py:101
#, python-format
msgid "%(what)s is deprecated as of %(as_of)s. It will not be superseded."
msgstr ""

#: nova/pci/whitelist.py:56
#, python-format
msgid "Invalid entry: '%s'"
msgstr ""

#: nova/pci/whitelist.py:61
#, python-format
msgid "Invalid entry: '%s'; Expecting list or dict"
msgstr ""

#: nova/pci/whitelist.py:67
#, python-format
msgid "Invalid entry: '%s'; Expecting dict"
msgstr ""

#: nova/scheduler/chance.py:50
msgid "Is the appropriate service running?"
msgstr "Is the appropriate service running?"

#: nova/scheduler/chance.py:55
msgid "Could not find another compute"
msgstr "Could not find another compute"

#: nova/scheduler/driver.py:65
msgid "Driver must implement select_destinations"
msgstr ""

#: nova/scheduler/filter_scheduler.py:79
msgid "There are not enough hosts available."
msgstr ""

#: nova/scheduler/host_manager.py:331
#, fuzzy, python-format
msgid "Host filter ignoring hosts: %s"
msgstr "Host filter fails for ignored host %(host)s"

#: nova/scheduler/host_manager.py:343
#, fuzzy, python-format
msgid "Host filter forcing available hosts to %s"
msgstr "Host filter fails for non-forced host %(host)s"

#: nova/scheduler/host_manager.py:346
#, python-format
msgid "No hosts matched due to not matching 'force_hosts' value of '%s'"
msgstr ""

#: nova/scheduler/host_manager.py:359
#, fuzzy, python-format
msgid "Host filter forcing available nodes to %s"
msgstr "Host filter fails for non-forced host %(host)s"

#: nova/scheduler/host_manager.py:362
#, python-format
msgid "No nodes matched due to not matching 'force_nodes' value of '%s'"
msgstr ""

#: nova/scheduler/utils.py:163
#, python-format
msgid ""
"Exceeded max scheduling attempts %(max_attempts)d for instance "
"%(instance_uuid)s. Last exception: %(exc)s"
msgstr ""

#: nova/scheduler/utils.py:196
msgid "Invalid value for 'scheduler_max_attempts', must be >= 1"
msgstr "Invalid value for 'scheduler_max_attempts', must be >= 1"

#: nova/scheduler/utils.py:287
msgid "ServerGroupAffinityFilter not configured"
msgstr ""

#: nova/scheduler/utils.py:291
msgid "ServerGroupAntiAffinityFilter not configured"
msgstr ""

#: nova/servicegroup/api.py:70
#, python-format
msgid "unknown ServiceGroup driver name: %s"
msgstr ""

#: nova/servicegroup/drivers/db.py:48
msgid "service is a mandatory argument for DB based ServiceGroup driver"
msgstr ""

#: nova/servicegroup/drivers/mc.py:44
#, fuzzy
msgid "memcached_servers not defined"
msgstr "Server name is not defined"

#: nova/servicegroup/drivers/mc.py:59
msgid "service is a mandatory argument for Memcached based ServiceGroup driver"
msgstr ""

#: nova/virt/block_device.py:399
#, python-format
msgid "Booting with volume %(volume_id)s at %(mountpoint)s"
msgstr "Booting with volume %(volume_id)s at %(mountpoint)s"

#: nova/virt/diagnostics.py:143
#, python-format
msgid "Invalid type for %s"
msgstr ""

#: nova/virt/diagnostics.py:147
#, python-format
msgid "Invalid type for %s entry"
msgstr ""

#: nova/virt/driver.py:735
msgid "Hypervisor driver does not support post_live_migration_at_source method"
msgstr ""

#: nova/virt/driver.py:1254
msgid "Event must be an instance of nova.virt.event.Event"
msgstr ""

#: nova/virt/event.py:33
msgid "Started"
msgstr ""

#: nova/virt/event.py:34
msgid "Stopped"
msgstr ""

#: nova/virt/event.py:35
msgid "Paused"
msgstr ""

#: nova/virt/event.py:36
msgid "Resumed"
msgstr ""

#: nova/virt/event.py:108
msgid "Unknown"
msgstr ""

#: nova/virt/hardware.py:55
#, python-format
msgid "No CPUs available after parsing %r"
msgstr ""

#: nova/virt/hardware.py:87 nova/virt/hardware.py:91
#, python-format
msgid "Invalid range expression %r"
msgstr ""

#: nova/virt/hardware.py:100
#, fuzzy, python-format
msgid "Invalid exclusion expression %r"
msgstr "Invalid reservation expiration %(expire)s."

#: nova/virt/hardware.py:107
#, fuzzy, python-format
msgid "Invalid inclusion expression %r"
msgstr "Invalid reservation expiration %(expire)s."

#: nova/virt/images.py:52
#, python-format
msgid "Path does not exist %(path)s"
msgstr ""

#: nova/virt/images.py:58
#, python-format
msgid "Failed to run qemu-img info on %(path)s : %(error)s"
msgstr ""

#: nova/virt/images.py:91
msgid "'qemu-img info' parsing failed."
msgstr "'qemu-img info' parsing failed."

#: nova/virt/images.py:97
#, python-format
msgid "fmt=%(fmt)s backed by: %(backing_file)s"
msgstr "fmt=%(fmt)s backed by: %(backing_file)s"

#: nova/virt/images.py:127
#, python-format
msgid "Converted to raw, but format is now %s"
msgstr "Converted to raw, but format is now %s"

#: nova/virt/disk/api.py:292
msgid "image already mounted"
msgstr "image already mounted"

#: nova/virt/disk/api.py:616
msgid "Not implemented on Windows"
msgstr "Not implemented on Windows"

#: nova/virt/disk/api.py:643
#, python-format
msgid "User %(username)s not found in password file."
msgstr "User %(username)s not found in password file."

#: nova/virt/disk/api.py:659
#, python-format
msgid "User %(username)s not found in shadow file."
msgstr "User %(username)s not found in shadow file."

#: nova/virt/disk/mount/api.py:145
#, python-format
msgid "partition search unsupported with %s"
msgstr "partition search unsupported with %s"

#: nova/virt/disk/mount/api.py:161
#, python-format
msgid "partition %s not found"
msgstr "partition %s not found"

#: nova/virt/disk/mount/api.py:162
#, python-format
msgid "Failed to map partitions: %s"
msgstr "Failed to map partitions: %s"

#: nova/virt/disk/mount/api.py:197
#, python-format
msgid "Failed to mount filesystem: %s"
msgstr "Failed to mount filesystem: %s"

#: nova/virt/disk/mount/loop.py:32
#, python-format
msgid "Could not attach image to loopback: %s"
msgstr "Could not attach image to loopback: %s"

#: nova/virt/disk/mount/nbd.py:65
msgid "nbd unavailable: module not loaded"
msgstr "nbd unavailable: module not loaded"

#: nova/virt/disk/mount/nbd.py:73
msgid "No free nbd devices"
msgstr "No free nbd devices"

#: nova/virt/disk/mount/nbd.py:90
#, python-format
msgid "qemu-nbd error: %s"
msgstr "qemu-nbd error: %s"

#: nova/virt/disk/mount/nbd.py:103
#, python-format
msgid "nbd device %s did not show up"
msgstr "nbd device %s did not show up"

#: nova/virt/disk/vfs/guestfs.py:69
#, python-format
msgid "libguestfs is not installed (%s)"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:82
#, python-format
msgid "libguestfs installed but not usable (%s)"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:127
#, fuzzy, python-format
msgid "No operating system found in %s"
msgstr "Floating ip not found for id %s"

#: nova/virt/disk/vfs/guestfs.py:133
#, python-format
msgid "Multi-boot operating system found in %s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:144
#, python-format
msgid "No mount points found in %(root)s of %(imgfile)s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:158
#, python-format
msgid ""
"Error mounting %(device)s to %(dir)s in image %(imgfile)s with libguestfs"
" (%(e)s)"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:211
#, python-format
msgid "Error mounting %(imgfile)s with libguestfs (%(e)s)"
msgstr ""

#: nova/virt/disk/vfs/localfs.py:46
#, fuzzy, python-format
msgid "File path %s not valid"
msgstr "injected file path not valid"

#: nova/virt/hyperv/driver.py:189
msgid "VIF plugging is not supported by the Hyper-V driver."
msgstr ""

#: nova/virt/hyperv/driver.py:194
msgid "VIF unplugging is not supported by the Hyper-V driver."
msgstr ""

#: nova/virt/hyperv/hostops.py:150
msgid "Host PowerOn is not supported by the Hyper-V driver"
msgstr ""

#: nova/virt/hyperv/hostutils.py:99
#, python-format
msgid "Host %(action)s is not supported by the Hyper-V driver"
msgstr ""

#: nova/virt/hyperv/imagecache.py:63
#, python-format
msgid ""
"Cannot resize the image to a size smaller than the VHD max. internal "
"size: %(vhd_size)s. Requested disk size: %(root_vhd_size)s"
msgstr ""

#: nova/virt/hyperv/livemigrationops.py:40
msgid "Live migration is supported starting with Hyper-V Server 2012"
msgstr ""

#: nova/virt/hyperv/livemigrationutils.py:43
#, fuzzy, python-format
msgid "Live migration is not supported on target host \"%s\""
msgstr "Live migration is not enabled on this host"

#: nova/virt/hyperv/livemigrationutils.py:46
#, fuzzy, python-format
msgid "Target live migration host \"%s\" is unreachable"
msgstr "Starting live migration for instance: %s"

#: nova/virt/hyperv/livemigrationutils.py:49
#, fuzzy, python-format
msgid "Live migration failed: %s"
msgstr "Live Migration failure: %(e)s"

#: nova/virt/hyperv/livemigrationutils.py:61
msgid "Live migration is not enabled on this host"
msgstr "Live migration is not enabled on this host"

#: nova/virt/hyperv/livemigrationutils.py:64
msgid "Live migration networks are not configured on this host"
msgstr "Live migration networks are not configured on this host"

#: nova/virt/hyperv/livemigrationutils.py:70 nova/virt/hyperv/vmutils.py:176
#, fuzzy, python-format
msgid "VM not found: %s"
msgstr "Item not found"

#: nova/virt/hyperv/livemigrationutils.py:72 nova/virt/hyperv/vmutils.py:185
#, fuzzy, python-format
msgid "Duplicate VM name found: %s"
msgstr "duplicate name found: %s"

#: nova/virt/hyperv/migrationops.py:109
#, python-format
msgid ""
"Cannot resize the root disk to a smaller size. Current size: "
"%(curr_root_gb)s GB. Requested size: %(new_root_gb)s GB"
msgstr ""

#: nova/virt/hyperv/migrationops.py:161
#, python-format
msgid "Config drive is required by instance: %s, but it does not exist."
msgstr ""

#: nova/virt/hyperv/migrationops.py:222
msgid "Cannot resize a VHD to a smaller size"
msgstr ""

#: nova/virt/hyperv/migrationops.py:267
#, python-format
msgid "Cannot find boot VHD file for instance: %s"
msgstr ""

#: nova/virt/hyperv/networkutils.py:45 nova/virt/hyperv/networkutilsv2.py:42
#, fuzzy, python-format
msgid "vswitch \"%s\" not found"
msgstr "partition %s not found"

#: nova/virt/hyperv/networkutils.py:58
#, fuzzy, python-format
msgid "Failed to create vswitch port %(port_name)s on switch %(vswitch_path)s"
msgstr "Created switch port %(vm_name)s on switch %(ext_path)s"

#: nova/virt/hyperv/networkutilsv2.py:55
msgid "No external vswitch found"
msgstr ""

#: nova/virt/hyperv/pathutils.py:81
#, python-format
msgid "The file copy from %(src)s to %(dest)s failed"
msgstr ""

#: nova/virt/hyperv/pathutils.py:204
#, python-format
msgid "Unable to mount SMBFS share: %(smbfs_share)s WMI exception: %(wmi_exc)s"
msgstr ""

#: nova/virt/hyperv/pathutils.py:230
#, python-format
msgid "Could not unmount share: %s"
msgstr ""

#: nova/virt/hyperv/utilsfactory.py:68
msgid ""
"The \"force_hyperv_utils_v1\" option cannot be set to \"True\" on Windows"
" Server / Hyper-V Server 2012 R2 or above as the WMI "
"\"root/virtualization\" namespace is no longer supported."
msgstr ""

#: nova/virt/hyperv/vhdutils.py:66 nova/virt/hyperv/vhdutilsv2.py:65
#, python-format
msgid "Unsupported disk format: %s"
msgstr ""

#: nova/virt/hyperv/vhdutils.py:162
#, python-format
msgid "Unable to obtain block size from VHD %(vhd_path)s"
msgstr ""

#: nova/virt/hyperv/vhdutils.py:209
msgid "Unsupported virtual disk format"
msgstr ""

#: nova/virt/hyperv/vhdutilsv2.py:160
#, python-format
msgid "Unable to obtain internal size from VHDX: %(vhd_path)s. Exception: %(ex)s"
msgstr ""

#: nova/virt/hyperv/vmops.py:145
#, python-format
msgid "VIF driver not found for network_api_class: %s"
msgstr ""

#: nova/virt/hyperv/vmops.py:230
#, python-format
msgid ""
"Cannot resize a VHD to a smaller size, the original size is %(old_size)s,"
" the newer size is %(new_size)s"
msgstr ""

#: nova/virt/hyperv/vmops.py:353
#, python-format
msgid "Requested VM Generation %s is not supported on this OS."
msgstr ""

#: nova/virt/hyperv/vmops.py:364
#, python-format
msgid "Requested VM Generation %s, but provided VHD instead of VHDX."
msgstr ""

#: nova/virt/hyperv/vmops.py:372 nova/virt/vmwareapi/vmops.py:613
#, python-format
msgid "Invalid config_drive_format \"%s\""
msgstr ""

#: nova/virt/hyperv/vmops.py:640
#, python-format
msgid "Could not get instance console log. Error: %s"
msgstr ""

#: nova/virt/hyperv/vmutils.py:147
#, fuzzy, python-format
msgid "Cannot get VM summary data for: %s"
msgstr "Failed to get metadata for ip: %s"

#: nova/virt/hyperv/vmutils.py:245
msgid ""
"The Windows account running nova-compute on this Hyper-V host doesn't "
"have the required permissions to create or operate the virtual machine."
msgstr ""

#: nova/virt/hyperv/vmutils.py:574
#, python-format
msgid "Operation failed with return value: %s"
msgstr ""

#: nova/virt/hyperv/vmutils.py:590
#, python-format
msgid ""
"WMI job failed with status %(job_state)d. Error details: %(err_sum_desc)s"
" - %(err_desc)s - Error code: %(err_code)d"
msgstr ""

#: nova/virt/hyperv/vmutils.py:601
#, python-format
msgid "WMI job failed with status %(job_state)d. Error details: %(error)s"
msgstr ""

#: nova/virt/hyperv/vmutils.py:607
#, python-format
msgid "WMI job failed with status %d. No error description available"
msgstr ""

#: nova/virt/hyperv/vmutils.py:732
msgid "Exceeded the maximum number of slots"
msgstr ""

#: nova/virt/hyperv/vmutils.py:735
msgid "Metrics collection is not supported on this version of Hyper-V"
msgstr ""

#: nova/virt/hyperv/volumeops.py:175
#, python-format
msgid ""
"Cannot log in target %(target_iqn)s. Unsupported iSCSI authentication "
"method: %(auth_method)s."
msgstr ""

#: nova/virt/hyperv/volumeops.py:300
#, python-format
msgid "Unable to find a mounted disk for target_iqn: %s"
msgstr "Unable to find a mounted disk for target_iqn: %s"

#: nova/virt/hyperv/volumeops.py:314
#, python-format
msgid ""
"Unable to find a mounted disk for target_iqn: %s. Please ensure that the "
"host's SAN policy is set to \"OfflineAll\" or \"OfflineShared\""
msgstr ""

#: nova/virt/hyperv/volumeops.py:372
#, python-format
msgid "Unable to attach volume to instance %s"
msgstr ""

#: nova/virt/hyperv/volumeutils.py:50
#, python-format
msgid "An error has occurred when calling the iscsi initiator: %s"
msgstr "An error has occurred when calling the iscsi initiator: %s"

#: nova/virt/hyperv/volumeutils.py:107 nova/virt/hyperv/volumeutilsv2.py:109
#, python-format
msgid "Failed to login target %s"
msgstr ""

#: nova/virt/ironic/client_wrapper.py:85
msgid "Unable to authenticate Ironic client."
msgstr ""

#: nova/virt/ironic/client_wrapper.py:135
#, python-format
msgid ""
"Error contacting Ironic server for '%(method)s'. Attempt %(attempt)d of "
"%(total)d"
msgstr ""

#: nova/virt/ironic/driver.py:297
#, python-format
msgid ""
"Failed to add deploy parameters on node %(node)s when provisioning the "
"instance %(instance)s"
msgstr ""

#: nova/virt/ironic/driver.py:323
#, python-format
msgid "Fail to clean up node %s parameters"
msgstr ""

#: nova/virt/ironic/driver.py:348
#, python-format
msgid "Failed to provision instance %(inst)s: %(reason)s"
msgstr ""

#: nova/virt/ironic/driver.py:591
#, python-format
msgid "Ironic node uuid not supplied to driver for instance %s."
msgstr ""

#: nova/virt/ironic/driver.py:613
#, python-format
msgid ""
"Ironic node: %(id)s failed to validate. (deploy: %(deploy)s, power: "
"%(power)s)"
msgstr ""

#: nova/virt/ironic/driver.py:686
#, python-format
msgid ""
"Error destroying the instance on node %(node)s. Provision state still "
"'%(state)s'."
msgstr ""

#: nova/virt/ironic/driver.py:877
#, python-format
msgid ""
"Ironic node: %(id)s virtual to physical interface count  missmatch (Vif "
"count: %(vif_count)d, Pif count: %(pif_count)d)"
msgstr ""

#: nova/virt/ironic/driver.py:998
#, python-format
msgid "Failed to request Ironic to rebuild instance %(inst)s: %(reason)s"
msgstr ""

#: nova/virt/libvirt/blockinfo.py:145
#, python-format
msgid "Unable to determine disk prefix for %s"
msgstr ""

#: nova/virt/libvirt/blockinfo.py:193
#, python-format
msgid "No free disk device names for prefix '%s'"
msgstr ""

#: nova/virt/libvirt/blockinfo.py:294
#, fuzzy, python-format
msgid "Unable to determine disk bus for '%s'"
msgstr "Unable to find vbd for vdi %s"

#: nova/virt/libvirt/driver.py:459
#, python-format
msgid ""
"Unexpected sysinfo_serial setting '%(actual)s'. Permitted values are "
"%(expect)s'"
msgstr ""

#: nova/virt/libvirt/driver.py:540
#, python-format
msgid "Nova requires libvirt version %(major)i.%(minor)i.%(micro)i or greater."
msgstr ""

#: nova/virt/libvirt/driver.py:637
msgid "operation time out"
msgstr ""

#: nova/virt/libvirt/driver.py:988
#, python-format
msgid ""
"Volume sets block size, but the current libvirt hypervisor '%s' does not "
"support custom block size"
msgstr ""

#: nova/virt/libvirt/driver.py:995
#, python-format
msgid "Volume sets block size, but libvirt '%s' or later is required."
msgstr ""

#: nova/virt/libvirt/driver.py:1092
msgid "Swap only supports host devices"
msgstr ""

#: nova/virt/libvirt/driver.py:1387
msgid "libvirt error while requesting blockjob info."
msgstr ""

#: nova/virt/libvirt/driver.py:1404
msgid "Only KVM and QEMU are supported"
msgstr ""

#: nova/virt/libvirt/driver.py:1408
#, python-format
msgid "Quiescing requires libvirt version %(version)s or greater"
msgstr ""

#: nova/virt/libvirt/driver.py:1414
msgid "QEMU guest agent is not enabled"
msgstr ""

#: nova/virt/libvirt/driver.py:1432
#, python-format
msgid ""
"Error from libvirt while quiescing %(instance_name)s: [Error Code "
"%(error_code)s] %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:1587
msgid "Found no disk to snapshot."
msgstr ""

#: nova/virt/libvirt/driver.py:1685
#, python-format
msgid "Unknown type: %s"
msgstr ""

#: nova/virt/libvirt/driver.py:1690
msgid "snapshot_id required in create_info"
msgstr ""

#: nova/virt/libvirt/driver.py:1747
#, python-format
msgid "Libvirt '%s' or later is required for online deletion of volume snapshots."
msgstr ""

#: nova/virt/libvirt/driver.py:1754
#, python-format
msgid "Unknown delete_info type %s"
msgstr ""

#: nova/virt/libvirt/driver.py:1790
#, python-format
msgid "Disk with id: %s not found attached to instance."
msgstr ""

#: nova/virt/libvirt/driver.py:1799
msgid "filename cannot be None"
msgstr ""

#: nova/virt/libvirt/driver.py:1828
#, python-format
msgid "no match found for %s"
msgstr ""

#: nova/virt/libvirt/driver.py:1885
#, python-format
msgid ""
"Relative blockcommit support was not detected. Libvirt '%s' or later is "
"required for online deletion of network storage-backed volume snapshots."
msgstr ""

#: nova/virt/libvirt/driver.py:2404 nova/virt/xenapi/vmops.py:1726
msgid "Guest does not have a console available"
msgstr "Guest does not have a console available"

#: nova/virt/libvirt/driver.py:2736
#, python-format
msgid "%s format is not supported"
msgstr ""

#: nova/virt/libvirt/driver.py:2843
#, python-format
msgid "Detaching PCI devices with libvirt < %(ver)s is not permitted"
msgstr ""

#: nova/virt/libvirt/driver.py:2934
#, python-format
msgid "Detaching SR-IOV ports with libvirt < %(ver)s is not permitted"
msgstr ""

#: nova/virt/libvirt/driver.py:3015
#, python-format
msgid ""
"Config requested an explicit CPU model, but the current libvirt "
"hypervisor '%s' does not support selecting CPU models"
msgstr ""
"Config requested an explicit CPU model, but the current libvirt "
"hypervisor '%s' does not support selecting CPU models"

#: nova/virt/libvirt/driver.py:3021
msgid "Config requested a custom CPU model, but no model name was provided"
msgstr "Config requested a custom CPU model, but no model name was provided"

#: nova/virt/libvirt/driver.py:3025
msgid "A CPU model name should not be set when a host CPU model is requested"
msgstr "A CPU model name should not be set when a host CPU model is requested"

#: nova/virt/libvirt/driver.py:3061
#, python-format
msgid ""
"Volume sets discard option, but libvirt %(libvirt)s or later is required,"
" qemu %(qemu)s or later is required."
msgstr ""

#: nova/virt/libvirt/driver.py:4039
#, python-format
msgid ""
"Error from libvirt while getting domain info for %(instance_name)s: "
"[Error Code %(error_code)s] %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:4327
msgid "Invalid vcpu_pin_set config, out of hypervisor cpu range."
msgstr ""

#: nova/virt/libvirt/driver.py:4858
msgid "Block migration can not be used with shared storage."
msgstr "Block migration can not be used with shared storage."

#: nova/virt/libvirt/driver.py:4868
msgid "Live migration can not be used without shared storage."
msgstr "Live migration can not be used without shared storage."

#: nova/virt/libvirt/driver.py:4951
#, python-format
msgid ""
"Unable to migrate %(instance_uuid)s: Disk of instance is too "
"large(available on destination host:%(available)s < need:%(necessary)s)"
msgstr ""
"Unable to migrate %(instance_uuid)s: Disk of instance is too "
"large(available on destination host:%(available)s < need:%(necessary)s)"

#: nova/virt/libvirt/driver.py:4990
#, python-format
msgid ""
"CPU doesn't have compatibility.\n"
"\n"
"%(ret)s\n"
"\n"
"Refer to %(u)s"
msgstr ""
"CPU doesn't have compatibility.\n"
"\n"
"%(ret)s\n"
"\n"
"Refer to %(u)s"

#: nova/virt/libvirt/driver.py:5052
#, python-format
msgid "The firewall filter for %s does not exist"
msgstr "The firewall filter for %s does not exist"

#: nova/virt/libvirt/driver.py:5121
msgid ""
"Your libvirt version does not support the VIR_DOMAIN_XML_MIGRATABLE flag "
"or your destination node does not support retrieving listen addresses.  "
"In order for live migration to work properly, you must configure the "
"graphics (VNC and/or SPICE) listen addresses to be either the catch-all "
"address (0.0.0.0 or ::) or the local address (127.0.0.1 or ::1)."
msgstr ""

#: nova/virt/libvirt/driver.py:5138
msgid ""
"Your libvirt version does not support the VIR_DOMAIN_XML_MIGRATABLE flag,"
" and the  graphics (VNC and/or SPICE) listen addresses on the destination"
" node do not match the addresses on the source node. Since the source "
"node has listen addresses set to either the catch-all address (0.0.0.0 or"
" ::) or the local address (127.0.0.1 or ::1), the live migration will "
"succeed, but the VM will continue to listen on the current addresses."
msgstr ""

#: nova/virt/libvirt/driver.py:5550
#, python-format
msgid ""
"Error from libvirt while getting description of %(instance_name)s: [Error"
" Code %(error_code)s] %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:5682
msgid "Unable to resize disk down."
msgstr ""

#: nova/virt/libvirt/driver.py:5693
msgid "Migration is not supported for LVM backed instances"
msgstr ""

#: nova/virt/libvirt/host.py:174
#, python-format
msgid "Can not handle authentication request for %d credentials"
msgstr "Can not handle authentication request for %d credentials"

#: nova/virt/libvirt/host.py:255
#, python-format
msgid "Connection to libvirt lost: %s"
msgstr ""

#: nova/virt/libvirt/host.py:486
#, python-format
msgid ""
"Error from libvirt while looking up %(instance_id)s: [Error Code "
"%(error_code)s] %(ex)s"
msgstr ""

#: nova/virt/libvirt/host.py:508
#, python-format
msgid ""
"Error from libvirt while looking up %(instance_name)s: [Error Code "
"%(error_code)s] %(ex)s"
msgstr ""
"Error from libvirt while looking up %(instance_name)s: [Error Code "
"%(error_code)s] %(ex)s"

#: nova/virt/libvirt/imagebackend.py:98
msgid ""
"Incompatible settings: ephemeral storage encryption is supported only for"
" LVM images."
msgstr ""

#: nova/virt/libvirt/imagebackend.py:277
#, python-format
msgid "Could not load line %(line)s, got error %(error)s"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:292
msgid "Attempted overwrite of an existing value."
msgstr ""

#: nova/virt/libvirt/imagebackend.py:340
msgid "clone() is not implemented"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:515
msgid "You should specify images_volume_group flag to use LVM images."
msgstr ""

#: nova/virt/libvirt/imagebackend.py:577
msgid "Instance disk to be encrypted but no context provided"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:624
msgid "You should specify images_rbd_pool flag to use rbd images."
msgstr ""

#: nova/virt/libvirt/imagebackend.py:717
msgid "installed version of librbd does not support cloning"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:728
msgid "Image is not raw format"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:736
msgid "No image locations are accessible"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:756
#, python-format
msgid "Unknown image_type=%s"
msgstr "Unknown image_type=%s"

#: nova/virt/libvirt/imagebackend.py:784
#, python-format
msgid "Unknown hw_disk_discard=%s"
msgstr ""

#: nova/virt/libvirt/lvm.py:91
#, python-format
msgid ""
"Insufficient Space on Volume Group %(vg)s. Only %(free_space)db "
"available, but %(size)db required by volume %(lv)s."
msgstr ""
"Insufficient Space on Volume Group %(vg)s. Only %(free_space)db "
"available, but %(size)db required by volume %(lv)s."

#: nova/virt/libvirt/lvm.py:139
#, fuzzy, python-format
msgid "vg %s must be LVM volume group"
msgstr "Path %s must be LVM logical volume"

#: nova/virt/libvirt/lvm.py:182
#, python-format
msgid "Path %s must be LVM logical volume"
msgstr "Path %s must be LVM logical volume"

#: nova/virt/libvirt/lvm.py:262
#, python-format
msgid "volume_clear='%s' is not handled"
msgstr ""

#: nova/virt/libvirt/rbd_utils.py:105
msgid "rbd python libraries not found"
msgstr ""

#: nova/virt/libvirt/rbd_utils.py:160
msgid "Not stored in rbd"
msgstr ""

#: nova/virt/libvirt/rbd_utils.py:164
msgid "Blank components"
msgstr ""

#: nova/virt/libvirt/rbd_utils.py:167
msgid "Not an rbd snapshot"
msgstr ""

#: nova/virt/libvirt/utils.py:81
msgid "Cannot find any Fibre Channel HBAs"
msgstr ""

#: nova/virt/libvirt/utils.py:450
msgid "Can't retrieve root device path from instance libvirt configuration"
msgstr "Can't retrieve root device path from instance libvirt configuration"

#: nova/virt/libvirt/vif.py:343 nova/virt/libvirt/vif.py:523
#: nova/virt/libvirt/vif.py:676
msgid "vif_type parameter must be present for this vif_driver implementation"
msgstr ""

#: nova/virt/libvirt/vif.py:349 nova/virt/libvirt/vif.py:682
#, fuzzy, python-format
msgid "Unexpected vif_type=%s"
msgstr "Unexpected error: %s"

#: nova/virt/libvirt/vif.py:529
#, python-format
msgid "Plug vif failed because of unexpected vif_type=%s"
msgstr ""

#: nova/virt/libvirt/volume.py:340
#, python-format
msgid "iSCSI device not found at %s"
msgstr "iSCSI device not found at %s"

#: nova/virt/libvirt/volume.py:898
#, fuzzy, python-format
msgid "AoE device not found at %s"
msgstr "iSCSI device not found at %s"

#: nova/virt/libvirt/volume.py:1088
msgid "We are unable to locate any Fibre Channel devices"
msgstr ""

#: nova/virt/libvirt/volume.py:1107
#, fuzzy
msgid "Fibre Channel device not found."
msgstr "iSCSI device not found at %s"

#: nova/virt/vmwareapi/driver.py:128
msgid ""
"Must specify host_ip, host_username and host_password to use "
"vmwareapi.VMwareVCDriver"
msgstr ""

#: nova/virt/vmwareapi/driver.py:137
#, python-format
msgid "Invalid Regular Expression %s"
msgstr ""

#: nova/virt/vmwareapi/driver.py:153
#, python-format
msgid "All clusters specified %s were not found in the vCenter"
msgstr ""

#: nova/virt/vmwareapi/driver.py:383
#, python-format
msgid "The resource %s does not exist"
msgstr ""

#: nova/virt/vmwareapi/driver.py:602
msgid ""
"Multiple hosts may be managed by the VMWare vCenter driver; therefore we "
"do not return uptime for just one host."
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:47
msgid "Datastore name cannot be None"
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:49
msgid "Datastore reference cannot be None"
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:51
msgid "Invalid capacity"
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:54
msgid "Capacity is smaller than free space"
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:117
msgid "datastore name empty"
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:122 nova/virt/vmwareapi/ds_util.py:158
msgid "path component cannot be None"
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:175
msgid "datastore path empty"
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:303
#, python-format
msgid "Storage policy %s did not match any datastores"
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:307
#, python-format
msgid "Datastore regex %s did not match any datastores"
msgstr ""

#: nova/virt/vmwareapi/error_util.py:30
msgid "No root disk defined."
msgstr ""

#: nova/virt/vmwareapi/error_util.py:34
msgid "Default PBM policy is required if PBM is enabled."
msgstr ""

#: nova/virt/vmwareapi/error_util.py:38
msgid "The default PBM policy doesn't exist on the backend."
msgstr ""

#: nova/virt/vmwareapi/io_util.py:122
#, python-format
msgid "Glance image %s is in killed state"
msgstr "Glance image %s is in killed state"

#: nova/virt/vmwareapi/io_util.py:130
#, python-format
msgid "Glance image %(image_id)s is in unknown state - %(state)s"
msgstr "Glance image %(image_id)s is in unknown state - %(state)s"

#: nova/virt/vmwareapi/network_util.py:134
msgid ""
"ESX SOAP server returned an empty port group for the host system in its "
"response"
msgstr ""
"ESX SOAP server returned an empty port group for the host system in its "
"response"

#: nova/virt/vmwareapi/vm_util.py:272
#, python-format
msgid "%s is not supported."
msgstr ""

#: nova/virt/vmwareapi/vm_util.py:1043
msgid "No host available on cluster"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:421
msgid "Image disk size greater than requested disk size"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:461
#, python-format
msgid "disk type '%s' not supported"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:809
msgid "instance is not powered on"
msgstr "instance is not powered on"

#: nova/virt/vmwareapi/vmops.py:937
msgid "pause not supported for vmwareapi"
msgstr "pause not supported for vmwareapi"

#: nova/virt/vmwareapi/vmops.py:941
msgid "unpause not supported for vmwareapi"
msgstr "unpause not supported for vmwareapi"

#: nova/virt/vmwareapi/vmops.py:959
#, fuzzy
msgid "instance is powered off and cannot be suspended."
msgstr "instance is powered off and can not be suspended."

#: nova/virt/vmwareapi/vmops.py:979
msgid "instance is not in a suspended state"
msgstr "instance is not in a suspended state"

#: nova/virt/vmwareapi/vmops.py:1065
msgid "Unable to shrink disk."
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1488
#, python-format
msgid "No device with interface-id %s exists on VM"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1498
#, python-format
msgid "No device with MAC address %s exists on the VM"
msgstr ""

#: nova/virt/vmwareapi/volumeops.py:329 nova/virt/vmwareapi/volumeops.py:492
#, python-format
msgid "%s does not support disk hotplug."
msgstr ""

#: nova/virt/vmwareapi/volumeops.py:354 nova/virt/vmwareapi/volumeops.py:514
#, fuzzy
msgid "Unable to find iSCSI Target"
msgstr "Unable to find address %r"

#: nova/virt/vmwareapi/volumeops.py:471 nova/virt/vmwareapi/volumeops.py:522
#, fuzzy
msgid "Unable to find volume"
msgstr "Failed to find volume in db"

#: nova/virt/xenapi/agent.py:463
#, python-format
msgid "OpenSSL error: %s"
msgstr "OpenSSL error: %s"

#: nova/virt/xenapi/driver.py:114
msgid ""
"Must specify connection_url, connection_username (optionally), and "
"connection_password to use compute_driver=xenapi.XenAPIDriver"
msgstr ""

#: nova/virt/xenapi/driver.py:640
msgid "Host startup on XenServer is not supported."
msgstr "Host startup on XenServer is not supported."

#: nova/virt/xenapi/fake.py:851
#, python-format
msgid "xenapi.fake does not have an implementation for %s"
msgstr "xenapi.fake does not have an implementation for %s"

#: nova/virt/xenapi/fake.py:959
#, python-format
msgid ""
"xenapi.fake does not have an implementation for %s or it has been called "
"with the wrong number of arguments"
msgstr ""
"xenapi.fake does not have an implementation for %s or it has been called "
"with the wrong number of arguments"

#: nova/virt/xenapi/host.py:88
#, fuzzy, python-format
msgid "Aggregate for host %(host)s count not be found."
msgstr "Compute host %(host)s could not be found."

#: nova/virt/xenapi/host.py:186
msgid "Failed to parse information about a pci device for passthrough"
msgstr ""

#: nova/virt/xenapi/network_utils.py:31
#, python-format
msgid "Found non-unique network for name_label %s"
msgstr "Found non-unique network for name_label %s"

#: nova/virt/xenapi/network_utils.py:49
#, python-format
msgid "Found non-unique network for bridge %s"
msgstr "Found non-unique network for bridge %s"

#: nova/virt/xenapi/network_utils.py:52
#, python-format
msgid "Found no network for bridge %s"
msgstr "Found no network for bridge %s"

#: nova/virt/xenapi/pool.py:74 nova/virt/xenapi/pool.py:122
msgid "setup in progress"
msgstr ""

#: nova/virt/xenapi/pool.py:75 nova/virt/xenapi/pool.py:123
msgid "aggregate deleted"
msgstr ""

#: nova/virt/xenapi/pool.py:76
msgid "aggregate in error"
msgstr ""

#: nova/virt/xenapi/pool.py:121
msgid "no hosts to remove"
msgstr ""

#: nova/virt/xenapi/pool.py:145
#, python-format
msgid "Unable to eject %s from the pool; pool not empty"
msgstr ""

#: nova/virt/xenapi/pool.py:160
#, python-format
msgid "Unable to eject %s from the pool; No master found"
msgstr ""

#: nova/virt/xenapi/pool.py:180
#, python-format
msgid "Unable to join %s in the pool"
msgstr ""

#: nova/virt/xenapi/vif.py:100
#, python-format
msgid "Found no PIF for device %s"
msgstr "Found no PIF for device %s"

#: nova/virt/xenapi/vif.py:119
#, python-format
msgid ""
"PIF %(pif_uuid)s for network %(bridge)s has VLAN id %(pif_vlan)d. "
"Expected %(vlan_num)d"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:208
#, python-format
msgid ""
"Device id %(id)s specified is not supported by hypervisor version "
"%(version)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:403
#, python-format
msgid "Unable to unplug VBD %s"
msgstr "Unable to unplug VBD %s"

#: nova/virt/xenapi/vm_utils.py:406
#, python-format
msgid "Reached maximum number of retries trying to unplug VBD %s"
msgstr "Reached maximum number of retries trying to unplug VBD %s"

#: nova/virt/xenapi/vm_utils.py:418
#, python-format
msgid "Unable to destroy VBD %s"
msgstr "Unable to destroy VBD %s"

#: nova/virt/xenapi/vm_utils.py:471
#, python-format
msgid "Unable to destroy VDI %s"
msgstr "Unable to destroy VDI %s"

#: nova/virt/xenapi/vm_utils.py:633
#, python-format
msgid "No primary VDI found for %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:766
#, python-format
msgid ""
"Only file-based SRs (ext/NFS) are supported by this feature.  SR %(uuid)s"
" is of type %(type)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:900
#, python-format
msgid ""
"VDI %(vdi_ref)s is %(virtual_size)d bytes which is larger than flavor "
"size of %(new_disk_size)d bytes."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:911 nova/virt/xenapi/vmops.py:1172
msgid "Can't resize a disk to 0 GB."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:963
msgid "Disk must have only one partition."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:968
#, python-format
msgid "Disk contains a filesystem we are unable to resize: %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:973
msgid "The only partition should be partition 1."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:984
#, python-format
msgid "Attempted auto_configure_disk failed because: %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1542
#, python-format
msgid ""
"Kernel/Ramdisk image is too large: %(vdi_size)d bytes, max %(max_size)d "
"bytes"
msgstr ""
"Kernel/Ramdisk image is too large: %(vdi_size)d bytes, max %(max_size)d "
"bytes"

#: nova/virt/xenapi/vm_utils.py:1913
msgid "Cannot find SR of content-type ISO"
msgstr "Cannot find SR of content-type ISO"

#: nova/virt/xenapi/vm_utils.py:2119
#, python-format
msgid "VHD coalesce attempts exceeded (%d), giving up..."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2154
#, python-format
msgid "Timeout waiting for device %s to be created"
msgstr "Timeout waiting for device %s to be created"

#: nova/virt/xenapi/vm_utils.py:2332
msgid ""
"Shrinking the filesystem down with resize2fs has failed, please check if "
"you have enough free space on your disk."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2491
msgid "This domU must be running on the host specified by connection_url"
msgstr ""

#: nova/virt/xenapi/vmops.py:179
msgid "Error: Agent is disabled"
msgstr ""

#: nova/virt/xenapi/vmops.py:598
msgid "Failed to spawn, rolling back"
msgstr "Failed to spawn, rolling back"

#: nova/virt/xenapi/vmops.py:609
msgid "Unable to find root VBD/VDI for VM"
msgstr "Unable to find root VBD/VDI for VM"

#: nova/virt/xenapi/vmops.py:900
#, fuzzy
msgid "Unable to terminate instance."
msgstr "Failed to terminate instance"

#: nova/virt/xenapi/vmops.py:1148
msgid "Can't resize down ephemeral disks."
msgstr ""

#: nova/virt/xenapi/vmops.py:1426
msgid "instance has a kernel or ramdisk but not both"
msgstr "instance has a kernel or ramdisk but not both"

#: nova/virt/xenapi/vmops.py:1574
#, python-format
msgid "Instance is already in Rescue Mode: %s"
msgstr "Instance is already in Rescue Mode: %s"

#: nova/virt/xenapi/vmops.py:2010
#, python-format
msgid "Destination host:%s must be in the same aggregate as the source server"
msgstr ""

#: nova/virt/xenapi/vmops.py:2031
#, fuzzy
msgid "No suitable network for migrate"
msgstr "Bad networks format"

#: nova/virt/xenapi/vmops.py:2037
#, python-format
msgid "PIF %s does not contain IP address"
msgstr ""

#: nova/virt/xenapi/vmops.py:2050
msgid "Migrate Receive failed"
msgstr "Migrate Receive failed"

#: nova/virt/xenapi/vmops.py:2124
msgid "XAPI supporting relax-xsm-sr-check=true required"
msgstr ""

#: nova/virt/xenapi/vmops.py:2135
#, python-format
msgid "assert_can_migrate failed because: %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:2195
msgid "Migrate Send failed"
msgstr "Migrate Send failed"

#: nova/virt/xenapi/volume_utils.py:86 nova/virt/xenapi/volume_utils.py:262
#, python-format
msgid "Unable to obtain target information %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:165
#, python-format
msgid "Unable to introduce VDI on SR %s"
msgstr "Unable to introduce VDI on SR %s"

#: nova/virt/xenapi/volume_utils.py:169
#, python-format
msgid ""
"VDI not found on SR %(sr)s (vdi_uuid %(vdi_uuid)s, target_lun "
"%(target_lun)s)"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:180
#, python-format
msgid "Unable to get record of VDI %s on"
msgstr "Unable to get record of VDI %s on"

#: nova/virt/xenapi/volume_utils.py:202
#, python-format
msgid "Unable to introduce VDI for SR %s"
msgstr "Unable to introduce VDI for SR %s"

#: nova/virt/xenapi/volume_utils.py:300
#, python-format
msgid "Unable to find SR from VBD %s"
msgstr "Unable to find SR from VBD %s"

#: nova/virt/xenapi/volume_utils.py:311
#, python-format
msgid "Unable to find SR from VDI %s"
msgstr ""

#: nova/virt/xenapi/client/session.py:79
#, python-format
msgid "%(vendor)s %(product)s %(version)s"
msgstr ""

#: nova/virt/xenapi/client/session.py:87
msgid "Unable to log in to XenAPI (is the Dom0 disk full?)"
msgstr "Unable to log in to XenAPI (is the Dom0 disk full?)"

#: nova/virt/xenapi/client/session.py:107
#, python-format
msgid "Plugin version mismatch (Expected %(exp)s, got %(got)s)"
msgstr ""

#: nova/virt/xenapi/image/bittorrent.py:80
msgid ""
"Cannot create default bittorrent URL without torrent_base_url set or "
"torrent URL fetcher extension"
msgstr ""

#: nova/virt/xenapi/image/bittorrent.py:84
msgid "Multiple torrent URL fetcher extensions found. Failing."
msgstr ""

#: nova/vnc/xvp_proxy.py:94
#, python-format
msgid "Error in handshake format: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:99
#, python-format
msgid "Error in handshake: %s"
msgstr "Error in handshake: %s"

#: nova/vnc/xvp_proxy.py:114
#, python-format
msgid "Invalid request: %s"
msgstr "Invalid request: %s"

#: nova/vnc/xvp_proxy.py:134
#, python-format
msgid "Request: %s"
msgstr "Request: %s"

#: nova/vnc/xvp_proxy.py:137
#, python-format
msgid "Request made with missing token: %s"
msgstr "Request made with missing token: %s"

#: nova/vnc/xvp_proxy.py:147
#, python-format
msgid "Request made with invalid token: %s"
msgstr "Request made with invalid token: %s"

#: nova/vnc/xvp_proxy.py:154
#, python-format
msgid "Unexpected error: %s"
msgstr "Unexpected error: %s"

#: nova/vnc/xvp_proxy.py:174
#, python-format
msgid "Starting nova-xvpvncproxy node (version %s)"
msgstr "Starting nova-xvpvncproxy node (version %s)"

#: nova/volume/cinder.py:301
#, python-format
msgid "volume '%(vol)s' status must be 'in-use'. Currently in '%(status)s' status"
msgstr ""

#: nova/volume/cinder.py:309
#, python-format
msgid "volume '%(vol)s' status must be 'available'. Currently in '%(status)s'"
msgstr ""

#: nova/volume/cinder.py:314
#, python-format
msgid "volume %s already attached"
msgstr ""

#: nova/volume/cinder.py:325
#, python-format
msgid ""
"Instance %(instance)s and volume %(vol)s are not in the same "
"availability_zone. Instance is in %(ins_zone)s. Volume is in %(vol_zone)s"
msgstr ""

#: nova/volume/cinder.py:337
#, python-format
msgid "volume %s already detached"
msgstr ""

